- boilerplate/package.json
`embark demo` that you suggested in #20 was failing with:
```
npm WARN package.json app_name@0.0.1 No description
npm WARN package.json app_name@0.0.1 No repository field.
npm WARN package.json app_name@0.0.1 No README data
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: embark-framework@'embark-framework@develop'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.3.0","0.4.0","0.4.1","0.4.2","0.4.3"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your …
```
> fixed package.json

- lib/blockchain.js
Hello this PR allows the `embark blockchain` command to specify the `rpcHost` from the configuration.
> Allow blockchain rpchost to be configurable

- lib/chain_manager.js
> default to empty set when chains.json is missing

- bin/embark
- lib/blockchain.js
- lib/index.js
Hello,
I've added the option to run geth with any argument/command. Advantage is this allows me to run geth on the development chain with the configuration embark uses.
Our immediate motive was that we use the development environment for local testing/development and easy interacting with ethereum can be handy then.
Open for suggestions or critique.
> Add option to run geth with any command

- bin/embark
When altering this framework locally, I use [npm link](https://docs.npmjs.com/cli/link) to use my local framework version from my local project.  This simple change makes it work locally, and (I'm 99% confident) should work fine in the final npm module as well.
> Alter require to support `npm link`

- Gruntfile.coffee
This was causing a "grunt-cli not found" message even when you had the grunt-cli npm module installed.
> Don't loadNpmTasks grunt-cli (not needed)

- README.md
I've tested this to allow installation of embark-framework without requiring using sudo.
> npm -g install with no sudo

- lib/blockchain.js
- lib/index.js
This function behaves as follows:
```
gethCommand = Embark.getStartBlockchainCommand(env, true)
console.log gethCommand
```
I implemented it because I want to `spawn` a child process rather than blocking with `exec`, but this method may have other uses like checking the config before executing or for tests.
> implement `getStartBlockchainCommand` to return geth CLI string within app

- bin/embark
- lib/index.js
Needed to emulate `embark deploy` in node
> make `copyMinerJavascriptToTemp` step public

- js/mine.js
`embark blockchain` will now stop mining once the account is funded, fixing #74 :
```
=== datadir created
running: geth --datadir="/tmp/embark" --logfile="/tmp/embark.log" --port 30304 --rpc --rpcport 8101 --rpcaddr localhost --networkid 52790 --rpccorsdomain "*" --minerthreads "1" --mine --genesis="config/genesis/dev_genesis.json" --rpcapi "eth,web3" --maxpeers 4 --password config/password account list
Fatal: Could not list accounts: no keys in store
Fatal: Could not list accounts: no keys in store
running: geth --datadir="/tmp/embark" --logfile="/tmp/embark.log" --port 30304 --rpc --rpcport 8101 --rpcaddr localhost --networkid 52790 --rpccorsdomain "*" --minerthreads "1" --mine --genesis="config/genesis/dev_genesis.json" --rpcapi "eth,web3" --maxpeers 4 --password config/password …
```
> stop blockWatcher filter with correct method name. fixes #74

- README.md
- bin/embark
- lib/config/blockchain.js
- test/config.blockchain.js
I've added the ability to configure the chains file per environment, as discussed on gitter on 3th september.
Tested with my own software. Not certain if loading of value per environment is done in the best way (embark.js), I'd suspect there's a better way to load environment specific config file.
> Allowing to define chains file per environment/chain

- lib/ipfs.js
I have recently installed `ipfs` from Homebrew, which does not install to `~/go/bin/ipfs`.
As a result, `embark ipfs` did not work. This patch uses `which` to use the path for `ipfs`
if it is found in the user's `PATH`. If not, it assumes `~/go/bin/ipfs` as before.
> Add support for other paths for ipfs binary

- js/mine.js
Miner.stop accepts a config.threads option. While the wiki says its optional, it is actually required
https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#minerstop
> miner stop config threads

- lib/test.js
This is so it can be used before deploying contracts. It has useful functions such as sha3() on it..
> Setting web3 on Embark Test constructor

- lib/index.js
Althought the ```embark --help``` states the **build** command will deploy and build the Dapp at *dist/*, that wasn't happening. The **build** command only deploys contracts in the blockchain, but no assets are generated whatsoever.
This fixes that.
> embark build wasn't deploying assets

- lib/test.js
- package.json
- Fixes usage of `contractsManager.build` to actually provide a callback.
- Fixes `done is not a function` issues.
- Properly passes the `options` object to the sim provider
- Locks down the version of `solc` since a newer version causes compilation issues.
> Fix broken test environment

- README.md
If the pragma is not specified in the SimpleStorage contract it fails to deploy. Added the pragma directive the same way it's specified in the simple_storage.sol in the demo folder.
> Updated README  to include pragma on SimpleStorage contract

- lib/core/config.js
- lib/core/fs.js
Implemented logic to check if file embark.json exists and to prevent NodeJS exception when running command 'embark blockchain' if file doesn't exist or command is run outside Dapp folder.
> Prevent node exception when running command 'embark blockchain'

- lib/core/services.js
- Implemented logic to show the version of the connected IPFS node on the dashboard.
- It uses http call to the IPFS api endpoint (/api/v0/version) so no IPFS libs were used (just node http module).
> Implemented logic to show version of the connected IPFS node 

- boilerplate/package.json
- lib/cmds/template_generator.js
- lib/core/utils.js
Update `test` command to run `embark test`
Update `name` in `package.json` to be something more easily replaceable.
Use shelljs' `sed` to replace above flag with DApp name
Remove `main` directive from `package.json`, since it references non-existent file.
> Updates to boilerplate and template creation

- boilerplate/.editorconfig
Adds an editorconfig to the boilerplate, with the following options:
For .js/.sol/.json
* space indents
* indentation depth of 2
* crlf line endings
* utf-8 charset
* trailing whitespace trimming
* final newline enforcement
For .md:
* prevent trimming of trailing whitespace
Note: these are all just defaults pulled from other projects, and I don't have a strong opinion on any of them, except the space indentation and depth of 2.
> Add editorconfig to boilerplate

- lib/core/test.js
* Add ability to configure `logLevel` and `logging` during contract deployment in test setup (e.g. `EmbarkSpec.deployAll`).
* Add the ability to override the base contracts config (e.g. `embark.json`)
* Persist options on the `Test` object instance.
These change might be a bit controversial, but I found them very useful when testing a contract that has many sub-contracts.  Since they're not fleshed out yet, and I want to test one of the leaf contracts in isolation, this lets me create a `leaf_contract.json` that only deploys the contract in question.
This did raise a potential issue, though: if, for example, `LeafContract` implements `Owned`, I have to list (and subsequently deploy) `Owned` in order for `LeafContract` to successfully compile.  It might be nice to be able to separate …
> More testing options

- demo/app/js/index.js
Remove an unexpected + sign preceding a simple instruction.
> fix typo in index.js

- boilerplate/app/index.html
pointed it to the latest documentation instead of old wiki
> Updated the link on boilerplate app (generated by embark new) 

- README.md
- boilerplate/test/contract_spec.js
This updates the boilerplate test to match what #246 changes.
> update boilerplate test after PR#246

- demo/app/js/index.js
- demo/package.json
- js/build/embark.bundle.js
- js/embark.js
- Implemented changes on EmbarkJS file to allow multiple storage providers. Currently it supports IPFS but these changes will allow additional providers (e.g. Swarm)
- Changed demo project to use the storage enhancements (setProvider returns a Promise)
- When refactoring kept logic in a way to ensure backwards compatibility for storage calls
- Tested with demo and test_app
- Updated package.json to reflect latest embark npm version
> Refactored EmbarkJS to allow multiple storage providers

- lib/index.js
- package.json
Error message is self explainatory.
Include ethereumjs-testrpc to save end users another step of installing this as a global package.
> Show error message if unable to deploy contracts. Include ethereumjs-testrpc

- lib/core/logger.js
I found this when trying to compile some broken solidity, the effect was that embark crashes without logging anything when it should have logged the solidity compiler error.
> fix crash in logger if message is null or undefined

- lib/cmds/blockchain/blockchain.js
I tried Embark today. When starting blockchain for the first time, my Embark environment raised a warning and then crashed with the following message:
> Cannot read property '1' of null
The problem is described here: https://stackoverflow.com/questions/43481948/embark-demo-not-working. The accounts check was unsafe by checking for specific error cases instead of checking that accounts were actually found in the `client.listAccountsCommand()` result.
> fix for no accounts on init with warning messages

- package.json
The bignumber repo that web3 relied on was deleted so anything earlier than 0.19.1 is broken
> Update web3 version to 0.19.1

- demo/config/contracts.json
- docs/using-contracts.rst
- lib/contracts/deploy.js
Fixing #319 .
Added handling of "from" and "fromIndex" of contract configuration.
> [*] Fixing #319: option to use particular account for contract deployment

- lib/contracts/code_templates/define-when-env-loaded.js.ejs
This pull request should improve the check for when the environment is loaded. In the situation of a browser plugin, for instance, it's possible the 'DOMContentLoaded' event has already fired so waiting for it will be fruitless.
test document.readyState and only add the DOMContentLoaded event listener if that event hasn't already fired.
> don't wait for DOMContentLoaded if it's already fired

- lib/contracts/code_generator.js
- lib/index.js
- lib/pipeline/pipeline.js
Since PWD doesn't exist on Windows, the paths to build were not correct. 
I fixed by overiding `chdir` so that when `process.env.pwd` doesn't exist, it sets it to CWD. That way, the first time `chdir` is called, PWD is set to the real current directory.
After fixing that, another issue appeared where the paths created by `path.join` used backslashes and where imported `web3\1.0.0-beta.27` failed because node thought that `\1` was an octal.
Finally, while looking at the code to find the original bug, I saw that we re-create the import list with every loop of files, so I moved it up.
I think everything works. Sadly, my PC currently sucks so I can't run a VM with Linux to check if I didn't break the Linux build. Could someone please check that out.
> Fix Windows Build due to PWD not existing

- lib/modules/ipfs/embarkjs.js
There was a bug in Windows (or my version of IPFS), where the result of `ipfsConnection.object.get` was something like this: test
Fixed by using `ipfsConnection.get` instead.
Please test on Linux or OsX to confirm it still works. Thanks.
> Fix weird characters in IPFS get by using ipfsConnection.get

- lib/modules/solidity/index.js
- test/code_generator.js
- test/compiler.js
Tests were failing because of Windows CRLF. Fixed by replacing `\r\n` by `\n`
> Fix tests breaking because of line-endings

- README.md
- lib/contracts/compiler.js
- lib/contracts/deploy.js
- lib/core/engine.js
- lib/modules/solidity/index.js
- lib/modules/vyper/index.js
Can now compile and deploy contracts in Vyper. Need to have Vyper installed.
Do we want tests in Test_app for that, @iurimatias ? It wouldn't work for Windows though and we would need to install Vyper on the test machines, so it might be complicated.
> Add Vyper contract support

- lib/cmd.js
- lib/index.js
- lib/modules/ipfs/upload.js
- lib/modules/swarm/upload.js
- test_apps/test_app/app/js/test.js
- embark upload now builds and deploys contracts before uploading to the specified platform.
- embark upload now has an option for --logFile so that it can be passed in to build.
- Swarm.deploy and IPFS.deploy functions now return a Promise for better bubbling of errors and messages (@iurimatias - will this cause any conflicts with plugin dev? Possibly might require the embark.registerUploadCommand to pass in a callback that returns a Promise?)
- Fixes issues with the test_app test.js not working properly.
- Removed duplicated code to build and deploy contracts and replaced with a call to the build function. 
- Updated upload functions to use async `exec` and removed returns from the callbacks.
> Bug fix/build before upload fixed

- lib/versions/library_manager.js
When you put by accident a space in your version (ex: `"solc": "0.4.17  ",`), it still created the directory with that space, making it impossible to change, remove or move it (at least on Windows).
Fixed it and put a warning for users to know they made that mistake.
> Fix versions with spaces and add warning

- lib/cmd.js
- lib/core/engine.js
- lib/core/logger.js
- lib/index.js
- lib/modules/ipfs/upload.js
- lib/modules/swarm/upload.js
* Add loglevel and logfile switch to `embark build`
* Support existing `loglevel` and `logfile` switch for `embark run/upload`
* make casing consistent for `loglevel` and `logfile`
* remove passing engine to `build()` and instead pass needed objects in options.
* prevent duplicate plugin initiation (above point)
* allow `Events` object to be passed to `Engine` constructor and `init()`
* prevent echo of upload commands to allow interception and control via logging
>  Support setting log level as an argument

- lib/constants.json
- lib/core/engine.js
- lib/core/plugin.js
- lib/core/plugins.js
- lib/index.js
Adds 3 contexts (others can be added):
- blockchain
- simulator
- any
When we connect to the node, we check which of the context we are in. Plugins that have a specific environment condition won't load until the context changes to the one needed.
Designed to be completely backwards compatible, meaning that plugins not specifying a context will default to `any`. To tell embark that a plugin only works with the blockchain, just need to add the field  `"context": "blockchain"` in embark.json.
> Add context to limit plugins that should not run in the simulator

- lib/constants.json
- lib/core/config.js
- lib/core/engine.js
- lib/core/plugin.js
- lib/core/plugins.js
- lib/index.js
- Enables multiple contexts at once (eg: `embark run` is ['run', 'build']
- Enables plugins to use the function `hasContext(context)` to test if the current running context contains one specific context.
> Support multiple contexts at once

- package-lock.json
The issue was the npm dependency graph was causing the web3 dependencies to be nested inside the `node_modules/web3/node_modules` folder. After removing web3 from  `package-lock.json`, and allowing npm to rebuild the graph with `npm install`, the web3 depedencies (ie web3-bzz) were correctly installed at the same level as web3.
However, this also introduced a new dependency issue in that web3-providers-ws required and depended on the websocket package at a specific github commit and was causing the same issue with websocket being installed at `node_modules/web3-providers-ws/node_modules/websocket`. Removing the web3-providers-ws dependency on websocket and replacing with version 1.0.25 requirement brought the websocket package back to the same level as web3.
> Fix issues with missing web3 dependencies

- lib/cmds/blockchain/geth_commands.js
- lib/index.js
- templates/boilerplate/config/blockchain.json
- templates/demo/config/blockchain.json
- test/test1/config/blockchain.json
- test_apps/contracts_app/blockchain.json
- test_apps/test_app/config/blockchain.json
* 'auto' now supported for `rpcCorsDomain` and `wsOrigins` in the blockchain config.
* 'auto' set to the default value in blockchain config for test and demo apps.
> Add 'auto' setting for geth CORS and websockets origin

- lib/contracts/code_generator.js
- lib/contracts/deploy.js
- lib/core/config.js
- lib/index.js
- test_apps/test_app/extensions/embark-service/contracts/pluginSimpleStorage.sol
- test_apps/test_app/extensions/embark-service/fileInPipeline.js
- test_apps/test_app/extensions/embark-service/index.js
- test_apps/test_app/package.json
- test_apps/test_app/test/plugin_storage_spec.js
- test_apps/test_app/test/token_spec.js
I tested all the plugin APIs and saw some inconcistencies and bugs and fixed them.
I also added some tests for some of the APIs that are testable.
> Small fixes for plugin APIs

- lib/index.js
- package-lock.json
Really annoying bug to debug. It only happened in the dashboard and with a blockchain backend.
What happened is we ran a double eval on the global contract creation (so that it is available in the dashboard), but the second time, web.eth.defaultAccount is no defined because it is called from the index and not deploy (where the web3 object has been modified).
> Fix contract calls in dashboard by removing the double evaluation

- lib/pipeline/watch.js
Globs only work with forward-slashes for chokidar.watch
> Fix glob in Windows for chokidar

- js/embark.js
- lib/modules/whisper/js/embarkjs.js
- templates/demo/app/components/whisper.js
Whisper demo had a bug where it didn't render messages, because setState wasn't used. 
Also added the possibility to use a callback for listenTo instead of a fake promise.
Finally, better styled the messages.
> Fix Whisper demo

- lib/constants.json
- lib/core/engine.js
- lib/core/fs.js
- lib/pipeline/pipeline.js
- package-lock.json
Does the file processing in a separate process, which greatly increases the responsiveness of the Console. For example, it is now possible to type commands like help during the file processing.
Was able to send logs from the child process to the main. I didn't create a wrapper for it yet, but it would be possible afterwards. PR is already not so nice to review, so adding another layer of complexity would make it a nightmare.
Another step would be to process each file in a separate process. Maybe after having a wrapper, it would be easy. (Right now, the step that takes a lot of time in the webpack step).
> Write files in a different process

- lib/core/engine.js
- lib/pipeline/pipeline.js
- lib/pipeline/watch.js
- lib/pipeline/webpackProcess.js
- package-lock.json
- package.json
Partial revert of the previous PR for processes. Instead of putting all the pipeline in the process, only put the webpack run as it is the cpu extensive part.
That way, it is possible to run in multiple processes and fixes the problem of passing plugins to the process.
> Process files in multiple separate processes

- lib/core/engine.js
Cargo enables you to change multiple files while a file write is running and it will only run once after for all the other files.
Also, adds throttling for file changes, so we trigger a file change event only once for multiple files.
> Add a cargo to not run file write for each file

- lib/core/events.js
Looks like it fixes `MaxListenersExceededWarning: Possible EventEmitter memory leak detected.`, because the normal limit is 10.
> set max listeners to 50

- lib/modules/solidity/solcW.js
- lib/pipeline/pipeline.js
- lib/process/processLauncher.js
- test/processLauncher.js
- Rename `subscribeTo` to `on`
- Add `once`, which triggers only once
- Enable multiple subscriptions to the same key-value 
- So for example, if module A subs to ('result', 'success'), module B can too and they both have their respective callbacks called
- Changed solcW and pipeline to use once
> Improve Process Launcher

- lib/pipeline/pipeline.js
If dist folder did not already exist, the folder is created prior to creation of the placeholder page. Without this, the dapp files are never built.
> Fixed bug where dist folder is created before placeholder page

- lib/core/config.js
- lib/index.js
- test_apps/test_app/config/storage.json
* Adds auto cors updates to geth command when blockchain started via run command.
* Fixes issues with storage/webserver configs not enabled but still having their values put in to geth cors
* Adds fixes for not including port when port  == false
* Refactor of cors logic, and also now blockchainConfig updated in Config class so can be used by both `embark blockchain` and when blockchain started in separate process
> geth CORS updates to fix issues and add to auto blockchain process

- lib/cmds/blockchain/blockchain.js
- lib/i18n/locales/en.json
- lib/processes/blockchainProcessLauncher.js
* Updated the path depth warning to check that the dapp path length is <= 66 characters.
* Updated the blockchain process to silent:false when loglevel == trace.
* Updated the path warning so that it would appear in the console regardless of loglevel (and silent:true)
> Changed path depth warning to path length

- lib/contracts/code_generator.js
- package-lock.json
So, for more than a week, the pipeline hasn't built on file change and no one noticed until Iuri did lol.
Before, we created a new codeGenerator each file change, now we reuse the same one, but we listened to events only once. I removed the once, tell me if you think it should still be once. I tested quickly and it works.
> fix pipeline not building by removing the `once`s

- lib/core/services_monitor.js
I changed `addCheck` to accept the `initialState` a week back, but Iuri's refactor uses events now and he didn't add the new param
> fix blockchain already booted

- lib/contracts/accountParser.js
- lib/contracts/blockchain.js
- lib/contracts/deploy_manager.js
- lib/contracts/fundAccount.js
- lib/contracts/provider.js
- lib/core/plugin.js
- lib/modules/solidity/solcP.js
- lib/tests/run_tests.js
- lib/tests/test.js
- test/accountParser.js
- test_apps/test_app/test/another_storage_spec.js
Please review https://github.com/embark-framework/embark/pull/495 first please as it contains a bug fix that is used in this branch too.
Uses the config to tell which accounts to use and which balance. 
You can now specify your balance also for the normal wallet (in embark run) and you can do so using the unit name (eg: 5eth, 432432wei, 324gwei, etc.)
Currently only works with the simulator. Will make it work in a node in the next PR.
> Enables specifying accounts in simulator mode in the tests

- lib/cmd.js
- lib/index.js
- lib/tests/run_tests.js
- lib/tests/test.js
- lib/tests/test_logger.js
Set default loglevel for tests at warn. Also, actually enabled logs; before they were in comments.
> Enable loglevel for test logger and actually log

- lib/contracts/deploy_manager.js
- lib/index.js
Before `embark build` only ran the deploy and exited, now we wait for file build too (which leaves time for async afterDeploys to finish and also, well, builds)
In the case of simple apps (no files, only contracts), it will tell them that they can close with ctrl+c
> Fix afterDeploy in build and also build files

- lib/coderunner/codeRunner.js
- lib/index.js
- lib/modules/specialconfigs/index.js
Same as https://github.com/embark-framework/embark/pull/529, but with a small refactor to runCode to call back the error
> Add file build to embark build and fix afterDeploy

- lib/contracts/compiler.js
- lib/core/plugins.js
- test_apps/test_app/README.md
External plugins that use registerCompiler are loaded before the internal modules for Solidity and Vyper.
When the internal modules are loaded, they override the external plugin compiler.
This change will allow the external plugin to have preference over the internal modules for compilers.
> Allow plugins to override core compilers

- lib/modules/ipfs/index.js
- lib/modules/storage/index.js
Fixed issue with IPFS not starting when swarm failed.
Added logging when starting of all storage providers has completed, and whether or not there were errors during starting of one of the providers.
Added parallel processing for starting dappConnection storage providers.
Removed irrelevant IPFS error from trace logs when IPFS not available.
> Storage provider initialisation fixes and improvements.

- lib/contracts/blockchain.js
Fixes the issue of defaultAccount not being set in the dashboard and in onDeploy.
Was caused when initiating the blockchain node during node, because we need to reset the web3 object when creating the node, so I register the new object at the end of init
> Register web3 object after init

- lib/contracts/blockchain.js
- lib/tests/test.js
- lib/utils/utils.js
Fix the case where you try to test specifying a non available node or the node is off.
Moved the pingEndpoint function to utils so that I could use it in tests too.
> Fix hanging tests when using a wrong node

- lib/index.js
Did a bit of linting, but really, it's one line. Needed to start the web3 service, because now deployContract uses the getGasPrice event that's available in the web3 service
> Fix hanging embark graph by starting web3 service

- lib/core/logger.js
- lib/core/plugin.js
- lib/dashboard/monitor.js
- test_apps/test_app/extensions/embark-service/index.js
Enables multiple arguments in the logger.
Removes the old plugin interception as it ended up catching all the logs of all the plugins and used only the name of the last plugin.
Now, plugins can log with multiple arguments and when using embark.logger.x() it will add the plugin's name (the real plugin) to the log.
> Fix log interception and enable multi-argument logging #2

- lib/contracts/contract_deployer.js
- lib/contracts/contracts.js
- lib/contracts/deploy_manager.js
- lib/tests/test.js
First step towards parallel contract deploy. 
Adds an entry in the contract object saying the number of dependencies it has, that number is the sum of the number of contract it directly depends on plus the dependency count of its parents. It finds it recursively. It watches for circular dependencies and sets the count at Infinity if so.
Right now, the deploy is just too damn fast, so it doesn't change anything in terms of speed (at least in dev), but we are gonna go back to like before and it will hopefully increase the speed.
> Async contract deploy (parallel deploy prequel)

- lib/core/config.js
- lib/modules/ens/contracts/FIFSRegistrar.sol
- lib/modules/ens/index.js
- test_apps/test_app/config/namesystem.json
Deploys the registrar for ENS which is necessary to begin registration of contracts. Starting with a FIFS Registrar, might go to various types of Registrars in the future. Root name is used to denote the root node of the name system.
> Registrar deployment

- lib/index.js
It was simply too fast with the solc plugin and the blockchain node was not yet ready before solc would try to compile and deploy, and would error out while estimating gas costs.
> Fix for embark upload failing when embark-solc plugin is installed.

- lib/index.js
`embark build --contracts` was writing to the pipeline with or without the `--contracts` flag. Needed to add a condition to check if the flag was present before loading the pipeline. Additionally, finish the build process a tad earlier depending on whether or not the `--contracts` flag was set.
> Fix for `embark build --contracts` writing into the pipeline

- lib/cmds/blockchain/blockchain.js
- lib/cmds/blockchain/geth_commands.js
- templates/boilerplate/config/blockchain.js
- templates/demo/config/blockchain.js
- test/blockchain.js
Add fix by @hhakala to templates and also enable using `syncMode` and `syncmode`  as geth's option is called `syncmode`.
Having to accept both a my bad as I originally wrote the param in the blockchain.json as syncMode and it got shipped in 3.1, where it should have been syncmode to be the same as geth,
> Bug fix/sync modepatch

- lib/core/proxy.js
Proxy error message "Error forwarding requests to blockchain/simulator [Object(object)]" was showing in console. Have replace [Object(object)] with  `error.message`
> Fix proxy error message "Error forwarding requests to blockchain/simulator [Object(object)]"

- lib/contracts/code_generator.js
There was a condition checking if blockchain config was disabled and if so, do not generate any provider code, which is where the `__mainContext` was being defined. This was changed to generate the `__mainContext` code first, then if blockchain is disabled, return the already generated code.
> Fixed __mainContext error

- lib/pipeline/pipeline.js
Doesn't fix errors to the pipeline, but at least tells the user that the pipeline exited, so there will be no more hangs.
> log error when pipeline dies

- lib/contracts/blockchain.js
This bug only happened when using a WebSocket provider AND having the blockchain node in the same terminal (eg: run starting the node). 
I have no idea why, but the receipt event just sometimes doesn't get triggered, nor did the `then` trigger.
As a quick fix/patch, I added a backup interval that will check if the receipt is there.
> Fix deployment getting stuck

- lib/cmds/simulator.js
- package.json
I realized that we can avoid `shelljs.which` entirely by invoking `<embark>/node_modules/.bin/ganache-cli` directly.  An upside is that we don't need an extra `"bin"` entry, so no more `ganache-cli-embark` in the global PATH.
So, it's a better approach, and a step closer toward the optimal solution suggested by @jrainville, i.e. using `ganache-core` as a library and spinning up our own server from `require('ganache-core').server`.
> invoke embark's local ganache-cli directly

- lib/core/config.js
- lib/core/engine.js
- lib/index.js
These changes result in cli options `--host` and `--port` being picked up by the service starter and the rutime config builder, and in turn the code that adjusts the CORS settings.
> propagate `embark run` cli webserver options to config and service

- lib/contracts/code_generator.js
- lib/contracts/code_templates/do-when-loaded.js.ejs
A dev might run into the need of inquirying which configuration is being used during runtime, in case they want to add environment specific behaviors.
Show a dialog indicating that a user is connected to the mainnet (with metamask), and using the development settings. 
```
const netId = await web3.eth.net.getId();
if(netId === 1 && EmbarkJS.environment !== 'livenet'){
// Notify user that configuration does not match the network used
alert("Wrong network / configuration used");
}
```
Do something (like displaying additional developer options) only when running on development
```
const netId = await web3.eth.net.getId();
if(netId == 1337 && EmbarkJS.environment === 'development'){
// ...
}
```
> Add environment to EmbarkJS

- lib/modules/profiler/index.js
In case the contract don't exist or the profile
command don't have argument, embark don't crash
and return an error
> Fix profile command

- lib/modules/swarm/index.js
See IPFS:
```
registerUploadCommand() {
const self = this;
this.embark.registerUploadCommand('ipfs', (cb) => {
let upload_ipfs = new UploadIPFS({
buildDir: self.buildDir || 'dist/',
storageConfig: self.storageConfig,
configIpfsBin: self.storageConfig.ipfs_bin || "ipfs"
});
upload_ipfs.deploy(cb);
});
}
```
> Fix scope of the callback

- lib/cmds/blockchain/blockchain.js
- lib/cmds/simulator.js
- lib/core/config.js
- lib/core/proxy.js
- lib/modules/webserver/index.js
- lib/modules/webserver/server.js
- lib/modules/whisper/index.js
- lib/processes/storageProcesses/storageProcessesLauncher.js
- lib/utils/host.js
- lib/utils/utils.js
- test/blockchain.js
You can give this PR a spin by running the following in a Bash shell:
```shell
td=~/temp/$(basename $(mktemp -d)) \
&& mkdir -p $td \
&& cd $td \
&& export EMBARK_DOCKER_EXTRA_RUN_OPTS='--rm' \
&& export EMBARK_DOCKER_IMAGE=statusim/embark \
&& export EMBARK_DOCKER_TAG=revised \
&& export EMBARK_DOCKERFILE='https://github.com/embark-framework/embark-docker.git#features/env-flexibility' \
&& export EMBARK_VERSION='embark-framework/embark#features/defaultHost' \
&& export RUNNER='https://raw.githubusercontent.com/embark-framework/embark-docker/features/env-flexibility/run.sh' \
&& docker build \
--build-arg EMBARK_VERSION=$EMBARK_VERSION  \
-t $EMBARK_DOCKER_IMAGE:$EMBARK_DOCKER_TAG \
$EMBARK_DOCKERFILE \
&& source <(curl $RUNNER) \
&& run_embark demo \
&& cd embark_demo \
&& run_embark
``` …
> docker awareness

- package.json
Yesterday, a new version of ethereumjs-wallet was published (`0.6.1`), and embark will pick it up on a fresh install owing to our use of a caret range: `"^0.6.0"`.
Normally that wouldn't be a problem, but `0.6.1` has a breaking change, probably not intended by its authors: https://github.com/ethereumjs/ethereumjs-wallet/issues/64.
Until they fix the problem or clarify the breaking change was intentional, we can specify an exact version in embark's pkg.json.
> spec exact version of ethereumjs-wallet

- lib/pipeline/webpackProcess.js
- package.json
- test_apps/test_app/package.json
With webpack 4 and babel 7, as discovered through trial and error, it's important to:
1. configure webpack so that modules organized under `.embark/versions` take precedence over embark's own `node_modules`.
2. configure babel to exclude modules in `.embark/versions` from the sources it will transpile.
3. specify the webpack aliases plugin for babel ahead of other babel plugins.
With regard to (1), especially, I'm somewhat puzzled how things were managing to work under webpack 3 and babel 6. It's possible we were getting lucky owing to a subtle interaction between webpack, babel and module lookup that just happened to work out favorably.
The test_app's babel-related devdep has also been bumped to the babel 7 equivalent, and I changed embark's babel deps to specify caret ranges. Also …
> .embark/versions modules

- lib/pipeline/webpackProcess.js
- package.json
- test_apps/test_app/package.json
This effectively resurrects #656, but with an additional commit adding Windows compatibility.
I have tested that dapps making use of plugins (e.g. `test_apps/test_app`, which specs ipfs-api 17.2.7, the default being 17.2.4) build correctly and that geth, ipfs, etc. are working correctly in the browser.
> .embark/versions modules — round 2

- lib/cmds/blockchain/blockchain.js
- lib/cmds/blockchain/dev_funds.js
- test/devFunds.js
- test/helpers/fakeIpcProvider.js
- test/test1/password
Added unit tests for dev_funds. These are weak tests as the `FakeIpcProvider` (used to mock `web3` responses) does not provide enough support for keeping track of accounts and balances and instead we are injecting the provider responses in the tests, which kind of defeats the purposes of the tests. Instead, the `FakeIpcProvider` should be a little smarter and do more of what a real node would do.
The `FakeIpcProvider` has a lot of room for improvement. If we spend the time improving it, we could probably leverage it's functionality to further test Embark components that rely on `web3`.
> Patch:  Basic unit tests complete for dev_funds

- lib/cmds/blockchain/blockchain.js
- lib/cmds/simulator.js
- lib/core/config.js
- lib/core/proxy.js
- lib/modules/webserver/index.js
- lib/modules/webserver/server.js
- lib/modules/whisper/index.js
- lib/processes/storageProcesses/storageProcessesLauncher.js
- lib/utils/host.js
- lib/utils/utils.js
- test/blockchain.js
Commits cherry-picked from develop to give `3_1_0` "docker awareness".
Tested with:
``` shell
td=~/temp/$(basename $(mktemp -d)) \
&& mkdir -p $td \
&& cd $td \
&& export EMBARK_DOCKER_IMAGE=statusim/embark \
&& export EMBARK_DOCKER_TAG=3_1_0_defaultHost \
&& export EMBARK_DOCKERFILE='https://github.com/embark-framework/embark-docker.git' \
&& export EMBARK_VERSION='embark-framework/embark#3_1_0_defaultHost' \
&& export RUNNER='https://raw.githubusercontent.com/embark-framework/embark-docker/master/run.sh' \
&& docker build \
--build-arg EMBARK_VERSION=$EMBARK_VERSION  \
-t $EMBARK_DOCKER_IMAGE:$EMBARK_DOCKER_TAG \
$EMBARK_DOCKERFILE \
&& source <(curl $RUNNER) \
&& run_embark demo \
&& cd embark_demo \
&& run_embark
```
It works! When the container is running and once the embark …
> docker awareness for 3_1_0

- lib/modules/deployment/contract_deployer.js
Enabling contract:deploy:beforeDeploy plugins to access deploymentAccount.
Previously known as #673 .
<If relevant, write a list of questions that you would like to discuss related to the changes that you have made.>
<use @mentions for quick questions, specific feedback, and progress updates.>
> Enabling contract:deploy:beforeDeploy plugins to access deploymentAccount

- lib/cmds/simulator.js
- lib/modules/deployment/contract_deployer.js
- lib/modules/ens/index.js
- lib/utils/accountParser.js
This PR allows user to configure option "simulatorAccounts" in the blockchain.json in the following format:
```
"someEnvironment": {
// skipped //
"simulatorMnemonic": "something something something something something something ",
"simulatorBlocktime": 35,
"simulatorAccounts": [
{
"privateKey":  "0xaaaaa",
"hexBalance":    "0x56BC75E2D60000000"
},
{
"privateKey": "0xbbbbb"
// default of 10 ether will be applied if hexBalance is invalid or missing
}
```
Then it would be used when running "embark simulator someEnvironment" .
> Applying simulatorAccounts configuration for "embark simulator" command

- lib/contracts/contracts.js
- lib/tests/test.js
TLDR: removes direct references to contractManager, so we can move it to a module
> remove contracts manager dependency from tests

- lib/core/ipc.js
- lib/tests/test.js
- Make sure the folder .embark exists otherwise the first time there is a
run, the connection abort silently
- Fix the number of args in the callback function
> Fix connection to IPC

- lib/contracts/contracts.js
- lib/modules/blockchain_connector/index.js
- lib/modules/deployment/contract_deployer.js
- lib/modules/ens/index.js
- lib/modules/specialconfigs/index.js
ENS contracts created a lot of logs that are annoying to a user since he didn't really add those contracts himself. 
Added `silent: true` to the contract config. When set, it hides the logs for that contract and doesn't show it in the dashboard.
When loglevel is trace, it still shows the logs.
Would it be better as `hidden` or `silent`? We usually use `silent` and it makes sense for logs, but since it's also used for the dashboard maybe `hidden` is better?
I didn't hide the Proxy logs for the ENS contracts / silent contracts. Would it be better? I feel that when EmbarkJS calls register, it's very nice to have the proxy displaying it. But for the initial register, maybe less helpful.
> Hide ENS logs etc

- lib/modules/contracts_manager/index.js
- lib/modules/deployment/index.js
Use async.auto to deploy the contract in a parallel manner. 
Async.auto makes sure the dependencies are processed first.
Also remove dependencyCount as it is not needed anymore.
Stats: https://docs.google.com/spreadsheets/d/1cjtY6yBmi1Qu8ASdBn3SA4-jsWpg2GlL6aiu5J3FeY0/edit?usp=sharing
> More Parallel deploy

- .npmignore
`npm pack` was by default ignoring the `.gitignore` files within the template directories. With this change, it doesn't ignore them.
Compare the results of:
```
npm pack embark-framework/embark#3.1.7
```
```
npm pack embark-framework/embark#develop
```
^ both of those are missing the `.gitignore` files
```
npm pack embark-framework/embark#bug_fix/templates-gitignore
```
It was easy to miss this since during development we're often working with embark installed from a clone of the github repo vs. a tarball packed by `npm`.
Post approval and merge, I will cherry pick this commit into a branch off `3_1_0`, then submit a PR for merging into `3_1_0`.
> npm should not ignore templates' .gitignore files

- lib/modules/blockchain_process/simulator.js
- package-lock.json
- package.json
I accidentally discovered a corner-case that breaks our method of [ganache-cli resolution](https://github.com/embark-framework/embark/blob/develop/lib/modules/blockchain_process/simulator.js#L17) on embark's develop branch. Embark's `3.1.x` series is immune as it's still using the [`shelljs.which` approach](https://github.com/embark-framework/embark/blob/3_1_0/lib/cmds/simulator.js#L17).
It happens that if ganache-cli and embark are installed globally ***at the same time***:
```
npm install -g embark-framework/embark#develop ganache-cli@6.1.0
```
And if the ganache-cli being installed satisfies embark's dependency (version/range match), then during  install npm will dedupe the dependency such that ganache-cli doesn't end up in embark's `node_modules`. Our resolution, relative to embark's …
> fix ganache-cli resolution

- lib/pipeline/webpackProcess.js
- package-lock.json
- package.json
Applies changes complementary to those of https://github.com/embark-framework/EmbarkJS/pull/10 and bumps `embarkjs` to (just released) `0.3.2`.
> fixes re: babel 7 release candidate 1

- lib/contracts/provider.js
Caused all the fundings to have the same nonce. With the limit, only funds one account at a time.
> set async limit funding

- lib/modules/blockchain_process/index.js
this line was causing embark to crash if the blockchain process died. the variable doesn't exist and is probably a byproduct of a merge conflict.
> remove line causing crash

- lib/core/engine.js
**TL;DR**
When a file is removed, the config needs to be reloaded, otherwise the pipeline try to compile a file that doesn't exist and crash
> Reload config when a file is added/removed

- lib/modules/ens/contracts/Resolver.sol
- lib/modules/ens/embarkjs.js
- lib/modules/ens/index.js
- lib/modules/ens/register.js
Since privatenet is not dev, we can't pre-register and also, we have nothing to lookup like with a testnet or mainnet, so there is no need to enable ENS in privatenet. I put a warning in case the user had put ENS enabled and is in privatenet.
Also, fixed some conditions that were broken.
> Enable ENS in privatenet

- package-lock.json
- package.json
Currently embark is using ganache-cli 6.1.0 (ganache-core 2.1.0), which has a bug when it ignores --blockTime option. It was fixed in ganache-core 2.2.0 and 2.1.1 in this commit - trufflesuite/ganache-core@4de0b71 .
ganache-cli versions 6.1.2-6.1.4 are broken in another way - they interpret CLI flag --host as --help , so ganache-cli -h localhost just shows help and doesn't start. It was fixed in 6.1.5 .
I updated my local latest embark to use ganache-cli@6.1.6 and got no issues using it.
for quick questions, specific feedback, and progress updates.>
> Updated ganache-cli from broken 6.1.0 to 6.1.6 in order to fix simulatorBlocktime blockchain option.

- lib/core/processes/processLauncher.js
- lib/core/processes/processWrapper.js
**TL;DR**
Catch error in process and display them.
before:
```
anthony@anthony:~/code/embark-framework/embark/templates/demo$ ../../bin/embark run --nodashboard
Debugger listening on ws://127.0.0.1:36407/6e7f93ab-38d0-49fa-83ff-9a22cd107997
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
pid 1786 listening on /home/anthony/code/embark-framework/embark/templates/demo/.embark/embark.ipc
========================
Welcome to Embark 3.2.0-develop
========================
webserver available at http://localhost:8000
ready to watch file changes
Debugger listening on ws://127.0.0.1:38549/76a529f3-15e0-46a1-b3ee-a42d64d33b47
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect... …
```
> Do not hang if process crash

- lib/modules/whisper/index.js
The whisper config was being stringified twice, but that should only be done once.
> whisper config should be stringified only once

- lib/constants.json
**TL;DR**
`embark run/console livenet` was failing with:
```
TypeError: Cannot read property 'toString' of undefined
at web3.eth.net.getId.then.id (/home/anthony/code/embark-framework/embark/lib/modules/blockchain_connector/index.js:85:45)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:118:7)
```
this is:
```
if (!networkId && constants.blockchain.networkIds[self.blockchainConfig.networkType]) {
networkId = constants.blockchain.networkIds[self.blockchainConfig.networkType];
}
```
The networkType is `livenet`, not `mainnet`
> Mainnet is livenet

- cmd/cmd.js
- lib/core/engine.js
- lib/modules/blockchain_process/index.js
- lib/modules/solidity/solcW.js
- lib/pipeline/pipeline.js
- lib/tests/run_tests.js
- lib/tests/test.js
- lib/tests/test_logger.js
- lib/utils/utils.js
**TL;DR**
Enables `embark test --node <node>`
Where node can be a url (eg: ws://localhost:8546) or "embark". If "embark", use IPC to check the node at which Embark is connected
Connecting  to a WS node creates some problem, because some of our tests just don't work well on WS for some reason. This is not related to this PR. The problem is present on develop too. I created an issue in Pivotal to track it.
> Add --node option for tests

- cmd/dashboard/repl.js
- lib/core/modules/coderunner/codeRunner.js
- lib/core/modules/coderunner/runCode.js
- test_apps/test_app/test/ens_spec.js
**TL;DR**
Name a contract Buffer cause a failure.
The error is cause because by default Buffer is part of the global namespace. By doing a contract Buffer the default one is overridden.
Some of the library have usage of the Buffer.
To avoid any conflict, the code runner do not touch the global namespace, it uses a vm
(https://nodejs.org/api/vm.html)
The context is also set on the repl such that auto completion still works.
> Isolate the code runner

- cmd/cmd.js
- cmd/cmd_controller.js
- lib/modules/ipfs/upload.js
- lib/modules/swarm/upload.js
- lib/pipeline/webpack.config.js
`embark upload` needs to support a `--pipeline` option, with default value of `production`.
URLs reported after upload for the ipfs and swarm gateways should be `https`.
Webpack shouldn't produce `.gz` files in `buildDir` by default, since that doesn't provide any benefit at present — they're just extra things that get uploaded.
> pipeline option/default for upload command

- lib/core/modules/coderunner/codeRunner.js
- test_apps/test_app/test/simple_storage_spec.js
Bug was caused because transactions sometime hang on websocket connections and with the `await in console` task, we added a condition, if the code eval returns a Promise, wait for it to resolve before call backing. 
However, this was intended to be used with the console, not the onDeploys and other transactions.
So for those, we let the normal behavior happen. But for function calls like `await web3.eth.getAccounts()`, we intercept and display a nice result.
You can still use `await` to do `await SimpleStorage.methods.set(200).send()` in the console
> Fix hang by not intercepting web3 transactions

- lib/modules/profiler/gasEstimator.js
**TL;DR**
profile never crash, even when gasEstimate is not successfull due to specific address required.
(adding estimate gas in the ui will allow us to estimage those function)
@emizzle
> profile always return

- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
When doing a clean install on develop this afternoon (`rm -rf node_modules && npm i .`), I found that changes were introduced to `package-lock.json`. I've created a [gist from the diff](https://gist.github.com/michaelsbradleyjr/8afdf78e537e03e4ed6bab31b53e6be0).
When running `npm ls --depth=0` there are dependencies reported missing:
```
npm ERR! invalid: webcrypto-shim@0.1.1 /Users/michael/temp/nozzle/embark/node_modules/libp2p-crypto/node_modules/webcrypto-shim
npm ERR! invalid: websocket@1.0.26 /Users/michael/temp/nozzle/embark/node_modules/web3-providers-ws/node_modules/websocket
npm ERR! missing: typedarray-to-buffer@^3.1.2, required by websocket@1.0.26
npm ERR! missing: yaeti@^0.0.6, required by websocket@1.0.26
npm ERR! extraneous: debug@2.6.9 …
```
> web3@1.0.0-beta.35

- lib/utils/template_generator.js
- test/template.js
This change will also:
* upgrade calls from HTTP to HTTPS
* update / add some tests
See: #765
With these changes I wanted to make the following referenecs work for generating a project from a template:
* git@github.com/status-im/dappcon-workshop-dapp#start-here
* git@github.com/status-im/dappcon-workshop-dapp
* http://www.github.com/status-im/dappcon-workshop-dapp
* https://www.github.com/status-im/dappcon-workshop-dapp
* github.com/status-im/dappcon-workshop-dapp#start-here
* http(s)://github.com/status-im/dappcon-workshop-dapp/tree/start-here
* embark-framework/embark
The relevant changes are inside template_generator.js, sadly I couldn't re-use the branch detection of the contract download since it seems that this here would need some special expections from the rule.
Since I am not …
> Extend template_generator to support git urls and branches

- lib/core/processes/processWrapper.js
- lib/modules/solidity/solcP.js
**TL;DR**
Do not let solc process die because the process is compiling.
Debug:
```
!!!!!!!!!!!!!!!! Compiling
############################################
Checking Parent /home/anthony/code/embark-framework/embark/lib/modules/ipfs/process.js
ping /home/anthony/code/embark-framework/embark/lib/modules/ipfs/process.js
/home/anthony/code/embark-framework/embark/lib/modules/ipfs/process.js pong trueconnected: true
End Checking Parent /home/anthony/code/embark-framework/embark/lib/modules/ipfs/process.js
############################################
############################################
Checking Parent /home/anthony/code/embark-framework/embark/lib/modules/blockchain_process/blockchainProcess.js
ping /home/anthony/code/embark-framework/embark/lib/modules/blockchain_process/blockchainProce …
```
> Avoid Solc to die because of compilation

- templates/boilerplate/config/contracts.js
- templates/demo/config/contracts.js
- templates/simple/contracts.js
**TL;DR**
On development, we try to connect first to ws then http and finally WEB3 to avoid having to wait 20s
https://github.com/embark-framework/EmbarkJS/pull/19
> Ready for EIP 1102

- lib/modules/blockchain_process/simulator.js
- lib/modules/code_generator/index.js
`getWeb3Location` was hard-wiring the web3 location to always be in `node_modules` within `fs.embarkPath()`. But if embark is installed locally, e.g. in dapp-bin, web3 may be a sibling dependency of embark, owing to how npm lifts non-conflicting transitive dependencies to the top-level `node_modules`. For example, in dapp-bin the web3 pkg is found in `dapp-bin/node_modules/web3` after running `npm install`.
This PR changes the lookup to use `require.resolve()`.
~~An important thing to consider is that with this change, if a dapp has installed web3 as a dev/dep, that web3 will always be resolved instead of embark's own web3.~~
> getWeb3Location should use require.resolve()

- templates/boilerplate/config/blockchain.js
- templates/demo/config/blockchain.js
**TL;DR**
Added documentation for the dev_funds work that made it's way in to 3.1.x and now 3.2 in to the config files generated for the demo and the simple apps.
> Add `dev_funds` doco to templates

- lib/tests/test.js
**TL;DR**
Since the connection is made when possible in `engine.init()` which is called before. There is no need to call connect again.
Also calling connect again makes the process totally stop waiting for something.
> Avoid multiple connect to IPC

- lib/utils/template_generator.js
- lib/utils/utils.js
If download fails for a template specified with `embark new --template [url]`, an error should be reported and the process should exit.
> template download error

- cmd/cmd.js
If `embark eject-webpack` is run outside of a DApp, it should print an error and exit.
> eject-webpack cmd should report error and exit if run outside DApp

- lib/modules/deployment/contract_deployer.js
- lib/modules/deployment/index.js
**TL;DR**
When specifying `$accounts[x]` where `x` is a non-existent index, the error shown was unclear. Now it shows the error that occurred.
> Show an error message on account parameters

- test_apps/test_app/test/simple_storage_deploy_spec.js
**TL;DR**
For Simple Storage:
The issues is the problem with ws, if I switch the contract deployment to http, it works fine.
For ENS:
once again the problem is ws, the promise is never resolve so the code runner wait for it indefinitely
At the same time I feel that the ens test is useless because it actually test that on deploy is working
and I don't think it is the intent
Maybe what we should do is: display a warning when deploying contract with ws and change our test to use http.
> Fix embark test using node option

- lib/modules/blockchain_connector/provider.js
- lib/tests/test.js
This PR adds code coverage to pure functions.
It does this by patching the simulator provider and, when getting a pure call, forcing a transaction through first, waiting for it to be mined, and only then will it send the call.
Because pure calls should be idempotent, no side effects are expected.
Co-Authored with @iurimatias and @jrainville
> Add call coverage to pure functions

- lib/modules/deployment/index.js
Originally meant to fix: "if there is an error deploying contracts, status stays pending"
But ended up changing the behavior a bit. Before, as soon as one contract deploy failed, it would stop everything. That's why they stayed "pending". 
Now, every contract deploy will have its chance, but it will still stop before the pipeline if there is an error.
> Don't stop everything on contract deploy fail

- cmd/dashboard/monitor.js
- cmd/dashboard/repl.js
- lib/modules/plugin_cmd/index.js
Now possible to do `plugin install fortune` and `plugin install embark-fortune`
I also restructured and linted a bit
Finally, fixed a simili-bug where the console would print `undefined` if the command had no result. Now, it print an empty sting.
> Prepend "embark-" to plugin names and little fixes

- lib/core/processes/processWrapper.js
**TL;DR**
Make sure webpackProcess.js die when parent process die by playing ping pong
Fix the merge of default options with options pass in parameters:
> Better manage default options

- cmd/cmd.js
- lib/tests/test.js
**TL;DR**
Add better help info for `embark test —node`.
Fixed issue with `embark test —node vm` where the `vm` was attempted to be parsed as a URL instead of running the simulator.
> `embark test —node` help, plus fix for vm option

- lib/core/file.js
- test/config.js
The flag to say that the file had downloaded it's dependencies was set too soon, because we recursively check all dependencies and if a dep has an http import, we didn't download it.
Also, weird `toString` was needed, but only when a contract import another http contract.
> Fix contracts with http import inceptions

- cmd/cmd.js
Previously, if the option value for `embark test --node [value]` was not valid, it would be silently replaced with `'vm'` and the command would continue to run using the simulator.
However, that behavior can mask simple typos in node URLs such that the user might think a successful test run had been made against his (bad) URL but actually wasn't
Instead, if the option value isn't valid, we should report an error and exit.
> report error and exit if --node option value is not valid

- lib/core/modules/coderunner/runCode.js
**TL;DR**
The providerUrl being provided to the console VM was looking for a WebsocketProvider-specific property which did not exist on the HttpProvider.
Type checking was added to provide the necessary type-dependent property.
> Fix for embark run crashing after console connects to it

- lib/modules/blockchain_process/blockchain.js
- lib/modules/blockchain_process/proxy.js
- test/blockchain.js
**TL;DR**
There is no difference in output except that:
```
[Error forwarding requests to blockchain/simulator,connect ECONNREFUSED 127.0.0.1:8556]
```
should not appear anymore
The proxy was started before geth client and was causing this error.
To solve it, move the proxy start after the gets command.
Let me know if you still experimence this error. I haven't since this change
> Delay the start of the proxy

- lib/modules/webserver/server.js
- package-lock.json
- package.json
**TL;DR**
serve `/coverage` to `coverage/__root__/index.html`
In order to do so I had to change the server to express, this is the only way I found to have multiple root for serving static assets, happy to change if anyone has a better solution
> Add coverage to webserver

- cmd/cmd.js
Embark's template downloader only supports GitHub repos, so I changed the output of `embark new --help` to mention GitHub.
> clarify 'new' help output

- lib/modules/blockchain_process/geth_commands.js
**TL;DR**
When `isDev` is false, and `mineWhenNeeded` is true, embark attempts to create a new account using `geth account new`, and uses the password file specified in `blockchain/config > accounts > password`. This warning informs the user that the create account command may fail if the password is missing.
This is the second part of the `mineWhenNeeded` issue where the user gets "stuck" on `geth account new` when running `embark blockchain`.
Should we offer an example of what to include in the config, ie `"password": "config/privatenet/password"`?
> Geth creates new account - add password warning

- cmd/cmd.js
- cmd/cmd_controller.js
- lib/core/config.js
- lib/core/engine.js
- lib/modules/webserver/index.js
- lib/modules/webserver/server.js
- templates/boilerplate/config/webserver.js
- templates/demo/config/webserver.js
Automatic opening of the default web browser (when embark's development webserver starts) can be disabled via `--nobrowser` cli option or `openBrowser: false` in a DApp's `webserver.js` config file.
Some aspects of how the webserver's config and cli options are handled have been modified to ensure that not specifying a cli option doesn't effectively override what's in the DApp's config. Merging the cli and config options is now entirely the responsibility of `core/config`; previously, it was done by both the webserver module and core/config, which is redundant and could be confusing.
> cli and config options for browser auto-open

- cmd/cmd.js
Tiny change to improve wording in cli help output re: `--gasDetails`:
"deploy" -> "deployment".
See also https://github.com/embark-framework/embark-site/pull/60.
> deploy -> deployment

- cmd/cmd.js
When `embark test --coverage --node [opt]` specifies `embark` or a custom endpoint for the node, coverage works inconsistently: no report (`.embark/coverage.json`) is written most of the time. This PR makes embark report an error and exit if the node is not `vm`. We can remove this behavior once coverage works consistently for the other node types.
Wording of the help output for `--gasDetails` and `--node` has been revised a bit and quotes style in the error messages has been made consistent with the rest of the help output.
> --coverage requires --node be "vm"

- lib/modules/blockchain_process/blockchain.js
- lib/modules/blockchain_process/miner.js
**TL;DR**
The datadir path was not being passed to the miner, was resolving as `undefined`, and therefore, was not setting up an ipc connection correctly and no communication was happening.
The fix passes the `datadir` from the blockchain config to the miner in the constructor.
https://github.com/embark-framework/embark/pull/858, https://github.com/embark-framework/embark/pull/857
> Fix datadir for miner

- lib/tests/test.js
**TL;DR**
Display a warning when gas price won't be display
> Display warning for gas price

- lib/modules/contracts_manager/index.js
A contract that's an `instanceOf` another contract needs to reference its parent's `realRuntimeBytecode` code in order to be detected as having changed when the parent changes.
> fix for instance contracts not redploying when parent changes

- lib/modules/blockchain_process/blockchain.js
- lib/modules/blockchain_process/proxy.js
- lib/modules/blockchain_process/simulator.js
- lib/utils/utils.js
When a proxy is being created, attempt to wait for the target endpoint to be live before connecting the proxy. If it takes longer than 10 seconds, then go ahead — we'll get an error as before, and something is probably wrong in any case.
Owing to the placement of the proxy setup call for a real blockchain, there is hardly any delay before the proxy is available (a few ms, assuming nothing is wrong with the invocation of geth). For the simulator, it takes a few seconds.
> proxy should try to wait on target endpoint

- lib/modules/blockchain_process/blockchain.js
- lib/modules/blockchain_process/miner.js
**TL;DR**
The datadir path was not being passed to the miner, was resolving as `undefined`, and therefore, was not setting up an ipc connection correctly and no communication was happening.
The fix passes the `datadir` from the blockchain config to the miner in the constructor.
https://github.com/embark-framework/embark/pull/858, https://github.com/embark-framework/embark/pull/857
> Fix datadir for miner (PR for next branch)

- .travis.yml
- appveyor.yml
- npm-shrinkwrap.json
- package.json
- test_apps/contracts_app/package.json
- test_apps/coverage_app/package.json
- test_apps/test_app/package.json
(( if #887 is merged first may need a rebase, and vice versa ))
Uses the same approach as dapp-bin's `develop` branch to make embark's and its test dapps' npm-scripts more DRY, and in turn allows simplifying embark's `.travis.yml` and `appveyor.yml` configs.
> better npm scripts

- .travis.yml
Since we support the "big 3" platforms — Linux, macOS, Windows — I think it makes sense to have travis run tests on both Linux and macOS, with appveyor responsible for testing on Windows.
> configure travis to test on both Linux and macOS

- .travis.yml
- appveyor.yml
Revise `.travis.yml` and `appveyor.yml` so that tests are run on Node.js current (v10) and LTS (v8) releases.
> test node current release (10) in addition to node LTS release (8)

- lib/utils/accountParser.js
**TL;DR**
Change the way that the absolute path for `privateKeyFile` gets calculated.
| Value | Before | After |
| --- | --- | --- |
| `somedir/keyfile` | `/dapp/somedir/keyfile` | `/dapp/somedir/keyfile` |
| `/somedir/keyfile` | `/dapp/somedir/keyfile` | `/somedir/keyfile` |
> Resolve private key path instead of forcing inside dApp root

- lib/modules/ipfs/upload.js
**TL;DR**
This ensures that, regardless of the IPFS output order, we're always able to get the directory hash.
In some cases, IPFS output interpolated progress bars that interfered with fetching the directory hash. Because the previous solution fetched the penultimate line, it sometimes fetched the wrong information. This way, we ensure that we're able to pick it regardless of the order in which the output comes with.
> Fetch IPFS dir hash deterministically

- lib/utils/template_generator.js
When running `embark new --template` and specifying a github shortcut like `status-im/dappcon-workshop-dapp#branch`, if the `branch` part contained `/` then it wasn't being handled correctly. This PR fixes it so that an arbitrary number of `/` characters may appear in the branch part.
> allow for '/' in branch name when handling github shortcuts

- lib/modules/webserver/server.js
**TL;DR**
Make sure the connection is open before sending the event.
I was getting this error:
```
Ready
/Users/anthony/code/embark-framework/embark/node_modules/express-ws/node_modules/ws/lib/websocket.js:320
throw err;
^
Error: WebSocket is not open: readyState 3 (CLOSED)
at WebSocket.send (/Users/anthony/code/embark-framework/embark/node_modules/express-ws/node_modules/ws/lib/websocket.js:314:19)
at EventEmitter.self.events.on (/Users/anthony/code/embark-framework/embark/lib/modules/webserver/server.js:42:12)
at EventEmitter.emit (events.js:187:15)
at pipeline.build (/Users/anthony/code/embark-framework/embark/lib/core/engine.js:121:23)
at /Users/anthony/code/embark-framework/embark/node_modules/async/dist/async.js:473:16
at next …
```
> Fix websocket not open

- cmd/cmd.js
- lib/utils/template_generator.js
- package.json
- test/template.js
This is a follow-up to #897. The previous implementation could still get tripped up on some corner-cases with `/` characters and fail in unhelpful ways if a user supplied an unsupported URL type (vs. one that would result in 404). Some other shortcomings were identified, e.g. the "complete" and "ready" messages were being displayed too soon, and the "installing packages" message wasn't being displayed when instantiating from the boilerplate template.
I found a battle-tested and well-maintained package that parses *git host URLs*:
https://www.npmjs.com/package/hosted-git-info
`hosted-git-info` (latest version) was already a transitive dep of embark; pkg json has been revised to make it an explicit dependency, but no changes needed to be made to `npm-shrinkwrap.json`.
It's from the …
> make template downloader more robust

- lib/modules/coverage/contract_source.js
- lib/modules/coverage/contract_sources.js
**TL;DR**
This PR will only filter out contract files from the coverage report that only contain interfaces. If, for instance, a contract file contains both an interface and runnable code, it will not be filtered out.
http://cdn-static.denofgeek.com/sites/denofgeek/files/styles/insert_main_wide_image/public/4/09//narada-star-trek.jpg?itok=SOnVTvMG)
> Filter out interfaces from the coverage report

- lib/modules/storage/storageProcessesLauncher.js
CORS URL for the local ipfs' own server (default `localhost:8080`) should be added, otherwise when the DApp is loaded from that server it raises CORS exceptions.
The XHR that fails is trying to talk to `localhost:5001`, the DApp having been served from `localhost:8080`. So the CORS being added for `localhost:8080` is really for the benefit of the ipfs process handling requests on `localhost:5001`.
> add CORS URL for local ipfs' own server

- cmd/cmd_controller.js
This PR has `embark upload` start the `namingSystem` service unconditionally.  `associateToENS` still happens conditionally, though the `--ens` cli option to activate it [is disabled on embark's `next` branch](https://github.com/embark-framework/embark/blob/next/cmd/cmd.js#L303).
If the `namingSystem` service is not started, then the code gen step for including `__embarkENS.setProvider = function (config) {...}` within `.embark/embark.js` never happens, and when the DApp is served from local ipfs `localhost:8080`, ENS is broken as a result.
> upload command should unconditionally start the "namingSystem" service

- lib/modules/ens/embarkjs.js
**TL;DR**
ENS needs default account
> Warning if no default account for ens

- lib/modules/coverage/contract_source.js
- test_apps/coverage_app/contracts/branches.sol
- test_apps/coverage_app/test/branches_spec.js
**TL;DR**
Handle `if` statements without a body in the Solidity coverage report, ie.
```javascript
// this used to be supported
if(someCondition) {
doThis();
doThat();
}
// this crashed the coverage tool
if(someCondition) doTheOtherThing();
```
Fixes #909
> Support if statements without a list of statements

- lib/core/engine.js
- lib/modules/contracts_manager/index.js
The configuration for test is not passed via the engine
**TL;DR**
It seems to be a missing config, it used to check for process.env.Test but when compileOnceOnly has been introduce, it hasn't been added to the engine
> Add missing config

- cmd/cmd_controller.js
**TL;DR**
The pipeline and the contracts compiler print the error themselves.
For example doing: `err || err.message` is causing double printing
> Remove undefined printed

- cmd/cmd.js
- cmd/cmd_controller.js
- lib/modules/graph/index.js
Add optional --output argument to graph generator. The argument allows
to specify a filepath for graph output. Default filepath is ./diagram.svg
if the argument is not specified.
Refs: https://github.com/embark-framework/embark/issues/944
None
> cmd, cmd_controller, graph: Add --output option to graph.

- cmd/cmd.js
- lib/tests/run_tests.js
**TL;DR**
Do not start browser during coverage run when --nobrowser option is passed.
Refs: https://github.com/embark-framework/embark/issues/941
None
> cmd, run_tests: Add --nobrowser option for runCoverage.

- lib/modules/deployment/contract_deployer.js
We are using plugin that modifies bytecode and contract arguments based on future contract's address.
Contracts are tracked by name, constructor's bytecode and arguments.
New event "deploy:contract:arguments" added before "_determineArguments" to give plugin an opportunity to calculate dynamic arguments before DeployTracker's check, so arguments actually applied to contract in beforeDeploy will match arguments that DeployTracker checks against.
spaceship.jpg
> Make possible for deploy:contract:beforeDeploy plugin to modify arguments

- lib/modules/deployment/contract_deployer.js
Always deploy the contract regardless if already deployed
when 'track' field in the contract configuration is specified
and set to false.
In line with #938 requirements:
* If a contract has the track field set to false, that contract
will always deploy.
* If the track field is set to true, then the existing deployment
tracking mechanism will be active for that contract.
* If the field is not set, it should be assumed to true by default
Refs: https://github.com/embark-framework/embark/issues/938
Example log:
```
========================
Welcome to Embark 3.2.1
========================
loaded plugins: embark-solc
ready to watch file changes
IPFS node not found, attempting to start own node
Starting ipfs process
webserver available at …
```
> contract_deployer: Redeploy if track field is set to false.

- lib/utils/template_generator.js
- npm-shrinkwrap.json
- package.json
- test/template.js
**TL;DR**
For `embark new --template <name>`, if `<name>` is unqualified (like `typescript`), embark calculates a `<major>.<minor>` branch name from its own version number. So these would be equivalent if the embark being used is version `3.2.2`.
```
embark new --template typescript
embark new --template typescript#3.2
```
For testing purposes, I created a `3.2` branch on the typescript template (branched off the template's `develop` branch)
Qualified template names (such as git urls or shortcuts like `--template embark-framework/embark-typescript-template`) are not modified. Also, an unqualified name that specifies a commitish isn't modified, e.g. `--template typescript#develop`.
Before this PR lands in a published version of embark, we will need to make sure all of our templates have …
> smarter template downloader

- cmd/cmd_controller.js
- lib/core/engine.js
Both commands, `$ embark graph` and `$ embark build --contracts` spin up all web3 related services, including starting a blockchain node which is not necessary in those cases.
> Don't spin up blockchain node in graph and build command with --contracts option

- lib/core/config.js
- lib/modules/blockchain_process/dev_funds.js
- test/config.js
- test/devFunds.js
- test/test1/config/blockchain.json
- test/test1/config/contracts.json
**TL;DR**
Allows the use of standard Ether units in configuration files rather than being limited to just wei.
Supersedes https://github.com/embark-framework/embark/pull/910
@iurimatias @PascalPrecht @jrainville This new branch is rebased on latest develop and includes all previous changes as well as some linting fixes from the new linter in the tests.
> Accept standard Ether units and update/add tests

- cmd/cmd.js
- cmd/dashboard/command_history.js
- cmd/dashboard/repl.js
- lib/modules/console/index.js
- test/console.js
Add persistent automatically loaded history file for repl console and Embark dashboard.
Default location of the history file is stored in DEFAULT_CMD_HISTORY_PATH pointing to DAPP_PATH/.embark/cmd_history.
The history is automatically saved and loaded on startup. Repl console has added parametrized .history command that shows last ten commands by default.
Refs: https://github.com/embark-framework/embark/issues/939
> console, dashboard: Add persistent, automatically loaded commands history.

- lib/modules/blockchain_process/gethClient.js
**TL;DR**
When `mineWhenNeeded` is true (occurs in zero-config) and an account on the node exists, a password is required to be specified `config/blockchain.js > account > password` so that the existing account can be unlocked by geth (the `—unlock` cli option).
> Add message warning user a password is needed to unlock

- lib/modules/blockchain_connector/index.js
- lib/modules/storage/storageProcessesLauncher.js
- lib/modules/swarm/process.js
**TL;DR**
When there is no account/password specified for swarm, there was an error shown in the logs (asking for address/password), and the swarm process would quit.
This PR changes the behaviour so that if a swarm address/password are not specified in the config, it attempts to use the blockchain address/password specified in `config/blockchain > account`. If `config/blockchain > account > address` doesn’t exist, the first account controlled by the node is used (provided by `web3.eth.getAccounts`, along with the password from `config/blockchain > account > password`.
> Auto set swarm account to account controlled by the node

- cmd/cmd_controller.js
We've introduced a regression in https://github.com/embark-framework/embark/commit/6d75a4c6c4b993d39be91bae14baa3f1f5695f0c where running
`embark run` breaks due to webserver options not being defined.
The reason this happened is because in the mentioned commit, we're checking given
webserver options with an identity check against `null` and only set dedicated
options, if that condition is true.
E.g.:
```
if (options.runWebserver !== null) {
webServerConfig.enabled = options.runWebserver;
}
```
Unfortunately, due to one of JavaScript design flaws, this condition behaves totally
different when no identity check is done, which causes Embark to break.
Meaning that in JavaScript:
```
undefined != null // false
undefined !== null // true
```
In other words, after the mentioned commit, the …
> fix(core/cmd_controller): ensure webserver host and port aren't set to undefined

- embark-ui/src/actions/index.js
**TL;DR**
If the command return an empty result, don't break the client
> bug: empty response

- lib/modules/blockchain_process/blockchain.js
- lib/modules/blockchain_process/blockchainProcess.js
- lib/modules/blockchain_process/gethClient.js
- lib/modules/blockchain_process/parityClient.js
**TL;DR**
If geth or parity (or others, in the future) is not within a client-specific supported-version range (or that version-test could not be performed), then a warning is printed.
There is some code-repeat across the client classes, but that can be addressed in a future PR that refactors them to specialize from a base class.
> Warn re: unsupported blockchain client

- lib/modules/contracts_manager/index.js
- test_apps/test_app/test/simple_storage_spec.js
- test_apps/test_app/test/token_spec.js
Fixes the bug @tabcat had on Gitter where he had a circular dependency, but it can work, since the address is available in `onDeploy`
> enable self-referencing contracts in onDeploy

- lib/core/config.js
- lib/core/file.js
- lib/modules/solidity/index.js
- lib/modules/solidity/solcP.js
- lib/modules/solidity/solcW.js
- lib/utils/utils.js
- test/config.js
- This PR adds the function to import  `.sol` file from ipfs.
- It uses a local variable to define the URL (`http://localhost:8080/ipfs/`) for retrieve file from ipfs. I can change it without problems. I have seen that the port number (8080) is fixed in `embark.config.storageConfig` too.
- It catches an error when the `.sol` file imported has to import another external `.sol` file.
- I wanted to change less code possible with my implementation.
- I tested the code using the last version of embark via npm, modifying only `getExternalContractUrl()` inside `utils.js`. I tested it in Mac OS environment.
- I have added a `SimpleStorageWithIPFSImport.sol` for testing the import from ipfs.
> [WIP] Include .sol import from ipfs

- lib/constants.json
- lib/core/config.js
- lib/modules/blockchain_connector/provider.js
- lib/modules/blockchain_process/dev_funds.js
- lib/modules/whisper/index.js
Fixes https://github.com/embark-framework/embark/issues/1027
Was caused by a missing cors. We used to set `http://embark` as cors only for whisper, but it is needed for the proxy too.
> Fix disabling whisper crashing the proxy

- embark-ui/package-lock.json
- embark-ui/package.json
- embark-ui/src/components/FileExplorer.js
- embark-ui/src/components/TextEditor.js
- embark-ui/src/constants.js
- embark-ui/src/containers/EditorContainer.css
- embark-ui/src/containers/EditorContainer.js
- embark-ui/src/containers/TextEditorContainer.js
**TL;DR**
Can resize the editor and the aside from left and right.
In small screens, aside goes under and editor can be resized up and down too.
There is a bug in the resizable library with using `auto`. Opened a PR here: https://github.com/bokuweb/re-resizable/pull/382
What it does is, in small displays, if you activate and deactivate the aside, the editor gets stuck with the previous height, instead of going back to `auto`. It's a pretty specific condition, so if we merge now, it shouldn't affect users too much.
> Make the editor resizable

- templates/boilerplate/config/contracts.js
- templates/simple/contracts.js
- test_apps/coverage_app/config/contracts.js
- test_apps/embark_demo/config/contracts.js
Since RPC is deprecated and the cockpit requires WS to have all the features activated
> Change RPC to WS in contract configs

- CONDE_OF_CONDUCT.md
- CONTRIBUTING.md
This updates our contributing guide as the current one wasn't apparently written by us. It also takes commit message conventions into account.
In addition it updates our COC and moves into its own document as well, so GitHub can take advantage of that.
@embark-framework/core-devs please review those carefully.
> chore: update contributing guide and code of conduct

- test/contracts/contract_with_http_import.sol
- test/file.js
- test_apps/test_app/app/contracts/SimpleStorageWithHttpImport.sol
- test_apps/test_app/test/http_contract_test.js
Some test endpoints have still pointed to `develop` branch on GitHub,
which made our tests fail as we're now on `master` branch
> fix(ci): make CI happy again by updating http paths to master branch

- lib/modules/deployment/index.js
As mentioned in #1038, when contract deployment fails, Embark doesn't give any information about which contract caused the error.
> Improve error messages when contract deployment fails

- embark-ui/package-lock.json
- src/cmd/cmd.js
- src/lib/core/env.js
- src/lib/core/fs.js
- src/lib/modules/console/index.js
- src/lib/modules/pipeline/webpack.config.js
- src/test/fs.js
**TL;DR**
DApps with embark installed locally were suffering from lingering module resolution problems, but not always... it depended on their dependencies. This PR tries to improve the situation in lieu of more extensive revisions (which may ultimately be necessary).
Among the changes included here, I've introduced a `lib/core/env.js` script, which groups together all of the `process.env.X` defaults and anchors. Also, due to sensitivity around plugin ordering, the default webpack config now includes @babel/plugin-proposal-decorators in the correct order relative to other plugins.
Several problems were noticed with [dreddit-devcon](https://github.com/status-im/dreddit-devcon), which was originally supposed to feature a local install of the latest embark 4 alpha version; similar problems …
> Fix local install problems

- src/lib/modules/webserver/server.js
Embark's webserver needs to serve the production build of embark-ui from the root of the package not from `dist/`.
> fix(@embark/webserver): load embark-ui sources from the correct path

- src/lib/core/config.js
In https://github.com/embark-framework/embark/pull/975/commits/594d1323faa272ef305e9870b8dd6f8db63f4d10 we've introduced the ability
to configure balance-related options with human readable ether units.
There are cases where there's account configurations that don't come
with a `balance` property, which breaks Embark when running an Embark app.
Fixes #1067
> fix(@embark/core): don't expect `balance` on `accounts`

- src/lib/modules/coverage/contractSource.js
- src/lib/modules/coverage/contractSources.js
- src/lib/modules/coverage/contract_source.js
- src/lib/modules/coverage/index.js
- src/lib/modules/coverage/sourceMap.js
- src/test/coverage.js
In order to get result for the constructor we also need to run code coverage on the bytecode, not only the deployedBytecode.
See below: code coverage is now 100%
> feat: run coverage for bytecode and deployedBytecode

- src/lib/constants.json
- src/lib/modules/contracts_manager/index.js
- src/lib/modules/deployment/index.js
Fixes part of https://github.com/embark-framework/embark/issues/1028
It at least now enables to deploy completely using RPC.
Problem was that somehow, we didn't parse contract args correctly if it was an object. So `_lpBase: '$LiquidPledgingMock'` returned a void address.
I also added a better message for bad inputs, just in case.
> Fix using an object as arguments

- src/cmd/cmd.js
This PR aims to solve issue #937 and supersedes PR #999 to match new contributing criteria. 
It Adds a --template option to the embark demo CLI command so it is now possible to generate a demo project using an existing embark's template repository on Github with an existing demo branch (e.g. `embark demo --template vue` will use `embark-framework/embark-vue-template#demo`) or any other git URL repository. If no `--template` option is specified, the command  will generate a demo from default template in `templates/demo`.
This new feature will allow users to create a dapp demo using, for example Vue.js framework. A corresponding template will be sent to demo branch in [https://github.com/embark-framework/embark-vue-template](https://github.com/embark-framework/embark-vue-template)
The …
> feat(@embark/cli): add --template option to embark demo cli command

- src/lib/core/ipc.js
Fixes #1063 
Happened when you used the console standalone, which still launches a blockchain process.
However, the console uses IPC as a Client, whereas the `run` is a server (for the console and others to connect to. 
The blockchain acts as a client too and is trying to send it's logs to the server, but there is none with a console, so it crashed.
Now, it looks for the IPC to be connected first.
> IPC: send requests and events only when connected

- src/lib/core/config.js
- src/lib/modules/contracts_manager/index.js
- src/lib/modules/specialconfigs/index.js
Prior to this commits deployment lifecycle hooks had been defined as Array<string> due
to historical reasons (contracts.js) used to be a json file back in the days.
`deployIf`, `onDeploy` and `afterDeploy` can now be defined as (async)
function and have access to several dependencies such as contract instances and web3.
However, in order to have needed dependencies registered in the dependencies object,
all lifecycle hook dependencies need to be listed in the `deps` property
as shown below.
Also note that this is NOT a breaking change. Existing deployment lifecycle
hooks written in Array<string> style still work.
All three lifecycle hooks can now be defined as (async) functions and get an dependency
object with a shape like this:
```
interface DeploymentLifecycleHookDependencies { …
```
> feat: introduce function support for deploy lifecycle hooks

- package.json
- src/lib/core/config.js
- src/lib/modules/scaffolding-solidity/templates/contract.sol.hbs
- src/lib/modules/solidity/solcP.js
- src/test/compiler.js
- src/test/config.js
- src/test/contracts/contract_with_http_import.sol
- src/test/contracts/contract_with_import.sol
- src/test/contracts/simple_storage.sol
- src/test/contracts/token.sol
- src/test/contracts/token_storage.sol
- src/test/fixtures/cont.sol
- templates/boilerplate/embark.json
- templates/demo/contracts/simple_storage.sol
- templates/demo/embark.json
- templates/simple/embark.json
- test_apps/coverage_app/contracts/branches.sol
- test_apps/coverage_app/contracts/events.sol
- test_apps/coverage_app/contracts/loops.sol
- test_apps/coverage_app/contracts/modifiers.sol
- test_apps/coverage_app/contracts/simple_storage.sol
- test_apps/coverage_app/embark.json
- yarn.lock
What's in:
- Accept 0.5.0 solc compiler
- Update demo to use 0.5.0
- Update test_apps/coverage_app to use 0.5.0
- Update templates
What's *not* in:
* Update test_apps/test_app to use 0.5.0:
2 reasons:
** we depends of open zeppelin and they haven't updated yet, as it is a minor version with zero major, the caret range don't allow it
** we depends of embark contracts in master => It seems like a bad idea to do that in general plus the caret range don't work again
fixes https://github.com/embark-framework/embark/issues/1081
> feat: update to solc 0.5.0

- src/cmd/cmd_controller.js
Fixes #1091
Speeds up tests because coverage triggers big loops on each new block headers.
> Fix slow tests by deactivating coverage without --coverage

- src/lib/modules/whisper/js/communicationFunctions.js
These two options are useful for identifying to whom was the whisper message directed, and what's the pubKey that signed the message.
https://web3js.readthedocs.io/en/1.0/web3-shh.html#notification-returns
> Adding signature and recipient's public key to whisper envelope

- src/cmd/cmd_controller.js
- src/lib/modules/pipeline/index.js
This fix ensures that `embark build --contracts` outputs the contracts
the same way a normal build would.
Closes #1088
> fix(@embark/cmd): output contract json

- src/lib/modules/ens/ENSFunctions.js
We've introduced a regression in https://github.com/embark-framework/embark/commit/2dfaaa8201c664efb99e54bc7a0b3b3ea07028bd where zero addresses
have been replaced with a constant, including the ones within ENSFunctions.
The problem is that this code is as well added to the EmbarkJS client, where importing
`../../utils/addressUtils` won't work as it isn't available.
This commit reverts back to have ENSFunctions having its own ZERO_ADDRESS constant.
> fix(@embark/ens): use local ZERO_ADDRESS in ENSFunctions

- src/lib/core/config.js
- src/test/config.js
- src/test/test1/config/contracts.json
In https://github.com/embark-framework/embark/commit/d3f6b4398620e643f16634d30fdc9cb56d9e9bee we ensured that Embark automatically
expands `0x0` address to full zero addresses in order to stay backward compatible
with existing projects that made use of `0x0`, even after we've upgraded web3,
which doesn't allow that syntax anymore.
Turns out however, that the address expansion for `afterDeploy` hook was
done in the wrong place. This was due to a bug in our documentation that has been
fixed in https://github.com/embark-framework/embark-site/commit/66a5bec46d05d6ed8ec1d21e6f5ca3615a813277
> fix(@embark/core): expect `afterDeploy` hook on contracts config environment

- src/lib/modules/coverage/contractSource.js
In order to match node, use only the offset.
Problem with full match:
in case that the instruction is:
```
foo++
```
the source map will be: `1:3:0` instead of being `1:5:0`
So each time the offset match we assume this line has been covered
> feat(coverage): count node by line only

- embark-ui/src/components/TextEditorToolbar.js
- embark-ui/src/containers/EditorContainer.js
- embark-ui/src/containers/TextEditorToolbarContainer.js
* Rename openAsideTab to toggleAsideTab which is more explicit
* Handle the case where nothing is open or close but just updated.
In that case this is a noop for changing the size of the containers
> fix: open/close aside container

- src/cmd/cmd.js
As discussed in #1121, the `eject-webpack` command in Embark's CLI
exposes implementation details of the CLI's build process, namely webpack.
If we ever change our internal build tooling, commands like this
will become obsolete immediately. That's why this commit introduces
a new command `eject-build-config`, with `eject-webpack` being an alias for it.
So the following commands are the same:
```
$ embark eject-build-config
```
and
```
$ embark eject-webpack
```
The `eject-webpack` command can now be marked as deprecated and removed in future
versions of Embark.
Closes #1121
> feat(@embark/cli): introduce `eject-build-config` alias

- package.json
- src/lib/modules/blockchain_process/dev_funds.js
- src/lib/modules/blockchain_process/proxy.js
- yarn.lock
Use proper stream parsing to consistently track JSON-RPC messages.
For HTTP POST requests use the `stream-json` package to assemble request and response message objects.
For WebSocket requests continue to use `simples/lib/parsers/ws` to process stream frames into messages. For Websocket responses use the Receiver class of the `ws` package to process stream data into messages. In both cases, make use of the `stream-chain` and `pump` packages to avoid leaks.
This mishmash of stream parsing approaches is the result of much experimentation to find a working solution. For example, `simples/lib/parsers/ws` does't work for processing WebSocket responses and `ws.Receiver` doesn't work for processing requests. Additional revisions may be necessary.
Revise `blockchain_process/dev_funds.js` to use …
> refactor(@embark/blockchain_process): improve the blockchain proxy

- src/lib/modules/ens/embarkjs.js
- src/lib/modules/ens/index.js
We introduced a bug when fixing the hangs by returning on error when resolving sub domains, but the real trick is to look at the error and if it's the right error ('Not registered yet'), then we register,
Also, while playing with it, I found that doing `await EmbarkJS.Names.resolve('eth')` gives the resolver address instead of the name's address. This was fixed so `await` works correctly now.
> Fix ENS register + Make EmbarkJS functions work with await

- src/lib/modules/blockchain_process/proxy.js
Ignore the sequence of bytes `03:ef:bf:bd` that are sent between Chrome/Firefox (others?) and the node process when a browser connected via websocket to the blockchain proxy is closed/reloaded. The theory is that sequence is part of a socket control frame that is leaking to `parseJsonMaybe` from `http-proxy-middleware`.
> fix(@embark/blockchain_process): ignore socket disconnect bytes

- src/lib/core/env.js
- src/lib/modules/pipeline/webpack.config.js
- src/lib/modules/whisper/js/communicationFunctions.js
Include yarn's global path when modifying `NODE_PATH` since dependencies are deduped when a package is installed globally with yarn, which is different from npm's behavior.
Fix webpack resolution by listing relative `'node_modules'` in `resolve/Loader:{modules:[...]}`. This ensures that dependecies' dependecies are resolved correctly when webpack builds a DApp.
Remove the invocation of `.catch()` on a subscription object which lacks that method.
> fix: adjust module resolution behavior

- src/lib/core/plugin.js
- src/lib/modules/code_generator/index.js
- src/lib/modules/deployment/contract_deployer.js
- src/lib/modules/tests/test.js
This commit introduces a new API `registerTestContractFactory()` which can be
used to register a factory function for the creation of web3 contract instances
in the testing environment.
Example:
```
// some.plugin.js
module.exports = function (embark) {
embark.registerTestContractFactory((contractRecipe, web3) => {
// do something with web3 and contractRecipe and return contract instance here
});
};
```
Closes #1066
> feat(@embark/plugins): introduce API to register test contract factories

- src/lib/core/config.js
- src/lib/modules/code_generator/code_templates/web3-connector.js.ejs
- src/lib/modules/code_generator/index.js
- src/test/config.js
- templates/boilerplate/config/contracts.js
- templates/demo/app/components/blockchain.js
- templates/demo/config/contracts.js
- templates/simple/contracts.js
Update demo to work with `EmbarkJS.enableEthereum`
DO NOT MERGE until a new version of EmbarkJS has been published
> feat: enable ethereum manually

- src/lib/constants.json
- src/lib/modules/ipfs/process.js
- src/lib/modules/storage/storageProcessesLauncher.js
- src/lib/utils/utils.js
When adding URLs to IPFS CORS that are not localhost, the IPFS daemon needed to be restarted after non-localhost CORS updates were added to the IPFS config. Without the restart, any non-localhost URLs added to the CORS were not being sent in the CORS header.
After this change, when the IPFS process is run, the following happens:
1. IPFS config is checked if the correct CORS settings are present in the config.
2. If not present, they are updated and IPFS is restarted.
3. If they are present, continue without restarting IPFS.
> fix(@embark/core): Restart IPFS after CORS Update

- embark-ui/src/components/Layout.js
- embark-ui/src/sagas/searchSaga.js
In the cockpit, allow the search to find the contract by name. For example in the test_app, searching for “Token” (or “token”) in the cockpit, will take the user to the Token contract page.
> feat(@embark/core): Allow search to find contract by name

- src/lib/modules/scaffolding/framework/reactBuilder/index.ts
- src/lib/modules/scaffolding/framework/reactBuilder/templates/dapp.js.hbs
there is 2 IPFS case:
* text
the text is save to ipfs then the hash is save to the contract
When using the accessor, we directly return the text, ipfs is transparent
* image
the image is save to ipfs then the hash is save to the contract
When using the accessor, we return the url to the file
When using the setter, we present a file upload input
> feat(scaffold): use ipfs in scaffold and upload file

- src/lib/modules/swarm/index.js
If the storage config is set up in such a way that a URL for swarm cannot be determined, the swarm module will exit early.
For example, if the storage config looks like:
```
available_providers: ["ipfs", "swarm"],
upload: {
provider: "ipfs",
host: "localhost",
port: 5001
},
dappConnection: [
{
provider:"ipfs",
host: "localhost",
port: 5001,
getUrl: "http://localhost:8080/ipfs/"
}
]
```
Then there is no way to determine the swarm URL as neither `upload` nor `dappConnection` specify a provider with `swarm`. If this is the case, the swarm module will exit in it’s constructor.
> fix(@embark/core): Disable swarm if URL can’t be determined

- src/lib/modules/blockchain_process/blockchain.js
- src/lib/modules/ens/index.js
- test_apps/test_app/config/namesystem.json
- test_apps/test_app/test/namesystem_spec.js
Support directives in ENS configurations, such that subdomains can be registered to addresses of deployed tokens.
The following directives are supported:
```
"register": {
"rootDomain": "embark.eth",
"subdomains": {
"status": "0x4a17f35f0a9927fb4141aa91cbbc72c1b31598de",
"mytoken": "$MyToken",
"MyToken2": "$MyToken2"
}
}
```
Add unit test for these directives.
>  feat(@embark/core): Support directives in ENS config

- embark-ui/src/components/Converter.js
Prior to this commit, it wasn't possible to enter decimal numbers
with dots. The reason for that is that all units are recalculated
on form control change and values like `2.` are simply converted to
`2`.
As every change will cause a `setState()` in Cockpit, users never had
a chance to get "beyond" the first dot of their input value.
This is now fixed by preventing the recalculation all together when
the last character in the entered value is a `.`
In that case, we simply update the form control using `setState()` and
don't touch all the other values. The next key stroke will cause a full
recalculation again.
> fix(@embark/cockpit/converter): allow decimal numbers

- src/lib/modules/whisper/index.js
Was caused because in embarkjs.js, there is a `throw` when the provider doesn't work, which it doesn't with the simulator (ganache-cli doesn't support whisper).
Instead of removing the throw, I instead detect if Whisper is supported and if nt, I stop trying to make it work.
> Fix crash on using whisper with the simualtor

- src/lib/modules/blockchain_process/parityClient.js
Caused issues when starting Parity with no accounts in the config (so the basic template)
> fix(parity): create password file even when there are no accounts

- src/cmd/dashboard/repl.js
- src/lib/core/plugin.js
- src/lib/modules/console/index.ts
- src/lib/modules/ens/index.js
- src/lib/modules/library_manager/index.js
Created a new API that sits on top of the current API for console command registration. This is NOT a breaking change.
It enables us to register the matches and the description inside the module so that the help command doesn't have to manualy list all the descriptions, but instead only reads them from the module.
This is what the API looks like:
```
this.embark.registerConsoleCommand({
description: "description for the help command",
matches: ["this", "that"],
// OR a function for more complex cases
matches: function (cmd) {
return cmd === 'this'; 
},
use: "that <option>" // Optional: This is the name of the command in the help. If not there, it will use `matches`
}, (cmd: string, callback: any) => {
this.doSomething(callback);
});
``` 
What help looks like:
As you can see, I didn't put …
> Better console command API

- package.json
- src/lib/modules/blockchain_process/blockchain.js
- src/lib/modules/blockchain_process/httpProxyOverride.js
- src/lib/modules/blockchain_process/proxy.js
- src/lib/modules/blockchain_process/simulator.js
- src/lib/modules/code_generator/index.js
- src/lib/utils/accountParser.js
- src/test/accountParser.js
- yarn.lock
One of the last steps of the blockchain refactor. Now, with this, in the Dapp, you get all the accounts specified in the blockchain config while getting accounts.
> Proxy accounts from the blockchain so that they can be used in the Dapp

- src/cmd/cmd_controller.js
- src/lib/core/engine.js
- src/lib/modules/console/index.ts
Was caused because tests require the console to register providers, but we have a flag to not register when ipc is connected. So added a flag to force registration (only used for tests right now)
> Fix tests hanging when connecting to a node

- src/lib/modules/whisper/index.js
In https://github.com/embark-framework/embark/commit/1461e95c39d0ec4b7b5b0d08f51b2d2cb5110349 we've introduced a guard that ensures whisper isn't crashing
when Embark is used with the Simulator. This unfortunately also introduced
code that tries to connect to an existing websocket provider that isn't actually
ready at the time it tries to connect.
This commit ensures `web3.shh.getInfo()` is only called once `web3` is ready
and therefore the WS connection as well.
> fix(@embark/whisper): ensure web3 is ready when whisper info is requested

- package.json
- src/lib/modules/blockchain_process/blockchain.js
- src/lib/modules/blockchain_process/httpProxyOverride.js
- src/lib/modules/blockchain_process/proxy.js
- src/lib/modules/blockchain_process/simulator.js
- src/lib/modules/code_generator/index.js
- src/lib/utils/accountParser.js
- src/test/accountParser.js
- yarn.lock
The problems described in embark PR #1166 can be resolved by implementing the blockchain proxy with `http-proxy` directly instead of using `express` together with `http-proxy-middleware`. The ultimate cause of the buggy behavior (the "stuck sockets" problems described in #1166) is unknown.
The need to swallow some errors as described in embark PR #1181 is also eliminated by dropping `http-proxy-middleware` and `express`.
> refactor(@embark/blockchain_process): remove http-proxy-middleware

- src/lib/utils/utils.js
This PR replaces #1166. The "stuck sockets" bug is addressed in #1195 so there is no longer a need to use timeouts. However a few aspects of the original PR are still useful, and lessons learned from #1166, #1181, and #1195 can be put to good use.
Use a websocket client from the `ws` package when pinging websocket endpoints instead of manually building a request header. The `'upgrade'` event being listened for was never actually firing; and though a response was received for those pings, the response messages indicated problems with those requests. It seems cleaner to use a proper websocket client and callback success upon the `ws` client's `'open'` event.
Abstract error and success handling across websocket and http pings.
Report network errors other than `ECONNREFUSED` with …
> refactor(@embark/utils): use a 'ws' websocket client in pingEndpoint

- src/cmd/cmd_controller.js
Was caused by the new certOptions needed by the blockchain client.
It was added to the blockchain process but not the basic blockchain client (`embark blockchain`)
> Fix logger.info not defined

- src/lib/modules/whisper/index.js
`waitForWeb3Ready` was never making it to the point it sets `this.web3Ready = true` and invokes its callback because once the provider's connection's `readyState` is `3` ("closed or couldn't be opened") there is no possibility it will change to `1` ("open and ready").
Call the `connectToProvider` method before setting up a retry with `setTimeout` so that a new instance of `Web3.providers.WebsocketProvider` is used on each retry.
> fix(@embark/whisper): use a new WebsocketProvider on each retry

- src/lib/utils/logHandler.js
Got this error by trying to connect via WS in the Dapp when I deactivated WS.
It threw an error in the log handler because somehow it tried to log an empty object.
Now this is handled
> fix(logHandler): stringify objects instead of trying to split it

- src/lib/utils/template_generator.js
- src/test/template.js
Support for all template URL syntax as spec’d in https://our.status.im/embark-3-2-much-more-than-a-moonshot/ (Everyone Gets A Template section).
Unit tests were added for all missing cases.
| Test case        | Command           | Successful?  | Output |
| :----------------------------------------- | :--------------------------------------------------------- | :---: | :-------- |
| ~~1a. Normal React template, no URL~~  			| ~~`embark new 1-normal-template-react --template react`~~ | ~~No~~ | ~~see below~~ |
```
Installing template from https://github.com/embark-framework/embark-react-template/tree/4.0
Downloading template...
Download failed, response code 404
Retrying with the default branch...
It may not be compatible with your Embark version 4.0.0-alpha.2
Installing template from …
```
> fix(@embark/core): Fix `—template` URL support

- embark-ui/src/components/ContractTransactions.js
- embark-ui/src/components/DebugButton.js
- embark-ui/src/constants.js
- src/lib/constants.json
- src/lib/modules/contracts_manager/index.js
- src/lib/modules/debugger/index.ts
- src/lib/modules/ens/index.js
- src/lib/modules/ens/register.js
- src/test/contracts.js
- src/typings/json.d.ts
When a transaction errors in the cockpit, show the error in the transaction log.
This does not catch errors in web3 that do not make it server-side (ie when executing a tx from the console or from the browser).
Add unit test for contract error logs in the `ContractManager`
> fix(@embark/core): Show transaction log for errors

- src/lib/core/modules/coderunner/codeRunner.js
- src/lib/modules/ens/embarkjs.js
Changes in https://github.com/embark-framework/embark/commit/c64c093a48626736ce9da64b603e1c3820ea3f22 resulted in a regression
that ENS functions within console/dashboard didn't work properly anymore.
This commit ensures that both APIs, `EmbarkJS.Names.resolve()` as well as
`EmbarkJS.Names.lookup()` can be either used using `async/await` or promised
based syntax within the console/dashboard.
Example:
```
await EmbarkJS.Names.resolve('me.eth.eth');
EmbarkJS.Names.resolve('me.eth.eth').then(val => ..., err => ...)
EmbarkJS.Names.resolve('me.eth.eth', (err, val) => ...)
```
Same with:
```
await EmbarkJS.Names.lookup('0x...');
EmbarkJS.Names.lookup('0x...').then(val => ..., err => ...)
EmbarkJS.Names.lookup('0x...', (err, val) => ...)
```
> fix(@embark/ens): make resolve() work with promises and callbacks

- src/lib/core/fs.js
- src/lib/core/ipc.js
- src/lib/core/processes/processManager.js
- src/lib/modules/blockchain_process/gethClient.js
- src/lib/modules/blockchain_process/miner.js
- src/lib/utils/host.ts
- src/lib/utils/utils.js
- src/test/fs.js
This PR replaces #1202.
When embark is running on Linux and macOS, unix socket files are used for geth's and embark's IPC files. A problem can arise if a DApp is in a deeply nested directory structure such that character-length of the path to a socket file exceeds the maximum supported length. See #450.
Also, if the DApp context is a Linux container running on a Windows Docker host, and if the DApp is mounted from the host's file system, there is a problem: unix socket files are incompatible with the Windows file system.
Solve both problems at once by storing a DApp's `.ipc` files in a directory within `os.tmpdir()`. Introduce `ipcPath()` in `core/fs.js` and use a truncated SHA-512 hash of the DApp's path in the name of the temporary directory created for that purpose so that DApps won't …
> feat(@embark/core): store IPC files in a dir within os.tmpdir()

- src/lib/modules/blockchain_process/parityClient.js
Parse legacy version of Parity. Pre-version 2 of Parity outputs “Parity <version>” instead of the post-version 2 “Parity-Ethereum”. Embark was emitting an error when the version of an older Parity client could not be parsed, and no warning messages regarding the version were shown.
This PR modifies the regex that parses the version so that older versions of Parity can be detected and the appropriate warning message can appear.
> fix(@embark/core): Support legacy Parity version parsing

- src/lib/modules/pipeline/webpack.config.js
I had to eject the webpack config and add this to get any project at all to run on Windows/Git Bash without this error:
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.                                                                                                                                                                              ││  - configuration.context: The provided value "C:/Users/xxx/GitHub/xxxxxx" is not an absolute path!                                                                                                                                                                                              ││    -> The base directory (absolute path!) for resolving the `entry` option. If …
> Fix for error running anything on Windows with Git Bash

- src/lib/modules/pipeline/webpack.config.js
Reverts embark-framework/embark#1198
The change introduced by #1198 is not needed for embark v4, it only helps with v3.2.x.
It’s a weird edge case. When running node in Git Bash on Windows:
```
> process.env.PWD
'/c/Users/micha/dapps/embark_demo'
```
On Windows, `process.env.PWD` is normally undefined.
When normalized, that `'/c/'` path can’t be successfully used with `path.join`. I tried `existsSync` when joining it (normalized) with `'embark.json'` and got `false`. Swapping it for `process.cwd()`, `existsSync` reports `true` as expected.
I’m not sure why it was working out when the normalized path is processed by webpack. If we wanted to properly fix it and cut a new 3.2.x release, we would need to change things here:
https://github.com/embark-framework/embark/blob/v3.2.7/cmd/cmd.js#L9-L …
> Revert "Fix for error running anything on Windows with Git Bash"

- src/lib/modules/blockchain_process/proxy.js
Change the blockchain proxy so that it listens on the `host` argument passed to `Proxy#serve` rather than on `defaultHost`.
> fix(@embark/blockchain_process): proxy listens on the specified host

- src/cmd/cmd_controller.js
- src/cmd/dashboard/dashboard.js
- src/cmd/dashboard/monitor.js
- src/cmd/dashboard/repl.js
- src/lib/core/ipc.js
- src/lib/modules/console/index.ts
Send a message over IPC when a command is executed from the REPL so that command history is immediately unified across `embark run` and one/more `embark console`. Previously, for `embark console` to pick up a command entered in the REPL of an `embark run` of which it was an IPC client it would have to be restarted, and vice versa.
> feat(@embark/cli): unify command history without needing a restart

- src/lib/modules/blockchain_connector/embarkjs.js
Caused Dapps to crash because we expect web3 1.x but metamask injects a 0.x web3 instance.
Fixed by using a 1.x instance with the metamask provider.
> fix(blockchain): fix metamask using the old web3

- src/lib/modules/blockchain_connector/fundAccount.js
- src/lib/modules/blockchain_process/dev_funds.js
- src/lib/modules/ens/index.js
- src/lib/modules/tests/test.js
- src/lib/utils/logHandler.js
- src/lib/utils/utils.js
- src/test/accountParser.js
- test_apps/test_app/test/config_spec.js
Specifying large ether values in the configs was causing embark to crash as javascript could not handle the large integer after the value was converted to wei.
The fix involves converting all values to BigNumbers and then comparing and adding/subtracting BigNumbers from that point forward.
There are two specific components that this affected: `config/contracts > accounts > balance` and `config/blockchain > account > balance`. The contracts config is used to fund accounts for contract deployment while the blockchain config is used for dev_funds accounts.
JSON.stringify unknown log messages
Add a unit test in the test app that sets a large ether value in the config before contract deployment and ensures the account balance is the value specified in the config.
Prior to this commit, if …
> fix(@embark/core): fix to allow large ether values

- src/cmd/cmd_controller.js
- src/lib/core/config.js
- src/lib/core/engine.js
- src/lib/core/plugin.js
- src/lib/core/plugins.js
- src/lib/index.js
Expose Embark’s version to the plugin constructor, allowing plugins to make logical decisions based on the version of Embark.
> feat(@embark/core): Expose embark version to plugin constructor

- src/lib/core/modules/coderunner/runCode.js
Supply a custom require function to the vm context for `doEval` so that module resolution succeeds for both DApp dependencies and Embark dependencies.
> fix(@embark/coderunner): use custom require function in vm context

- src/lib/modules/contracts_manager/index.js
- src/lib/modules/deployment/contract_deployer.js
- src/lib/modules/solidity/index.js
Replacement for: https://github.com/embark-framework/embark/pull/1232
Now uses the `linkReferences` that comes from the solc output. Solc docs: https://solidity.readthedocs.io/en/v0.5.1/using-the-compiler.html?highlight=linkReferences
> fix(contracts): fix linking libraries with long paths using output

- src/cmd/cmd.js
- src/cmd/cmd_controller.js
- src/lib/core/engine.js
- src/lib/modules/authenticator/index.js
This option is added to run and console.
This can be usefull while developing on cockpit,
the auto reload don't always ask to authenticate
> feat: add option --no-single-use-cockpit-token

- embark-ui/src/actions/index.js
- embark-ui/src/containers/AppContainer.js
- embark-ui/src/sagas/index.js
- embark-ui/src/services/api.js
- embark-ui/src/utils/utils.js
- src/lib/constants.json
- src/lib/modules/blockchain_listener/index.js
- src/lib/modules/blockchain_process/blockchain.js
- src/lib/modules/blockchain_process/blockchainProcess.js
- src/lib/modules/blockchain_process/blockchainProcessLauncher.js
- src/lib/modules/blockchain_process/dev_funds.js
- src/lib/modules/code_generator/code_templates/web3-connector.js.ejs
- src/lib/modules/code_generator/index.js
- src/test/devFunds.js
Regular transactions (aka “dev funds”) exist in embark as a workaround to a known bug in geth when using metamask. The workaround is to send a transaction at a regular interval (1.5s), which pushes through any transactions that were stuck. The problem is that the transaction logs and trace logs become cluttered and difficult to parse visually.
This PR disables regular transactions until the following conditions are met:
1. Embark is running geth
2. The user is running metamask in their browser
3. The user authenticates to the cockpit with `enableRegularTxs=1|true` in the query string.
A console warning is show in large letters in the browser with a link to the cockpit URL that includes the special query string to enable regular txs.
This could be extended later to have a button in the …
> feat(@embark/core): Disable regular txs until needed

- src/lib/modules/ipfs/process.js
Check if IPFS config has `API.HTTPHeaders.Access-Control-Allow-Origin` before attempting to update it.
`ipfs init` produces a default configuration without a `API.HTTPHeaders.Access-Control-Allow-Origin` element in the JSON. This caused an error to be thrown when attempting to update the IPFS config to provide CORS values.
> fix(@embark/ipfs): Update IPFS config CORS with default config

- embark-ui/src/containers/EditorContainer.js
- embark-ui/src/reducers/selectors.js
- src/lib/modules/contracts_manager/index.js
In order to start debugging contracts, the filename is required.
Instance of contracts use the parent contract filename
> fix: allow to debug instanceOf contracts

- src/lib/core/plugin.js
- src/lib/modules/compiler/index.ts
- src/lib/modules/solidity/index.js
This is needed because the solc plugin has a version check to see if it is compatible. However, there was a race condition in it, because it only registered itself if the version was ok, but Embark was sometime faster than the version check, so it compiled straight away with Embark's compiler.
The new API is NOT breaking, it just enables plugins to callback with `false` as the result and it tells Embark that the version was not compatible. Embark will then use the next available compiler in the list.
If no compiler works (which should never happen since Embark downloads it), it shows an error.
API used here: https://github.com/embark-framework/embark-solc/pull/21
> feat(compiler): add a new compiler api that checks for compatibility

- src/lib/modules/contracts_manager/index.js
- src/lib/modules/solidity/index.js
- src/lib/modules/tests/solc_test.js
- src/lib/modules/tests/test.js
Remix_test-injected contract files were not correctly being tested due to an update in the `remix-tests` signature. I'm really not sure how tests were not completely bombing out during testing.
This PR introduces a few changes:
1. Ensure all contract files have been compiled before skipping compilation. This can occur if contract files have been added after a compilation round has already completed (ie in the tests).
2. Update solc tests to support latest `remix_tests.runTests` signature and include `userdoc` in compiled contracts.
3. Ensure `EmbarkJS` is reset before executing solc tests - like in the js tests, this is required for built EmbarkJS contract objects to behave correctly when it's functions are executed against the chain.
4. Refactor “all files already compiled” function. …
> fix(@embark/core): Fix contract testing with `remix_tests`

- package.json
- src/lib/core/file.js
- src/test/contracts/recursive_test_0.sol
- src/test/contracts/recursive_test_1.sol
- src/test/contracts/recursive_test_2.sol
- src/test/file.js
- yarn.lock
Add support to recursively import contracts. If we have three contracts
1. A imports B
2. B imports C
Then prior to this PR, contract A would import contract B, and a remapping would be added to the contract so the compiler would know how to find contract B. However, contract B imports contracts C, and because the `parseFileForImport` method was not recursive, the remappings were not able to go one level deeper to remap the path to contract C, and thus the compiler would not know how to locate contract C, and would complain with the error `File outside of allowed directories.`
With the introduction of this PR, the `parseFileForImport` method is now recursive, and so any contract imported is also checked for it's own imports that can be remapped. Specifically, this use case is applicable …
> feat(@embark/core): Recursively import contracts

- src/bin/embark.js
Currently if you install embark in dev deps and you have deps the shim tells you it is not found because the first check was only looking at the existence of deps not at the existence of deps and embark
> fix: allow to use embark in dev deps

- src/lib/modules/contracts_manager/index.js
With that, in contracts.js, you can do:
```
artifact: 'artifacts/contracts/SimpleStorage.json`
}
```
And it will not need the file and will not deploy it if the address is already specified.
Caveat: This requires the Embark artifacts. Should we do an artifact abstraction at some point to accept artifacts from Truffle or others?
> Contracts can point to an artifact file to bypass deploy and compile

- src/lib/constants.json
- src/lib/core/config.js
- src/lib/modules/code_generator/code_templates/web3-connector.js.ejs
- src/lib/modules/code_generator/index.js
- src/test/code_generator.js
- templates/boilerplate/app/js/index.js
- templates/boilerplate/embark.json
- templates/demo/app/dapp.js
- templates/demo/embark.json
Dapps now need to call the connect, but it has a callback and returns a promise, so it can replace `onReady`.
The folder where the generations are generated can be changed in `embark.json`.
We only regenerate when there is an actual change.
Goes hand in hand with https://github.com/embark-framework/EmbarkJS/pull/38
> Move blockchain connect to EmbarkJS and let dapps call it

- src/lib/modules/pipeline/index.js
if using async function, the callback is not present and we need to use return,
revert to normal function
> fix: using async with async npm

- src/lib/utils/solidity/remapImports.ts
Remapping of imports was failing if the file had already had it’s import replaced with a pattern that would match with subsequent replacement attempts. For example, if the dapp contract contained
```
import ".embark/node_modules/zeppelin-solidity/contracts/ownership/Ownable.sol”;
```
which lives in `node_modules`, then `zeppelin-solidity/contracts/ownership/Ownable.sol` would be replaced with `.embark/node_modules/zeppelin-solidity/contracts/ownership/Ownable.sol`, resulting in:
```
import ".embark/node_modules/zeppelin-solidity/contracts/ownership/Ownable.sol";
```
On subsequent replacements of the same file, the same replacement would occur, resulting in the incorrect
```
import ".embark/node_modules/.embark/node_modules/zeppelin-solidity/contracts/ownership/Ownable.sol";
```
> fix(@embark/core): fix(@embark/core): Fix recursive import remapping

- src/lib/modules/solidity/solcP.js
This commit fixes a bug where it throws while trying to compile solidity
files as it dereferences its `this`.
Unfortunately passing methods as lambda callbacks doesn't correctly
resolve its `this` scope even within fat arrow functions, resulting in
unexpected behaviour where `this` inside lambda is `undefined`.
> fix(@embark/solidity): fix binding in method call

- packages/.yarnrc
- packages/embark-ui/.yarnrc
- packages/embark/.yarnrc
- test_dapps/.yarnrc
- test_dapps/packages/.yarnrc
- test_dapps/packages/contracts_app/.yarnrc
- test_dapps/packages/test_app/.yarnrc
- test_dapps/packages/test_app/extensions/embark-service/.yarnrc
- test_dapps/packages/test_app/extensions/embark-service/package-lock.json
- test_dapps/packages/test_app/extensions/embark-service/package.json
Yarn merges `.yarnrc` from the current working directory with `.yarnrc` files higher in the directory tree, so that file isn't needed in each package.
Unfortunately, npm doesn't do the same for `.npmrc` files, so a similar cleanup isn't possible.
Add version info to `test_app/extensions/embark-service/package.json` to that `yarn install` can work correctly if manually invoked in `test_app`.
> build: cleanup .yarnrc

- .gitignore
- packages/embark-ui/.gitignore
- packages/embark/.gitignore
Put common patterns we expect to use across most `packages/*` into the top-level `.gitignore`. If there are package-specific patterns they can go in that package's `.gitignore`. For example, `packages/embark-ui` ignores its `build/` directory while commonly we ignore the packages' `dist/` directories.
> build: cleanup .gitignore

- .eslintrc.json
- packages/embark/package.json
Move `packages/embark`'s eslint config into the monorepo root.
Remove `"plugin:react/recommended"` since it's not commonly needed.
Put a `"eslintConfig"` config key/object in `packages/embark`'s `package.json` that directs eslint to extend the root config; other `packages/*` can do likewise.
> build: cleanup eslint configuration

- yarn.lock
PR 1304 introduced a regenerated `yarn.lock` at the root. Somehow, that's responsible for the error described in [a comment on PR 1307][error].
Restore the `yarn.lock` from 3f61e314d996902b9845101313461a96c6e776f8, then catch it up with `yarn reboot:full` in the root. `yarn typecheck` then runs without error in `packages/embark`.
[error]: https://github.com/embark-framework/embark/pull/1307#issuecomment-461184291
> fix: use a yarn.lock that wasn't completely regenerated

- packages/embark/src/lib/core/config.js
- packages/embark/src/lib/core/file.ts
- packages/embark/src/lib/utils/solidity/remapImports.ts
- packages/embark/src/test/config.js
Prior to this commits `this.contractsFiles` kept growing at run time
for every file change that was detected by Embark.
The reason for that was a bug in a condition that determines whether
a subset of contract files needed to be added to memory or not.
In addition to that we kept pushing externally loaded contract files into
memory, even if they already existed in memory.
**Also notice** that this PR introduces `File.originalPath` which actually isn't necessary for the fix introduced here, but I'd have to roll back most of the changes to pull that out into a separate commit.
We'll need `originalPath` for smart compilation later.
Let me know if you want that in a separate commit.
> fix(@embark/core): fix memory leak when contract files are loaded

- packages/embark/src/lib/modules/deployment/contract_deployer.js
This allows for contract bytecode/abi to be specified on the contract config.
> fix: estimate gas automatically when not specified

- packages/embarkjs/package.json
- yarn.lock
Packages' `"clean"` scripts should run regardless of whether `node_modules` is in place at the root and/or package levels, but the `embarkjs` package was missing a needed `npx` in front of `rimraf` in its script.
Also, bump its devDeps version of rimraf to be in line with the rest of `packages/*` and `test_dapps/*`.
> build(embarkjs): clean script should invoke 'npx rimraf'

- .yarnrc
Yarn can be sensitive to timeouts when downloading large-ish packages that aren't in its cache, e.g. `@reactivex/rxjs`. Specify a high-timeout in the root `.yarnrc` to workaround `yarn install` hanging indefinitely and reporting network connection errors, which seems to be experienced more frequently on Windows than on Linux or macOS. Note: this is probably buggy behavior on yarn's part.
> build: specify a high network timeout in root .yarnc

- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/core/file.ts
- packages/embark/src/lib/core/modules/coderunner/codeRunner.js
- packages/embark/src/lib/core/plugin.js
- packages/embark/src/lib/modules/blockchain_connector/index.js
- packages/embark/src/lib/modules/codeRunner/index.js
- packages/embark/src/lib/modules/codeRunner/vm.ts
- packages/embark/src/lib/modules/console/index.ts
- packages/embark/src/lib/modules/deployment/contract_deployer.js
- packages/embark/src/lib/modules/pipeline/index.js
- packages/embark/src/lib/modules/solidity/index.js
- packages/embark/src/lib/modules/solidity/solcP.js
- packages/embark/src/lib/modules/tests/index.js
- packages/embark/src/lib/modules/tests/solc_test.js
- packages/embark/src/lib/modules/tests/test.js
- packages/embark/src/lib/utils/solidity/remapImports.ts
- packages/embark/src/test/code_generator.js
- packages/embark/src/test/config.js
- packages/embark/src/test/console.js
- packages/embark/src/test/file.js
- packages/embark/src/test/modules/solidity/remapImports.js
- packages/embark/src/test/vm.js
- packages/embarkjs/src/blockchain.js
- packages/web3Connector/index.js
- packages/web3Connector/web3Connector.js
This PR introduces a large number of changes (for that, I am very sorry). Breaking this up in to smaller PR's was causing tests to fail, and the likelihood of them getting merged diminished. There are a couple of PRs this PR closes, and as such, I have kept the original commits to preserve the history. The first two (of three) commits are the closed PRs, and the last is the glue bringing it all together.
The main goal of this PR is to fix the fragility of the tests with EmbarkJS, however in doing so, a number of recent features have been updated:
Remapping of imports still had a few edge cases that needed to be ironed out, as well as have unit tests created for them. More details of the changes an be seen in the closed PR (below).
The main issue with VM2 was running the code generated …
> fix(@embark/core): Fix VM2 + Remap Imports + Monorepo + Tests

- packages/web3Connector/index.js
This is a problem that's caused because we can't require stuff inside the console, so the connector needs to try the global object that was registered for the console, and then in the Dapp, that won't be available and it will require the code.
> fix: use our global Web3 and not Metamask's

- packages/embarkjs/src/blockchain.js
`EmbarkJS.Blockchain.connectConsole` has a potential race condition with both `cb` and `doneCb` firing at the end of the method.
This PR is an attempt to fix that by first awaiting the `cb`, then finally calling `doneCb`, as suggested by @michaelsbradleyjr in https://github.com/embark-framework/embark/pull/1319#discussion_r256850820
Please wait for @michaelsbradleyjr's approval before merging.
> fix(@embark/embarkjs): Fix potential race condition

- packages/embark/src/lib/modules/console/suggestions.ts
Prior to this PR, typing `SimpleStorage.methods.` in to the cockpit console would not show autosuggestions for the contract methods.
Contract names are case sensitive in the VM (VM2). Update the `Suggestions.getSuggestions` method to be case-sensitive when evaluating `Object.keys(<contract class name>.methods)`.
AFTER:
> fix(@embark/cockpit): Fix contract method autosuggest

- packages/embark/src/lib/core/events.js
- packages/embark/src/test/events.js
Add the ability to request an event before it’s command handler has been set.
Add unit tests for events, including the "oracle" use case.
The most useful use case for this is to allow modules/plugins to load asynchronously and without need to know their load order beforehand. This lets us request events in advance of having the event command handler set by the module/plugin.
An additional use case is the ability to reorder services started in `cmd_controller`. Previously, reordering services was quite fragile, as each service would layout command handlers for requests. If the order was changed, the command handlers were not laid out, and requests would go unanswered, causing hangs.
BEFORE:
```
this.events.request(“event:name”, () => {
// never fired
}); …
```
> feat(@embark/core): Add events oracle

- packages/embark-typings/src/embark.d.ts
- packages/embark/src/lib/modules/console/index.ts
- packages/embark/src/lib/modules/console/suggestions.ts
- packages/embark/src/lib/modules/debugger/index.ts
- packages/embark/src/lib/modules/ens/index.js
- packages/embark/src/lib/modules/plugin_cmd/index.js
- packages/embark/src/lib/modules/profiler/index.js
This PR fixes a number of issues relating to the cockpit console.
Fix cockpit console not displaying console usage commands that included “<usage option>”. For example “resolve <name>” would not display the “<name>” part, as it was attempting to write this in as HTML (ansi-to-html conversion).
This was fixed by replacing any instances of “<usage>” with “[usage]”. Please note that future usage strings should not contain text wrapped in “<>”.
Fix “web3.eth.” not suggesting members of `web3.eth`. This was due to a `Object.keys(web3.eth)` throwing `'getOwnPropertyDescriptor' on proxy: trap returned descriptor for property 'defaultAccount' that is incompatible with the existing property in the proxy target` in the console. Changing `Object.keys` to `Object.getOwnPropertyDescriptor` solved the …
> fix(@embark/cockpit): Fix cockpit not suggesting console commands

- packages/embark/src/lib/constants.json
- packages/embark/src/lib/core/config.js
- packages/embark/src/lib/core/fs.js
- packages/embark/src/lib/modules/codeRunner/index.js
- packages/embark/src/lib/modules/codeRunner/vm.ts
- packages/embark/src/lib/modules/code_generator/index.js
- packages/embark/src/lib/modules/ens/ENSFunctions.js
- packages/embark/src/lib/modules/ens/embarkjs.js
- packages/embark/src/lib/modules/ens/index.js
- packages/embark/src/lib/modules/ipfs/index.js
- packages/embark/src/lib/modules/library_manager/index.js
- packages/embark/src/lib/modules/pipeline/index.js
- packages/embark/src/test/code_generator.js
- packages/embark/src/test/file.js
- packages/embark/src/test/fs.js
- packages/embarkjs/src/blockchain.js
- packages/web3Connector/index.js
With this, it is possible to run an external pipeline on an embark project.
This does not remove the pipeline (yet). It just makes it so that it is now possible to run using create-react-app for example.
He is a basic template that you can use: https://github.com/jrainville/embark-cra-template
- To use it, you just need to do `embark new --template "https://github.com/jrainville/embark-cra-template" app-name
- The npm installation will fail because the web3connector is not yet published. You need to change the package.json to point web3connector to the package inside the embark monorepo
- Currently in my repos, but can be moved to the embark umbrella, we just need to decide where we should put it
Notable changes in this PR:
- Putting `*` CORS in dev (`isDev: true`) to enable the port CRA …
> Changes needed to use CRA (or any external pipeline)

- packages/embark/src/lib/modules/console/index.ts
- packages/embark/src/lib/modules/ens/index.js
- packages/embark/src/lib/modules/solidity/index.js
- Fix embark test getting stuck when `embark run` in running next to it (even without `--node`
- Fix ENS transactions getting stuck when using `--node ws:...`
- Fix the regex used by coverage on Windows (backslahes)
> Fixes for the tests

- packages/embark/src/lib/modules/contracts_manager/index.js
- packages/embark/src/lib/utils/contractsConfig.ts
- test_dapps/test_app/config/contracts.js
- Fix for using artifacts where having an address in the artifact still deployed the contract
- Fix gas and gasPrice to be ints or strings
- Fix contracts that were `instanceOf` another contract that had a library, now linking works
> Small fixes to contract configurations

- packages/embark/src/lib/modules/blockchain_connector/index.js
- packages/embark/src/lib/modules/blockchain_connector/provider.js
- packages/embark/src/lib/modules/deployment/contract_deployer.js
- packages/embark/src/lib/modules/tests/test.js
- packages/embark/src/lib/utils/accountParser.js
- packages/embark/src/test/accountParser.js
Also pass `privateKey` values in a way that ethereum wallet likes.
> fix: use right accounts for contract deployment

- package.json
- packages/embark/src/lib/core/plugin.js
- packages/embark/src/lib/core/plugins.js
- packages/embark/src/lib/modules/codeRunner/vm.ts
- packages/embark/src/lib/utils/utils.js
- packages/embark/templates/boilerplate/app/js/index.js
- packages/embark/templates/boilerplate/embark.json
- packages/embark/templates/boilerplate/package.json
- packages/embark/templates/demo/app/dapp.js
- packages/embark/templates/demo/embark.json
- packages/embark/templates/demo/package.json
- packages/embark/templates/simple/embark.json
- packages/embark/templates/simple/package.json
- packages/embarkjs-connector-web3/embarkJSConnectorWeb3.js
- packages/embarkjs-connector-web3/index.js
- packages/embarkjs-connector-web3/package.json
- packages/embarkjs-web3-connector/embarkJSWeb3Connector.js
- packages/embarkjs-web3-connector/index.js
- packages/embarkjs-web3-connector/package.json
- packages/embarkjs/src/blockchain.js
- test_dapps/contracts_app/embark.json
- test_dapps/contracts_app/package.json
- test_dapps/test_app/app/js/index.js
- test_dapps/test_app/embark.json
- test_dapps/test_app/package.json
- Renames the connector to `embarkjs-web3-connector`
- Enables the use of Classes for external plugins
- Only calls doFirst once when connecting in EmbarkJS.Blockchain.connect (otherwise, onReady was called twice)
- Automatically connects for the user in the Dapp
- Converts web3-connector to a class
- Replace the BLockhain.connects by onReady
> Connect the Dapp automatically for users

- packages/embark/src/lib/modules/whisper/index.js
Cockpit whisper messages were not being subscribed to due to a inocuous bug that would swallow errors and ultimately not be subscribed to the `rxjs` observer.
> fix(@embark/cockpit): Fix whisper messages not being received

- packages/embark/src/lib/modules/blockchain_connector/provider.js
`web3.eth.getAccounts` was returning an empty array in the console due to a change, that I’m unsure of what the original intention was for.
@andremedeiros, could you please take a look, and let me know if this breaks the intention of the original changes?
> fix(@embark/core): `web3.eth.getAccounts` returning empty

- packages/embark-typings/src/contract.d.ts
- packages/embark/src/cmd/cmd.js
- packages/embark/src/lib/modules/console_listener/index.js
- packages/embark/src/lib/modules/tests/index.js
- packages/embark/src/lib/modules/tests/reporter.js
- packages/embark/src/lib/utils/transactionUtils.ts
- packages/embark/src/test/modules/console_listener.js
- packages/embark/src/test/transactionUtils.js
Adds a flag to show the tx details just like the tx logger.
Since it uses the same functions as the tx logger, I moved the functions to a utils file and shared them.
> Add flag to show tx details in tests

- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/core/plugins.js
- packages/embark/src/lib/modules/deploytracker/index.js
- packages/embark/src/lib/modules/specialconfigs/index.js
- packages/embark/src/lib/modules/tests/test.js
Add the ability to pass an error in the callback of an event action.
Currently, event actions could either pass back a an error OR a result, but not both, and with no way to distinguish between the two parameters. This PR adds the ability to pass an error as the first parameter of the action callback.
An example of a use case that this fixed: errors on `afterDeploy` were silently swallowed, which has now been fixed.
All instances of `events.request(“deploy:contracts”)` were given an `error` parameter in their callback, and errors printed if it is not undefined.
All instances of `registerActionForEvent` were combed to ensure any callbacks were passing the expected error and result.
> fix(@embark/core): Allow errors in event actions

- packages/embark/src/lib/modules/ipfs/index.js
- packages/embark/src/lib/modules/swarm/index.js
Swarm was not being registered as a service due to a recent change that introduced a bug. The previous change was meant to register “swarm” as a console command to provide output for the `swarm` console command when swarm had not been registered in the VM. The bug, however, returned too early in the cases when swarm was meant to be enabled, thus effectively not registering the entire process.
The fix simply returns only when swarm is in fact, disabled, and also alters slightly the way swarm is determined to be enabled (the changes of which have been copied over to `ipfs`).
> fix(@embark/swarm): Fix swarm not being registered

- packages/embark-ui/src/actions/index.js
- packages/embark-ui/src/components/ContractsDeployment.js
- packages/embark-ui/src/services/web3.js
- packages/embark/src/lib/modules/blockchain_connector/index.js
Reproduce:
1. Go to cockpit > transactions
2. Click a transaction
3. There will be a flicker of an error, then the decoded tx displays OK. Inspecting the network requests, there is a 500 error with a response of
```
AssertionError [ERR_ASSERTION]: invalid remainder
```
This error is also printed in the console.
The issue is that the transaction is not a raw transaction, so instead of trying to decode the non-raw transaction, the transaction can be decoded by web3.
> fix(@embark/cockpit): Fix decode transaction error

- packages/embark-ui/src/sagas/searchSaga.js
This issue was caused by a string to integer conversion. In JavaScript,
when converting a string that starts with `0` (which is the case for tx
hashes) to an integer using `parseInt` it will always yield 0. That,
combined with a block with number 0 would always return a block result
instead of the transaction.
```
> parseInt("0xluri", 10)
0
```
This PR checks if the resulting number equals the string that was
provided on top of checking for the block number.
> fix: cockpit search with tx hash shows tx page

- packages/embark/src/lib/core/ipc.js
- packages/embark/src/lib/modules/blockchain_listener/index.js
- packages/embark/src/lib/modules/blockchain_process/blockchain.js
There are two ways to launch the blockchain process with Embark: standalone, by running `embark blockchain`, or with the dashboard, by running `embark run`.
When Embark runs, it also starts an IPC server that is used, amongst other things, to receive logs from potentially the standalone process. The problem is that the log listener for the standalone blockchain process starts independently of the blockchain process launcher, which will try to start a blockchain process even if one is already running. Each of these also registers an API endpoint which is supposed to serve logs. As the API endpoint is the same for both, one overwrites the other, and in this case `BlockchainListener` always won.
This PR sets things up in a way that `BlockchainListener` will only register its API endpoint if, …
> fix: blockchain logs show in cockpit

- packages/embark/src/lib/modules/console/suggestions.ts
This PR prevents things like `web3.sendTransaction({...})` from being
executed to generate suggestions.
> fix: don't eval function calls for suggestions

- packages/embark-ui/package.json
- packages/embark/package.json
- yarn.lock
Fixes `merged` and removed `webpack-dev-server` through `react-scripts`, as we don't use that anymore.
> fix: upgrade packages with vulnerabilities

- packages/embark-ui/src/components/Console.js
This fixes cases where commands return results with `\n` characters that weren't reflected in the console, such as the `help` command.
[Documentation for these options.](https://www.npmjs.com/package/ansi-to-html#default-options)
> fix: format \n as <br> in cockpit console

- packages/embark-ui/src/components/ContractOverview.js
- packages/embark-ui/src/components/Contracts.js
- packages/embark-ui/src/components/ContractsList.js
- packages/embark-ui/src/utils/presentation.js
- packages/embark/src/lib/modules/contracts_manager/index.js
- packages/embark/src/lib/modules/ens/index.js
Fixes the problem with `Contract log for unknown contract: {"type":"contract-`, because ENS contracts were not part of the contract manager.
> fix(ens/logger): add ens contracts to contract manager before deploy

- packages/embark-ui/src/actions/index.js
- packages/embark-ui/src/containers/AppContainer.js
- packages/embark-ui/src/sagas/index.js
- packages/embark-ui/src/services/api.js
- packages/embark/src/lib/modules/blockchain_listener/index.js
- packages/embarkjs/src/blockchain.js
A console warning is meant to appear in the browser console when the dapp is connecting to web3 using metamask and the blockchain client is geth. The warning displays information telling the user they should enable regular transactions to prevent known issues regarding transactions getting stuck.
The issue fixed here pertained to `warnAboutMetamask` vs `warnIfMetamask` - maybe there was a change that introduced this issue upstream.
Additionally, enabling and disabling of regular transactions via an API endpoint did not
> fix(@embark/core): Metamask + geth warning to enable regular txs

- packages/embark/src/lib/modules/ipfs/index.js
- packages/embark/src/lib/modules/swarm/index.js
Allow `embark upload` to upload to IPFS/Swarm even if the storage module is disabled in the storage config.
An easy way to test this is to set `config/storage.js` > `enabled` to `false` in the demo. Then run `embark upload`.
> fix(@embark/storage): Allow upload when storage disabled

- packages/embark-typings/src/embark.d.ts
- packages/embark-ui/src/actions/index.js
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/cmd/dashboard/dashboard.js
- packages/embark/src/cmd/dashboard/monitor.js
- packages/embark/src/cmd/dashboard/repl.js
- packages/embark/src/lib/core/logger.js
- packages/embark/src/lib/modules/console/index.ts
- tsconfig.json
I'd like @emizzle to confirm I didn't do something wrong, but long story short, when the console is a client in terms of IPC, it didn't do the EmbarkJS `connectConsole` so ENS tests were bound to fail. 
I think we could actually remove the `isEmbarkConsole` condition altogether for the register, but maybe it slows things down a bit or we make it so that we eval only through the console? Because there's a weird gap between runCode and console, but they still need one another
> fix(console): fix ENS tests not working with embark side by side

- packages/embark-ui/src/components/Converter.js
- packages/embark-ui/src/components/CopyButton.css
- packages/embark-ui/src/components/Layout.js
- Fixes the Nav links not being highlighted on children pages. 
- Eg: On Utils/Communication, the Utils link wasn't highlighted
- Also fixes a little style goof on the Converter's page
> Fix nav links with children pages and copy-button

- packages/embark/src/lib/modules/tests/index.js
Previous to this PR, `web3` was only made available to each test case, as it was put in to the global namespace after each test deploy. This was causing issues for tests that use `web3` in the test description (ie in `describe()` or `contract()` functions), as the deploy had not happened yet, and thus `web3` was not yet available. The error encountered in these cases was `web3 is not defined`.
This PR puts `web3` in the global namespace before setting up the tests, making it available to test descriptions.
> fix(@embark/tests): Make `web3` available in test descriptions

- packages/embark-ui/src/actions/index.js
- packages/embark-ui/src/components/ContractsList.js
- packages/embark-ui/src/components/Services.js
- packages/embark-ui/src/containers/AppContainer.js
- packages/embark-ui/src/containers/ContractsContainer.js
- packages/embark-ui/src/containers/DeploymentContainer.js
- packages/embark-ui/src/containers/HomeContainer.js
- packages/embark-ui/src/containers/ServicesContainer.js
- packages/embark-ui/src/sagas/index.js
The services websocket was initiated in the AppContainer and causing all child components to continuously re-render every time there was a service check (which is effectively every second). In addition, the socket was never stopped when not needed (ie when the services component was unmounted).
Create a ServicesContainer that initiates the websocket as part of the container, and stops the socket when the container is unmounted.
Move the ContractsList to be part of the ContractsContainer with a `mode` switch.
Add Deployment page title and description.
NOTE: this requires https://github.com/embark-framework/embark/pull/1413 to work.
> fix(@embark/core): Prevent unnecessary re-renderings

- packages/embark-ui/src/reducers/index.js
- packages/embark/src/cmd/cmd_controller.js
Switching between the two tabs shown on the Dashboard for the cockpit was removing some of the logs that were previously displayed. This was due to an overlap in `id`’s being assigned to the logs from different processes.
To alleviate this, the reducers has been updated to not only check `id` but also `process.name`.
Additionally, the reducer was updated so that the number of logs for **each process** is set to `ELEMENTS_LIMIT`. For example, our `ELEMENT_LIMIT` is currently set to `200` and it would have meant that the total number of process logs across all processes would have been capped at 200. The current changes in this PR allow for 400 total logs, given that we have two processes being monitored for logs.
> fix(@embark/cockpit): Switching between tabs resets logs

- packages/embark-ui/src/services/storage.js
LocalStorage has severe limits that we weren't taking under account. For instance, Safari has a limit, per domain, of 2.5MB, whereas Chrome has a limit of 5MB.
On top of this being a JS editor, and very slow with bigger files, we should limit how big the files we edit can be to prevent filling up local storage.
> fix: limit cockpit editor file size

- dapps/templates/boilerplate/package.json
- dapps/templates/demo/package.json
- dapps/templates/simple/package.json
- packages/embark-async-wrapper/package.json
- packages/embark-compiler/package.json
- packages/embark-graph/package.json
- packages/embark-reset/package.json
- packages/embark-typings/package.json
- packages/embark-ui/package.json
- packages/embark-vyper/package.json
- packages/embark/package.json
- packages/embark/src/lib/utils/template_generator.js
- packages/embarkjs-connector-web3/package.json
- packages/embarkjs/package.json
See: https://github.com/npm/rfcs/blob/latest/implemented/0010-monorepo-subdirectory-declaration.md
Make changes by running this command in the root of the monorepo:
```shell
npx lerna exec --concurrency 1 --stream -- \
'DIRPATH=$(realpath $PWD --relative-to=$LERNA_ROOT_PATH); \
npx json -I -f package.json -e \
"this.repository=\
{\"directory\": \"$DIRPATH\", \
\"type\": \"git\", \
\"url\": \"https://github.com/embark-framework/embark.git\"}"'
```
Don't commit changes to private packages, with the exceptions of embark-typings and embark-reset because those may switch from private to public, and also because the latter will be included in `node_modules` of embark even if it is private since embark-reset is presently a bundled dependency of embark.
Don't include the repository field in dapps …
> feat: add repository.directory field to package.json

- packages/embark-ui/src/components/ContractOverview.js
- packages/embark-ui/src/containers/ContractOverviewContainer.js
We profiled the contracts for the contract overview (the interact tab) in order to list the function, but that is unecessary, as we already have all the information in the ABI.
> Remove contract profiling for contract interactions

- packages/embark/package.json
- packages/embark/scripts/test.js
It's possible to pass a `--require` option to mocha to load a script that sets up `process.env.DAPP_PATH` as needed for embark's tests; that approach is preferable to running mocha in a child process because when running in a child process there seemed to be problems with sources maps and with VS Code's debugger.
After the changes in this PR, the following works as expected, i.e. when there are runtime errors line/col numbers are reported per the files in `src/`:
```
$ yarn build:no-ui
$ cd packages/embark
$ npx mocha "dist/test/**/*.js" \
--exit \
--no-timeouts \
--require ./scripts/test.js \
--require source-map-support/register
```
And the following VS Code launch config works well for me:
```json
{
"type": "node",
"request": "launch",
"name": "test - packages/embark",
"cwd": …
```
> refactor(embark): do not wrap mocha in a child process

- packages/embark/src/lib/modules/blockchain_listener/index.js
https://github.com/embark-framework/embark/pull/1367 introduced a change that prevented the `blockchain_listener` from listening to logs until the IPC server connected. However, the restriction went too far, and included restricting registration of console commands and API endpoints for the regular transactions feature.
This fix reverts the changes that affect registration of regular txs endpoints and console commands.
> fix(@embark/core): Re-enable regular txs commands/api

- packages/embark-ui/src/components/Transaction.js
- packages/embark-ui/src/containers/TransactionContainer.js
- packages/embark-ui/src/containers/TransactionsContainer.js
Before we only displayed links for block number, now it works for `to` and `from`. And thy can be accounts or contracts.
> feat(cockpit/transaction): display a link for contracts and accounts

- dapps/templates/boilerplate/config/pipeline.js
- dapps/templates/demo/config/pipeline.js
- packages/embark/src/lib/core/config.js
- packages/embark/src/lib/core/fs.js
- packages/embark/src/lib/modules/pipeline/index.js
Add an `enabled` property to the pipeline config. This lets developers disable the pipeline using the config file.
Updates to the enabled property will be reflected while embark is running. For example if embark is running with the pipeline, setting `enabled: false` in the pipeline config will build/deploy the contracts but not run the pipeline. Conversely, if embark is running with the pipeline disabled, enabling the pipeline in the config will build/deploy the contracts then build the dapp.
> feat(@embark/pipeline): Add `enabled` property to pipeline config

- packages/embark/src/lib/core/config.js
Prevent embark from crashing when app assets are not specified in `embark.json`.
Previously, if the `app` property of `embark.json` was missing, embark would crash with the error `TypeError: Cannot convert undefined or null to object`.
With this PR, the missing property is null-checked.
> fix(@embark/pipeline): Prevent crash when assets not specified

- packages/embark/src/cmd/cmd_controller.js
They weren't in the cockpit because the listener wasn't started. I know it was removed by @emizzle before, so gonna wait on his input before merging.
> fix(cockpit/dashboard): fix logs not in  cockpit with dashboard

- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/modules/ipfs/index.js
- packages/embark/src/lib/modules/storage/index.js
- packages/embark/src/lib/modules/swarm/index.js
- packages/embark/src/lib/modules/swarm/process.js
Previously, storage providers in embarkjs were not waiting for their respective storage process (ipfs and swarm) to start before running `registerProvider` and `setProvider` in the console.
This PR forces the `registerProvider` and `setProviders` from running in the console until the storage processes have loaded. As a side effect, the code generation of `EmbarkJS` must wait for the storage module ot be fully initiated (ie once the processes have launched and the `registerProvider` and `setProviders` have been run) before generating the code.
This fixes errors pertaining to `Could not connect to a storage provider using any of the dappConnections in the storage config` as these errors were typically caused by `setProviders` being called before the storage processes had fully launched.
> fix(@embark/storage): Storage processes race conditions

- packages/embark-ui/src/reducers/index.js
- packages/embark/src/lib/core/services_monitor.js
This is a weird bug, because it only hapenned in Firefox and only certain entities. 
The problem is we used a "bad" default sorter. When you don't want to change the order, you need to send `0`, but we sent `true`, which firefox handles weirdly.
Also, I made it so that we send an update on the services only when the services actually changed
> Fix bug in firefox with services, contracts, etc.

- packages/embark/src/cmd/dashboard/repl.js
Somehow, the dashboard swallowed the errors returned by the repl. So instead, we check for the error and send it as the normal output, but red.
> fix(embark/dashboard): fix dashboard not printing repl errors

- packages/embark-ui/src/components/Blocks.js
- packages/embark-ui/src/components/ExplorerDashboardLayout.js
- packages/embark-ui/src/containers/BlocksContainer.js
- packages/embark-ui/src/reducers/selectors.js
Revise calculations related to block numbers and pagination in the blocks explorer and explorers overview.
Make the number of blocks to display per page configurable and set it to 5 in the explorers overview.
---
Many thanks to @emizzle for his super 🌟 help on putting this together.
> fix(embark-ui): correctly calculate which blocks to display

- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/cmd/dashboard/dashboard.js
- packages/embark/src/cmd/dashboard/monitor.js
- packages/embark/src/cmd/dashboard/repl.js
- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/core/logger.js
- packages/embark/src/lib/modules/console/index.ts
When using the dashboard and putting a command in the cockpit's console or the repl, it put `console $gt;` in the cockpit's console.
So I moved the logging of `console>` directly in the repl, since we only want that when using the repl and also created a new logger function called `consoleOnly` (name can be changed), that only logs to the embark console and not to the cockpit.
> fix(cockpit/console): fix cockpit's console outputting "console >"

- packages/embark-ui/src/scss/coreui-dark.scss
was caused by the dark-theme class not being high level enough
> fix(cockpit/sidebar): fix closed sidebar in the dark-theme

- packages/embark-ui/src/components/Console.js
There is still an issue with the library where if you press Enter on
"Display additional results" and don't navigate around the new options,
it won't update the current option in the underlying state.
It's still, however, a small improvement over what we had before.
> fix: pressing enter on "Display additional results" does the expected thing

- packages/embark/src/lib/modules/console/suggestions.ts
Before, it suggested: `next/n`
Now suggests: `next`
> fix(cockpit/suggestions): fix suggestions with slashes

- packages/embark/src/lib/modules/solidity/index.js
This caused the right tab on the editor to not work on Windows.
So instead of just doing a match, I check with an indexOf, because the path can be not super exact.
> fix(embark/solidity): fix getting the original filename of contracts

- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/modules/ipfs/index.js
- packages/embark/src/lib/modules/storage/index.js
- packages/embark/src/lib/modules/swarm/index.js
This was caused by the race condition fix that went in earlier. If storage was disabled or the storage process died, it hung because we wait for the storage to be ready to build the files.
We still will have the hang if IPFS or swarm crashes, should we still build if it crashes, or add a better message or something else?
> fix(embark/storage): fix hang when storage is disabled

- packages/embark-ui/src/components/Contracts.js
- packages/embark-ui/src/components/ContractsList.js
- packages/embark-ui/src/containers/ContractsContainer.js
- packages/embark-ui/src/utils/presentation.js
Filter silent contracts in the views that display contracts lists rather than with `formatContractForDisplay` because the old approach prevents interaction with a silent contract if a link to it is followed from the blocks or transactions explorer, which is not desirable.
> refactor(embark-ui): filter silent contracts from contracts listings

- packages/embark-ui/src/containers/AccountContainer.js
- packages/embark-ui/src/containers/TransactionsContainer.js
Don't implicitly rely on explorer overview having been loaded to initially populate `entities.transactions`. Also, that container should watch for new blocks/transactions same as the other explorer containers.
Restore `getTransactions` and related to TransactionsContainer. It's no longer the basis of pagination (it didn't work as desired), but when navigating through the transaction pages that action will ensure more transactions are fetched so that the account page will list more of an account's transactions over time. That was a side effect of `getTransactions` before it was removed in favor of `getBlocksFull`, which is still the basis of revised pagination logic in the transactions explorer.
> fix(embark-ui): AccountContainer should get txs for cold load case

- packages/embark-ui/src/actions/index.js
- packages/embark-ui/src/components/Blocks.js
- packages/embark-ui/src/components/ExplorerDashboardLayout.js
- packages/embark-ui/src/components/Transactions.js
- packages/embark-ui/src/containers/AccountContainer.js
- packages/embark-ui/src/containers/TransactionsContainer.js
- packages/embark-ui/src/reducers/index.js
- packages/embark-ui/src/reducers/selectors.js
- packages/embark-ui/src/sagas/index.js
- packages/embark/src/lib/modules/blockchain_connector/index.js
Revise calculations related to transactions and pagination in the transactions explorer and explorers overview.
Make the number of transactions to display per page configurable and set it to 3 in the explorers overview. Display a "No transactions..." message instead of "0" when there are no transactions to display.
Introduce a `blocksFull` prop, action, api, etc. for calculating lists of transactions relative to block objects that contain full transaction objects instead of hash strings (the function backing the blocks endpoint already supports that) and transaction receipts. In the future, the receipts can be used to filter out constructor transactions for silent contracts.
Make pagination display conditional within the blocks explorer, same as in the transactions explorer.
> fix(embark-ui): correctly calculate which transactions to display

- packages/embark-compiler/package.json
Member packages of the monorepo should use caret ranges when specifying other packages in the monorepo as dependencies.
> build(embark-compiler): use a caret range for embark-async-wrapper

- packages/embark-vyper/package.json
Member packages of the monorepo should use caret ranges when specifying other packages in the monorepo as dependencies.
> build(embark-vyper): use a caret range for embark-async-wrapper

- packages/embark/src/lib/core/fs.js
- packages/embark/src/lib/modules/codeRunner/fs.js
- packages/embark/src/lib/modules/codeRunner/index.ts
- packages/embark/src/lib/modules/codeRunner/vm.ts
- packages/embark/src/test/vm_fs.js
When testing production installs of embark 4.0.0-beta.1 (local registry), the `restrictPath` mechanism of `core/fs` was too restrictive, interfering with template generation (cause not completely determined). Also, it's known that `restrictPath` causes problems when resolving plugins, etc. from "higher up" `node_modules` paths, e.g. in the monorepo.
Introduce `codeRunner/fs` which uses `restrictPath` as before, and in `core/fs` remove `restrictPath`. Revise the other `codeRunner` modules to use `codeRunner/fs`.
> refactor(embark): restrict path for fs ops only in VM2 context

- packages/embarkjs/src/blockchain.js
The `runtime_bytecode` is a useful information to remotely check if a smart contract matches our local informations.
This information was present in the configuration provided to the `EmbarkJS.Blockchain.Contract` constructor but was not saved, so we had no way to recover this information from artifacts.
I added three fields to the instance: `bytecode`, `runtime_bytecode` and `real_runtime_bytecode`.
> feat(@embark/embarkjs): add bytecode to contract

- packages/embark/src/lib/utils/transactionUtils.ts
If a transaction is sent and the proxy is enabled, but the function hash (identified in the data of the transaction) is not recognized as a function of the contract (ie does not match a function hash in the contract’s ABI), then embark would crash.
The fix was to introduce error handling in `transactionUtils.getTransactionParams` that defaults the contract name and params to `UNKNOWN`.
The error can be replicated by:
1. Clone https://github.com/mortimr/ethvtx_embark
2. `embark run` the dapp
3. Connect with Metamask
4. Ensure you have enough funds
5. In the “Tx calls” bubble, enter a new value, then click “Set Value”.
6. When the Metamask dialog appears, the error should have already happened. The console shows:
```
embark/src/lib/utils/transactionUtils.ts:58
const functionName = …
```
> fix(@embark/utils): Fix proxy crash with unknown function

- CONTRIBUTING.md
Add more detailed syntax and examples surrounding the commit header and scopes.
> docs(contributing): Update the syntax of the header and scope

- packages/embark/src/lib/modules/codeRunner/index.ts
- packages/embark/src/lib/modules/ipfs/index.js
- packages/embark/src/lib/modules/storage/index.js
- packages/embark/src/lib/modules/swarm/index.js
- packages/embarkjs/src/storage.js
Fix hang when the storage provider (IPFS or Swarm) was started externally before running Embark.
If IPFS/Swarm was already running before `embark run` was run, then the relevant `registerProvider` and `setProvider` code was not being run through the console, and thus the module init event was never fired, preventing the DApp from being built.
This PR refactors the way the IPFS/Swarm process is launched so that the `registerProvider` and `setProvider` code snippets are run through the console in the case of:
* IPFS/Swarm running externally from Embark
* IPFS/Swarm started in a child process by Embark
* Storage is disabled in the DApp config
> fix(@embark/storage): Fix hang when IPFS/Swarm started externally

- dapps/tests/contracts/test/ownable_test.sol
- packages/embark/src/lib/core/config.js
- packages/embark/src/lib/modules/blockchain_connector/provider.js
- packages/embark/src/lib/modules/deployment/contract_deployer.js
- packages/embark/src/lib/modules/solidity/index.js
- packages/embark/src/lib/modules/tests/index.js
- packages/embark/src/lib/modules/tests/solc_test.js
- packages/embark/src/lib/modules/tests/test.js
Contract app hangs when attempting to test the solc contract in the test folder.
There were several causes:
1. The test contract needed a referenced contract path updated
2. Contracts that had been compiled in the JS tests were being deleted at the end of the JS test run, which caused errors with the files not being found. The fix was to reset the contracts config to no longer require the non-test contracts to be compiled/deployed.
3. Contract filtering was attempting to filter on a property `filename` that must have been changed to `originalFilename` at some point and therefore was not filtering properly.
4. The accounts used by the contract deployer were getting overwritten when `SolcTest` was instantiated and thus preventing the `remix_tests` `Assert` library from getting deployed.
> fix(@embark/tests): Fix contracts app hanging

- packages/embark/src/lib/modules/contracts_manager/index.js
- packages/embark/src/lib/utils/solidity/remapImports.ts
Several problems were discovered when investigating why Windows builds on AppVeyor and Azure Pipelines have been failing. This PR fixes them and #1480 will be rebased against this branch to demonstrate the changes work across all platforms.
Compare a contract's `originalFilename` property to a contract file's normalized `originalPath` property instead of `filename`. The `filename` property seems to have been removed.
Detect absolute paths and handle them differently from paths that have not been resolved.
> fix(@embark/contracts_manager, @embark/solidity): compare correct property; handle absolute paths correctly 

- packages/embark-ui/src/actions/index.js
- packages/embark-ui/src/components/ContractsDeployment.js
- packages/embark-ui/src/containers/DeploymentContainer.js
- packages/embark-ui/src/reducers/index.js
- packages/embark-ui/src/reducers/selectors.js
- packages/embark-ui/src/sagas/index.js
- packages/embark-ui/src/services/web3.js
When connected to metamask, and “Injected Web3” is selected on the Deployment page of Cockpit, check to see if contracts have already been deployed or not.
For contracts that have not been deployed, or set to an address in the config, these should now all be re-deployable.
Supports libraries (that have bytecode with `0x73<address><bytecode>`).
> fix(@cockpit/deployment): Check if contracts deployed when connected to MetaMask

- packages/embark/src/lib/modules/debugger/index.ts
During deploy with a failing transaction, embark was crashing due to the variable `line` being passed in as undefined.
Add better error handling to catch this error and prevent embark from crashing.
> fix(@embark/debugger): Add error handling to prevent crash

- packages/embark-ui/src/components/Accounts.js
- packages/embark-ui/src/components/ExplorerDashboardLayout.js
- packages/embark-ui/src/containers/AccountsContainer.js
- packages/embark-ui/src/reducers/index.js
- packages/embark-ui/src/sagas/index.js
Display two accounts per page in the explorer overview. Display ten accounts per page in the accounts explorer page.
Sort accounts by their api-supplied index numbers with the lowest index coming first.
Change the `initBlockHeader` saga so that it triggers a re-fetch of accounts and therefore the "Tx Count" numbers of displayed accounts will reflect increased counts.
Display a truncated account balance if the balance is greater than 20 characters in length. This keeps the "Balance", "Tx Count", and "Index" fields well-aligned in lists of accounts.
In the account details page continue to show the full balance.
> feat(@cockpit/explorer): implement pagination for accounts explorer 

- packages/embark/src/lib/modules/pipeline/index.js
This caused the contract artifacts to be not built when the pipeline is disabled
> fix(pipeline): build contracts even when pipeline is disabled

- packages/embark-ui/src/components/Blocks.js
- packages/embark-ui/src/components/Transactions.js
During work on PRs #1492 and #1494 it became evident that it's not desirable to show pagination controls unless the number of pages is greater than one.
> refactor(@cockpit/explorer): show pagination when num pages > 1

- packages/embark/src/lib/modules/blockchain_process/gethClient.js
- packages/embark/src/lib/modules/blockchain_process/parityClient.js
This will only be enabled for test networks in order to be able to debug
transactions that have occurred in the past.
> fix: run geth in archival mode

- packages/embark-ui/src/components/Contracts.js
- packages/embark-ui/src/components/ContractsDeployment.js
- packages/embark-ui/src/components/ContractsList.js
- packages/embark-ui/src/containers/ContractsContainer.js
- packages/embark-ui/src/containers/DeploymentContainer.js
- packages/embark-ui/src/containers/HomeContainer.js
- packages/embark-ui/src/reducers/index.js
Display five contracts per page in the dashboard. Display ten contracts per page in the contracts explorer and deployment page.
Sort contracts by name. In the future we can implement an option to sort by block number and index within a block by calculating and including that information as part of the server-side api response (based on a contract's txhash).
Remove unnecessary contract filtering in the components since the containers take care of it.
Make use of `listenToContracts` / `stopContracts` in DeploymentContainer.
> feat(@cockpit): implement pagination for contracts

- packages/embark/src/lib/modules/blockchain_listener/index.js
- packages/embark/src/lib/modules/blockchain_process/proxy.js
- packages/embark/src/test/proxy.js
Create a dev tx (a 0-value tx that is sent from the `--dev` account to itself) when a request goes through the proxy, but does not get a response after 5 seconds.
Log requests to the console (when log level is trace - enabled with the embark option `--loglevel trace`) that have not received a response and for which a dev tx has been sent.
Add logging to a `proxyLogs.json` log file as well, so that this information can be gleaned later for debugging purposes.
This particular PR Is meant to workaround an issue with running geth with the `--dev` option, as some transactions appear to get stuck, which then builds up further txs in a queue. Only when another tx is sent is the queue then purged as expected.
The remaining issue is that even though a dev tx is sent to relieve the queued txs, the …
> feat(@embark/proxy): Add dev tx to proxy when request fails to get a response

- CHANGELOG.md
- dapps/templates/boilerplate/CHANGELOG.md
- dapps/templates/boilerplate/package.json
- dapps/templates/demo/CHANGELOG.md
- dapps/templates/demo/package.json
- dapps/templates/simple/CHANGELOG.md
- dapps/templates/simple/package.json
- dapps/tests/app/CHANGELOG.md
- dapps/tests/app/package.json
- dapps/tests/contracts/CHANGELOG.md
- dapps/tests/contracts/package.json
- lerna.json
- packages/embark-api-client/package.json
- packages/embark-profiler/package.json
- packages/embark-specialconfigs/package.json
- packages/embark-ui/CHANGELOG.md
- packages/embark-ui/package.json
- packages/embark-utils/package.json
- packages/embark-webserver/package.json
- packages/embark-whisper/package.json
- packages/embark/CHANGELOG.md
- packages/embark/package.json
- packages/embarkjs-ipfs/package.json
- packages/embarkjs-swarm/package.json
- packages/embarkjs-whisper/package.json
This commit has been originally cherry-picked from d0d89fc5ae4663c27e4b6b5c9cfcf1b47e645d6e and
slightly modified to update all packages, as meanwhile, new packages have been added to `master`.
The reason this commit is cherry-picked from `4.0.x` branch is because
it wasn't created from `master`.
Purpose is mainly to update `CHANGELOG` and get the package versions in sync again.
> cherry-pick: chore(release): 4.0.1

- packages/embark/package.json
Support embarkjs-whisper with external pipeline.
`embarkjs-whisper` is required by code that is through the VM, and therefore the `embark` package needs to be able to resolve `embarkjs-whisper`.
> fix(@embark/pipeline): Support embarkjs-whisper with external pipeline

- packages/embark-ui/src/services/api.js
- packages/embark/package.json
- packages/embark/src/lib/modules/api/server.ts
- yarn.lock
Embark API server's development proxy from port 55555 to 3000 was attempting to inappropriately forward an `/embark-api/` endpoint for the blockchain process logs to Create React App's development server. Why it was only happening for the one endpoint is not known but probably has to do with timing around registration of the API server's express routes.
The problem can be fixed with a one-line `filter:` function in the options for `express-http-proxy`. However, it was realized that to fix an unrelated problem, whereby the proxy doesn't forward websockets to CRA such that hot reload doesn't work when accessing `embark-ui` in development on port 55555, a switch to `http-proxy-middleware` would be required. That was quickly attempted (easy switch) but there are outstanding …
> Refactor API server to use a redirect page instead of proxy, and fix a bug in cockpit

- packages/embark/src/lib/modules/solidity/index.js
- packages/embark/src/lib/modules/solidity/solcP.js
solc 0.4.18 does stuff really weird. Instead of outputting normally like this: 
```
{
"C:/dev/embark_demo/.embark/contracts/zlib2.sol": {
"ZAMyLib2": [
{
"length": 20,
"start": 237
}
]
}
}
```
It looks like this:
```
{
"C": {
"/dev/embark_demo/.embark/contracts/zlib2.sol:ZAMyLib2": [
{
"length": 20,
"start": 233
}
]
}
}
```
Those changes make sure that we structure the output to work correctly
> fix(embark/compiler): fix errors and bugs with solc 0.4.18

- packages/embark/src/lib/modules/blockchain_process/simulator.js
Small bug where if there was blockchain accounts, but none of them was a mnemonic, it would return an empty object that would throw on the next line
> fix(embark/simulator): fix account object empty when no mnemonic

- packages/embark/src/cmd/cmd.js
- packages/embark/src/cmd/cmd_controller.js
**Docs for this feature are ready for release here: https://github.com/embark-framework/embark-site/pull/171**
This commit introduces a feature where users can specify which files should be removed
as part of Embark's `reset` command.
This is done by specifying the `options.reset` section in a project's `embark.json`.
The possible options are `defaults: bool` and `files: Array<String>`:
```
// embark.json
{
...
"options": {
"reset": {
"defaults": true,
"files": ["some.file", "some/other.file"]
}
}
}
```
`defaults` tells Embark whether or not it should remove the default files that are
defined by the `reset` command. Setting it to `false` will prevent Embark from
removing any of these (mostly files located inside `.embark`).
This gives users fine control as they now can re-add subsets or …
> feat(@embark/embark-reset): allow users to specify files to be removed in reset

- packages/embark-specialconfigs/src/index.js
- packages/embark/src/lib/modules/deployment/contract_deployer.js
- packages/embark/src/lib/modules/deployment/index.js
Errors emitted as part of the `deployAll()` routine got swallowed by
Embark, leaving users in the unknown when the deployment process
"froze".
This commit ensures errors emitted are now logged, making it obvious
when something went wrong.
> fix(@embark/deployment): ensure error messages emitted are logged

- packages/embark/src/lib/modules/code_generator/index.js
I had removed EmbarkJS.environemnt by accident when refactoring
> fix(embark/generator): add back environment to EmbarkJS

- packages/embark/src/lib/modules/deployment/index.js
This was a regression introduced in https://github.com/embark-framework/embark/commit/72fc80df53785f802a121f209c3088ad7817e884
> fix(@embark/deployment): only log error when error exists

- packages/embark/src/lib/core/processes/processManager.js
- packages/embark/src/lib/modules/blockchain_connector/index.js
- packages/embark/src/lib/modules/blockchain_process/blockchain.js
- packages/embark/src/lib/modules/blockchain_process/blockchainProcessLauncher.js
- packages/embark/src/lib/modules/blockchain_process/index.js
- packages/embark/src/lib/modules/console/index.ts
Add support for `service blockchain on/off` in the console.
Add `service <process> on/off` command for each process started by Embark, ie `service blockchain on/off` and `service whisper on/off`.
`service blockchain off` - Kills the blockchain process, stops the web3 provider, and shuts down the proxy (if used). In the case of `embark blockchain`, the entire process is exited.
`service blockchain on` - Starts the blockchain process *as a child process of the main embark process* then starts the web3 provider. This happens regardless of whether or not it was initially started with `embark blockchain` (see known issues).
1. If the blockchain process was started with `embark blockchain`, and then the blockchain process is killed with the `service blockchain off` command, when the blockchain …
> feat(@embark/blockchain): Restart Ethereum via command

- packages/embark-process-logs-api/.npmrc
- packages/embark-process-logs-api/README.md
- packages/embark-process-logs-api/package.json
- packages/embark-process-logs-api/src/index.js
- packages/embark-process-logs-api/tsconfig.json
- packages/embark-process-logs-api/tslint.json
- packages/embark/package.json
- packages/embark/src/lib/core/processes/processLauncher.js
- packages/embark/src/lib/modules/blockchain_listener/index.js
- packages/embark/src/lib/modules/embark_listener/index.js
- Move logHandler to embark-utils
- move escapeHtml and normalizeInput to embark-utils (in a new file called log-utils, more functions could go there, but those were the two I needed to move for now)
- Move process-logs-api to a package
> Move process-logs-api to package and more

- packages/embarkjs-ipfs/package.json
- packages/embarkjs-swarm/package.json
- packages/embarkjs-whisper/package.json
Several `embarkjs-*` packages specify a `"test":` script in their respective `package.json` files but lack any tests, causing `yarn test` in the root of the monorepo to fail. For now, disable those scripts.
> test: disable test script for packages without any tests

- packages/embark-webserver/src/index.js
- packages/embark/src/lib/core/processes/processManager.js
Add support for `service webserver on/off` commands.
Deprecate commands `webserver start/stop` in favor of `service webserver on/off`.
Handles passing through of arguments to the function executed after process launch.
`service webserver on` - Enables the webserver serving the DApp. Shows an error if the webserver is already starting or started.
`service webserver off` - Disables the webserver serving the DApp. Shows an error if the webserver is already stopping or stopped.
`webserver start` - This command has been deprecated in favor of `service webserver on` and will be removed in future versions.
`webserver stop` - This command has been deprecated in favor of `service webserver off` and will be removed in future versions.
> feat(@embark/webserver): Add support for `service webserver on/off`

- azure-pipelines.yml
- scripts/coveralls-pr-id.js
Based on [feedback](https://github.com/lemurheavy/coveralls-public/issues/1298#issuecomment-488316379) from the coveralls team, I was also able to include the PR ids of PR builds, which results in type "pull" instead of "push" in the coveralls builds list, along with a handy link to the relevant PR on github.
> ci: on azure pipelines split coveralls and ci:full invocation scripts, run each script conditionally

- packages/embark/src/lib/modules/blockchain_process/parityClient.js
This fix makes Parity work again with `--ws-origins=*,foo`. Apparently,
`*` is already wildcarding anything, so adding things after it will
negate the wildcard effect, making it useless.
I would like some good eyes and potentially to be proven wrong on this
BEFORE we merge this PR, as my understanding of CORS might be wrong
here.
> fix: parity origins

- packages/embark-library-manager/package.json
In the monorepo it works without `colors` specified as a dep, but it's important to specify all dependencies correctly for the sake of production installs.
> fix(@embark/library-manager): specify colors package as a dependency

- packages/embark-api/package.json
In the monorepo it works without `colors` specified as a dep, but it's important to specify all dependencies correctly for the sake of production installs.
> fix(@embark/api): specify colors package as a dependency

- packages/embark-api-client/package.json
- packages/embark-api/package.json
- packages/embark-async-wrapper/package.json
- packages/embark-authenticator/package.json
- packages/embark-compiler/package.json
- packages/embark-contracts-manager/package.json
- packages/embark-core/package.json
- packages/embark-ens/package.json
- packages/embark-graph/package.json
- packages/embark-library-manager/package.json
- packages/embark-logger/package.json
- packages/embark-process-logs-api/package.json
- packages/embark-profiler/package.json
- packages/embark-scaffolding/package.json
- packages/embark-specialconfigs/package.json
- packages/embark-test-runner/package.json
- packages/embark-transaction-tracker/package.json
- packages/embark-typings/package.json
- packages/embark-utils/package.json
- packages/embark-vyper/package.json
- packages/embark-watcher/package.json
- packages/embark-webserver/package.json
- packages/embark-whisper/package.json
- packages/embark/package.json
- yarn.lock
The more recent version of TypeScript works around a [problem][chalk-problem] encountered with the chalk package's type definitions.
[chalk-problem]: https://github.com/chalk/chalk/pull/296#issuecomment-418789492
> build: bump typescript in all relevant pkgs from v3.3.1 to v3.4.5

- packages/embark-api/src/index.ts
- packages/embark-api/src/server.ts
- packages/embark-compiler/src/index.ts
- packages/embark-scaffolding/src/commandOptions.ts
- packages/embark-scaffolding/src/contractLanguage/solidityBuilder/index.ts
- packages/embark-scaffolding/src/framework/reactBuilder/index.ts
- packages/embark-scaffolding/src/index.ts
- packages/embark-scaffolding/src/smartContractsRecipe.ts
- packages/embark-utils/src/longRunningProcessTimer.ts
- packages/embark-utils/src/transactionUtils.ts
- packages/embark/src/lib/core/i18n/i18n.ts
- packages/embark/src/lib/modules/codeRunner/index.ts
- packages/embark/src/lib/modules/codeRunner/vm.ts
We could use similar comments for imports related to other `@types` packages, but the need to do it for `@types/embark` (located in `packages/embark-typings`) seems more pressing since `import ... from "embark"` statements in the monorepo can be so easily misunderstood.
Note that the comments, and indeed the whole lines, are automatically erased during babel transpilation of TypeScript since TS types aren't relevant after the `.js` files are built.
> style: use comments to avoid confusion about @types/embark imports

- packages/embark-core/constants.json
- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/core/processes/processManager.js
- packages/embark/src/lib/modules/blockchain_process/blockchainProcessLauncher.js
- packages/embark/src/lib/modules/ipfs/index.js
- packages/embark/src/lib/modules/ipfs/process.js
- packages/embark/src/lib/modules/storage/storageProcessesLauncher.js
Add support for ability to start and stop IPFS via command `service ipfs on/off`.
Add support for `ProcessState.Errored` process state in the `ProcessManager`. This allows for processes being launched and stopped to trigger an error and the resulting process will be in an errored state. Processes in errored states can still attempt to be started and stopped.
`service ipfs on` - starts an IPFS node if not already started. Shows an error if the node is already starting or started.
`service ipfs off` - kills the running IPFS node as long as Embark has started the IPFS process. If the IPFS process was started externally, an error is shown.
> feat(@embark/storage): Add command `service ipfs on/off`

- site/source/docs/using_the_console.md
There is a typo on Using the console that would confuse newbies.
`await SimpleStorage.method.get().call()<ENTER>` should be `await SimpleStorage.methods.get().call()<ENTER>`
> docs(using_the_console): fix typo of methods call

- packages/embark-ui/src/actions/index.js
- packages/embark-ui/src/containers/TransactionsContainer.js
In addition to introducing improvements per #1492 and #1494, adjust the transactions request action to allow for a `blockLimit` argument, since that API parameter is supported by embark.
Revise `changePage` to invoke `fetchTransactions` correctly, i.e. with arguments pertaining to a starting block number and a block limit.
These changes together fix most of the pagination problems related to exploring transactions, i.e. badly mis-ordered results are no longer displayed.
However, a *wart* still remains related to estimation of the total number of transactions and pages. Sometimes the calculated number of pages for the transactions explorer doesn't match up to the actual number of transactions on the blockchain (owing to estimation). The pagination controls and display of transactions will …
> refactor(@cockpit/explorer): revise transactions explorer per techniques of PRs #1492, #1494

- packages/embark/src/lib/modules/storage/index.js
- packages/embark/src/lib/modules/swarm/index.js
- packages/embark/src/lib/modules/swarm/process.js
- packages/embarkjs-swarm/src/index.js
- packages/embarkjs/src/storage.js
Add support for ability to start and stop Swarm via command `service swarm on/off`.
Fix issue with swarm not starting due to missing web3 object.
`service swarm on` - starts a swarm node if not already started. Shows an error if the node is already starting or started.
`service swarm off` - kills the running swarm node as long as Embark has started the swarm process. If the swarm process was started externally, an error is shown.
Please do not merge until https://github.com/embark-framework/embark/pull/1564 has been merged, at which point I will rebase this with master.
> feat(@embark/storage): Add command `service swarm on/off`

- packages/embark-utils/src/accountParser.js
- packages/embark/src/lib/modules/blockchain_connector/index.js
- packages/embark/src/lib/modules/blockchain_connector/provider.js
I was missing the dappPath and also it used a Buffer key instead of the string key like web3 expects
> Fix privateKey accounts in accountParser

- packages/embark-contracts-manager/src/index.js
- packages/embark-core/src/processes/processWrapper.js
- packages/embark-test-runner/src/index.js
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/cmd/dashboard/repl.js
- packages/embark/src/lib/modules/blockchain_process/blockchain.js
- packages/embark/src/test/accountParser.js
This avoids mistakenly placing process event handlers on the parent process whenever the `embark-core` package is loaded. Also, don't listen for an `'exit'` event on `process` and then call `process.exit(0)` since the event "is emitted after the child process ends" ([docs][docs]), i.e. it's unnecessary to do so and in any case it's not correct to always exit with code `0`.
[docs]: https://nodejs.org/docs/latest-v10.x/api/child_process.html#child_process_event_exit
---
Intended to work together with #1604, though doesn't strictly depend on it.
> fix(@embark/core): move process.on inside ProcessWrapper's constructor

- packages/embark-contracts-manager/src/index.js
- packages/embark-test-runner/src/test.js
- site/source/docs/troubleshooting.md
Add docs on how to troubleshoot interface contract and show a message containing a link to that when that warning appears.
Also, show the warning in tests, because before it didn't appear at all, but only show it if the contract was in configs, because otherwise it would flood the user
> Add warning for interface contracts + docs

- packages/embark-utils/package.json
- packages/embark/package.json
- yarn.lock
This pull-request upgrades `ethereumjs-wallet`, which has upgraded the underlying dependency on scrypt.js to 0.3.0, making scrypt an optional dependency and offering a pure JS version as a fallback.
The reasoning behind this is that scrypt is problematic to install in some systems, particularly those that don't have node-gyp setup and we have seen some weird issues when installing with elevated privileges (i.e. `sudo npm install -g scrypt`)
This is only half the problem, as we have the same issue on `web3-eth-accounts`. They have updated the dependency to point to the behaving version in [b48073](https://github.com/ethereum/web3.js/commit/b4807318cf195686881aa4c791c6fbda76736c5b), but we have to wait on them to cut a new version, and for us to update web3.js to the latest beta.
Ultimately …
> chore: upgrade ethereumjs-wallet

- packages/embark-core/src/processes/processManager.js
- site/source/docs/using_the_console.md
Remove support for `service whisper on/off` because Whisper cannot be started without first disabling it in the communications config, then restarting Embark.
Also remove support for `service embark on/off` because Embark itself should not be able to be started/stopped via command.
These commands were only added a few commits back so it is not considered a breaking change.
Refactor the `service [process] on/off` commands so that there is only one command. Previously we had a command registered for each process, ie:
```
service blockchain on/off
service ipfs on/off
…
```
Now, we only have one command with many options:
```
service [process] on/off - Starts/stops the process. Options: blockchain, embark, ipfs, api
```
Whisper is deliberately not included in the available options for the …
> feat(@embark/whisper): Remove support for `service whisper on/off`

- packages/embark-api/src/index.ts
- packages/embark-api/src/server.ts
- packages/embark-typings/src/logger.d.ts
- packages/embark-ui/src/containers/ContractsContainer.js
- packages/embark-ui/src/containers/HomeContainer.js
- packages/embark-ui/src/containers/ServicesContainer.js
Add support for `service api on/off` commands.
Deprecate commands `api start/stop` in favor of `service api on/off`.
In action (takes a while to load, https://i.imgur.com/ywnARj3.gifv in case it doesn't):
There was some discussion in the #development channel around handling this a bit differently, ie 
> - When command is sent to turn off API service, check if there's an active Cockpit session
> - If yes, invalidate that one first and send a signal to Cockpit to logout (redirect to login page), then turn off the API
> - If no, it's fine, just turn it off
If we feel this is a better way to handle it, then we can either add that functionality in a separate PR, or ditch this PR entirely in favour of that functionality.
`service api on` - Enables the API server serving Cockpit. Shows an error …
> feat(@embark/api): Add command `service api on/off`

- package.json
The demo's `embark.json` relies on the bootstrap package being within the demo's own `node_modules`, but in the monorepo yarn was hoisting it up to the root `node_modules`.
> build: add nohoist entry for bootstrap package relative to dapps/templates/demo

- packages/embark/src/lib/utils/template_generator.js
If the `embark` cli is detected to be inside the monorepo, the template generator yarn-links any template deps that are part of the monorepo into the dapp. However, `embarkjs-connector-web3` now has a dependency on `embark-core`, which in turn has a dependency on `embark-i18n`. That causes `npm install` to fail inside the dapp because npm checks for deps of `embarkjs-connector-web3` relative to the dapp instead of checking relative to the symlink. `yarn install` does not suffer from that behavior so use it instead.
> refactor(@embark/template_generator): use yarn to install template deps if embark cli is in monorepo

- packages/embark-console/package.json
- packages/embark-debugger/package.json
- packages/embark-deploy-tracker/package.json
- packages/embark-listener/package.json
- packages/embarkjs-ipfs/package.json
- packages/embarkjs-swarm/package.json
- packages/embarkjs-whisper/package.json
- packages/embarkjs/package.json
Make the adjustment even if the test script is currently disabled. Consistently use nyc to generate coverage with mocha even if the test script is currently disabled.
> build: adjust reset script to delete coverage dirs if pkg has test script

- packages/embark-pipeline/package.json
- packages/embark-pipeline/src/webpackProcess.js
As part of https://github.com/embark-framework/embark/commit/880a3a69462ee07be17c046f41a50429755fe8e0, we've introduced a
regression where the `colors` package isn't imported in the scope anymore where it's
needed. In this case the pipeline package. This resulted in log output messages
such as:
```
undefinedwriting fileundefined
```
Adding the `colors` package as dependency and importing it accordingly
fixes the issue.
> fix(@embark/pipeline): ensure color methods for logs are available

- packages/embark-ui/src/reducers/selectors.js
With the move of Embark's modules into their own packages, the names under
which they are registered in the API service have changed as well.
This caused Cockpit to no longer being able to properly detect whether
ENS is enabled in the current Embark project
> fix(@cockpit/utils): properly detect if ENS is enabled

- packages/embark-ui/src/services/api.js
When introducing the `embark-api-client` in https://github.com/embark-framework/embark/commit/c1bbdbf34
we didn't properly update Cockpits apiService, resulting in calls to API endpoints
that don't exist.
This commit fixes a bug where calls to Embark's API to subscribe to whisper
channels are in a broken state.
It also updates Cockpit's apiService to no longer pass ignored parameters to embark-api-client.
> fix(@cockpit/whisper): ensure message subscription call is working

- packages/embark-test-runner/src/index.js
When running unit tests inside a project that configures ENS subdomains using Smart Contract directives, the tests will output an error because of that particular Smart Contract's `deployedAddress` being `undefined`.
This happens only when running tests, not when deploying the Smart Contracts including the custom ENS setup.
It turns out that Embark attempts to compile and deploy the Smart Contracts of the project *twice* - once before tests are executed, and another time **after** tests are done executing.
Both compilations/deployments are triggered through our custom `config()` function within test context, which ensures all Smart Contracts are deployed before tests are executed.
This explains a few things:
1. There's no such issue when running `embark run`, in fact the custom ENS …
> fix(@embark/test-runner): don't try to deploy and register ENS domains after JS tests have run

- packages/embark-watcher/package.json
- packages/embark/package.json
- yarn.lock
Upgrade chokidar to a version that's compatible with NodeJS v12.x.
Unfortunately, embark has other transitive dependencies that are not compatible with v12.x, but upgrading chokidar is still a good step.
> refactor(@embark/watcher): upgrade chokidar to 3.0.0

- packages/embark-ui/src/components/ContractOverview.js
> fix(@cockpit/explorer): slice contract function result string only if starts/ends with double-quote

- packages/embark-watcher/package.json
- yarn.lock
chokidar 3.x has fsevents `^2.0.6` [as a dependency][dependency], which introduced node v12.x compatibility, a sought-after goal of our PR #1638. However, fsevents `2.0.6` node compatibility range is quite [complicated][complicated]. After fsevents `2.0.6` was published its maintainers published `1.2.9`, which backports NodeJS v12.x compatibility minus some performance increases, while offering [much more straightforward][straightforward] node compatibility. fsevents `1.2.9` [is compatible][compatible] with the latest v2.x release of chokidar (`2.1.6`). Since Embark advertises runtime compatibility with node `>=8.11.3`, downgrade chokidar to `2.1.6`.
[dependency]: https://github.com/paulmillr/chokidar/blob/3.0.0/package.json#L25
[complicated]: …
> refactor(@embark/watcher): downgrade from chokidar 3.x to latest 2.x

- packages/embarkjs-whisper/src/index.js
When trying to either sending, or listening to whisper channels within
Embark's consoles (CLI and Cockpit), the console outputs an error that
`EmbarkJS` isn't defined.
E.g. running:
```
> EmbarkJS.Messages.listenTo({ topic: ['somechannel'])
```
Outputs:
```
EmbarkJS is not defined
```
This seemed very odd as outputting `EmbarkJS` and all of its members
worked totally fine.
It turns out that both methods, `listenTo()` and `sendMessage()`, in
`EmbarkJS.Messages` are not necessarily what one thinks they are.
EmbarkJS decorates both methods to create some options that need to be
available in the delegate, two of them being `EmbarkJS.Utils.toAscii`
and `EmbarkJS.Utils.fromAscii` (https://github.com/embark-framework/embark/blob/ac76a40a6156603fa436f1fe173835cff5fb0c3d/packages/embarkjs-whisper/s …
> fix(@embarkjs/whisper): don't rely on global EmbarkJS in whisper APIs

- dapps/tests/app/config/storage.json
Fixes #1643 
bzzr was removed in swarm 0.4.0. This change is necessary to this test dapp work with swarm 0.4.0.
> fix(@embark/swarm): update url-scheme to bzz-raw

- packages/embark-deployment/src/contract_deployer.js
- packages/embark-deployment/src/index.js
When deploying some more significant contracts in a test (which uses ganache as the blockchain) we ran into some gas estimation problems.
Namely, Ganache will underestimate gas in some scenarios. On their calculation they [assume a base fee of 21000](https://github.com/trufflesuite/ganache-core/blob/8ad1ab29deccbbb4018f6961d0eb7ec984ad8fcb/lib/utils/gasEstimation.js#L33-L39), where, for contract deployments, the [base fee](https://github.com/ethereum/go-ethereum/blob/d0082bb7ec04b4fe3fc9e269fe2673c9cbd094e2/core/state_transition.go#L83) is [higher (53000)](https://github.com/ethereum/go-ethereum/blob/b8f9b3779fbdc62d5a935b57f1360608fa4600b4/params/protocol_params.go#L32).
This PR doesn't seek to fix gas estimation. Instead, it will estimate the gas to be Ganache's default maximum gas per …
> fix: gas estimates in test

- site/source/docs/installation.md
Unfortunately, markdown syntax isn't properly supported within the
notification tag, so we have to be explicit here.
> docs: fix broken code snippet in installation guide

- packages/embark-code-generator/src/index.js
- packages/embark-library-manager/src/index.js
- packages/embark-solidity/src/index.js
- packages/embark-test-runner/src/solc_test.js
- packages/embark-utils/src/index.js
- packages/embark-utils/src/pathUtils.js
- packages/embark-watcher/src/index.js
- packages/embarkjs-connector-web3/index.js
Long story short, if you have a recursive dep in Solidity, it would still manage to compile, because solc was able to check your inputs and see that the import is in the list of files, but not on Windows, because we used backslahes instead of forward slashes (we import using forward)
> fix(@embark/solidity): fix recursive error on Windows

- dapps/templates/boilerplate/app/index.html
The previous link was pointing to [readthedocs.io](http://embark.readthedocs.io/en/latest/index.html), which wasn't active. 
So here I've replaced it with the link to the [official documentation on the Embark website](https://embark.status.im/docs/quick_start.html).
> fix(@embark/dapps): old link updated to the latest documentation at website

- dapps/tests/app/test/another_storage_spec.js
- packages/embark-test-runner/src/index.js
- packages/embark-test-runner/src/test.js
Based off https://github.com/embark-framework/embark/pull/1663
Puts accounts in the callback of `contract` and `describe`
> Add accounts array to the describe/contract callback

- packages/embark-test-runner/src/test.js
On some Dapps, the number of tests and contracts was so high, that we ended up with `MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 351 data listeners added.` warning.
This is cause each contract created using web3 creates a listener on the `data` event.
However, in the case of tests, contracts are only used in one file at a time, so we can remove the subscription after.
I tried using `removeSubscriptions` that contract objects have, but it ended up trhowing errors and not fixing the problem as it seems broken.
I instead went to the source and called `removeAllListeners`. I make sure that the request manager exists first, so if we ever use another contract instance, it won't crash.
> fix(@embark/test-runenr): fix event listener overflow

- packages/embark-deployment/src/contract_deployer.js
In https://github.com/embark-framework/embark/pull/1119 we've introduced a feature where
users can provide an already compiled ABI for Smart Contracts so they can be used
without the need to compiling them again.
This also means that, internally, those Smart Contract object won't have any
bytecode attached to it.
Later on, in https://github.com/embark-framework/embark/commit/387d33a076cb7a4acd59c212e662f19288498556,  we've introduced a warning
which is rendered when a Smart Contract's bytecode is too large. The check expects
a Smart Contract object to have bytecode associated to it, which will break the code
in cases where a Smart Contract has already an ABI and therefore didn't need compilation.
This commit ensures we only check a Smart Contract's bytecode when bytecode exists for
the …
> fix(@embark/deployment): don't break when using abiDefinitions

- packages/embark-webserver/src/index.js
- packages/embark/src/lib/core/config.js
The webserver's job is to serve files generated by Embark's built-in pipeline,
however, since v4 users can choose they front-end tool to take care of building,
bundling and packing their DApps. Usually these tools come with a built-in
dev server as well.
Therefore, when the pipeline is turned off (which also soon will be the default),
there's not need start a webserver.
> fix(@embark/webserver): don't spin up webserver if pipeline is disabled

- site/themes/embark/languages/en.yml
- site/themes/embark/scripts/docs_paginator.js
Templates used for rendering data inside helpers need to all over their local variables
passed down so they can be evaluated against some context object.
We didn't pass down the i18n `__()` function to the paginator template of our custom
theme resulting in compilation errors during site generation.
This commit fixes it.
> fix(docs): ensure paginator helper has `__()` local

- dapps/templates/boilerplate/test/contract_spec.js
- dapps/templates/simple/test/contract_spec.js
- dapps/tests/app/test/another_storage_spec.js
- packages/embark-test-runner/src/index.js
- packages/embark-test-runner/src/test.js
- site/source/docs/contracts_testing.md
This makes it possible to do this: 
```
contract("AnotherStorage", function() {
const defaultAccount = accounts[0];
```
One weird "hack" I needed to do is call `process.nextTick()`, because otherwise, tests with no `config()` calls would hang for no reason. I was able to put logs everywhere and everythign was called, except the `it`s. So I think it's a bug in Mocha where its event handlers are not set up yet and it waits to do it in a further event loop.
> Wait for `config` to finish before calling `describe`

- site/source/docs/installing_embarkjs.md
- site/source/docs/javascript_usage.md
We still had docs about `EmbarkJS.Blockchain.connect()` and we even had places where we said that `onReady` was deprecated.
So I removed the `connect` parts and added back or put higher the `onReady`
> chore(@embark/site): remove connect() doc and add back onReady

- packages/embark-blockchain-connector/src/provider.js
This PR adds a command to get full account details from the contradts config that includes info like private key.
The existing, and similar command, `blockchain:provider:contract:accounts:get` would only return account addresses if they existed, and not the full account info.
This is required to support obtaining private keys for signing purposes, as needed in the current state of the [`embarkjs-plasma`](https://github.com/embark-framework/embarkjs-plasma) plugin.
> feat(@embark/embark-blockchain-connector): Add command to get full account info

- packages/embark-contracts-manager/src/index.js
- packages/embark-solidity/src/index.js
When running with `loglevel=debug` you will now get more information about an error in solidity
Useful for internal errors, because solidity otherwise doesn't output much information
Also made it so that we print all errors before exiting.
> fix(@embark/solidity): show a better error message in debug

- packages/embark-code-runner/src/index.ts
- packages/embark-typings/src/embark.d.ts
The property is set/available on EmbarkJS in the artifacts, i.e. in a browser build; but sometime since v3.2.4 it was no longer availble in the cli dashboard environment.
> fix(@embark/code-runner): restore EmbarkJS.environment property in the cli dashboard

- packages/embark-blockchain-connector/src/index.js
- packages/embark-ui/src/components/Blocks.js
- packages/embark-ui/src/components/Transactions.js
- packages/embark-ui/src/containers/TransactionsContainer.js
- packages/embark-ui/src/utils/presentation.js
Adjust the API endpoints to augment transaction objects with a timestamp property from their corresponding blocks. This removes the necessity to copy the timestamp property from a block to its transactions in the client.
Introduce a `formatTimestampForDisplay` util function in Cockpit for consistently transforming timestamps into relative or absolute dates, depending on whether a date is sometime during the last day.
> fix(@cockpit/explorers): consistently display "Mined on" timestamps

- packages/embark-console/src/lib/index.ts
This fixes a bug where if you have `embark console` connected via IPC to `embark run`, getting an object that contains functions via the console would return an empty object. That's because flatted, the library we use to `stringify`, removes it because of possible circular dependencies.
Only problem with my fix is it doesn't fix getting `SimpleStorage`, ie the `methods` param would still be empty, but doing `SimpleSotrage.methods` works.
~~I tried fixing this by doing a recursive function, but it couldn't handle circular dependencies and I ended up making the choice to make a simple yet flawed solution instead of a complex but complete one, because the result is not worth the cost IMO. Tell me if you think otherwise.~~
Fixed by using util.inspect for the data
> fix(@embark/ipc): transform functions as string before stringify

- packages/embark-blockchain-connector/src/index.js
- packages/embark-deployment/src/contract_deployer.js
- packages/embark-deployment/src/index.js
When running tests against non-simulated blockchain nodes, even for simplex
Smart Contracts, deployment transactions would exceed the block gas limit.
E.g. running `embark blockchain` in one process and `embark test --node embark`
in another, inside our demo application, will throw an error when Embark attempts
to deploy its `SimpleStorage`:
```
Compiling contracts
Compilation done
[SimpleStorage]: error deploying =SimpleStorage= due to error: Returned error: exceeds block gas limit
Error deploying contracts. Please fix errors to continue.
Error deploying contracts. Please fix errors to continue.
terminating due to error
Error deploying contracts. Please fix errors to continue.
```
The reason for that is because in https://github.com/embark-framework/embark/pull/1650, we've introduced a …
> fix(@embark/deployment): don't over estimate gas when running tests against non-simulator nodes

- packages/embark-contracts-manager/src/index.js
- packages/embark-ui/package.json
- packages/embark-ui/src/components/ContractOverview.js
- packages/embark-ui/src/constants.js
- packages/embark-ui/src/utils/utils.js
- packages/embark-utils/src/constants.ts
- yarn.lock
For payable methods inside of the contract interatction section of cockpit, the value input has been updated to pass wei to the API. The input field now accepts value like `100 ether` or 25 szabo`. The value entered is automatically converted to wei and shown to the user in real time.
Additionally, the input is validated for a correct value, with an error shown to the user for incorrectly entered values.
A tooltip has been added to help the user enter correct values.
UI updates can be seen in video here: https://monosnap.com/file/642cHH2HxDeiFLzB2VLqHP9GuqoRfz
> feat(@cockpit): Pass tx value as wei and add validation

- packages/embark-code-generator/src/index.js
- site/source/docs/plugin_reference.md
Plugins that used the `contractGeneration ` api only affected the console and had no way of changing the embark artifacts, hence no way of affecting the contracts used in the Dapp.
Now, using `contractGeneration` plugins changes the result in the artifacts and in the console both.
> Fix contractGeneration plugins

- packages/embark-ui/src/components/ContractOverview.js
We've introduced a regression in https://github.com/embark-framework/embark/commit/536a4029ba1f544c8050c42eefeb439ff028f2f9 where the default
`value` sent to payable Smart Contract methods is `-1`, resulting in errors as it's not
a valid value.
In fact, this value is sent to all methods called through Cockpit, breaking also non-payable methods.
> fix(@cockpit): don't send invalid value to Smart Contract methods

- packages/embark-test-runner/src/reporter.js
In https://github.com/embark-framework/embark/commit/87d92b6091 we've introduced a feature in our test runner
to report exact gas costs used when calling Smart Contract methods that
cause computation.
Embark keeps a list of deployed contracts in memory and for all transactions
happening during tests, it'll match them to the contracts that performed them
to produce the report logs.
Unfortunately, we've been [resetting that memory](https://github.com/embark-framework/embark/commit/87d92b6091#diff-92b4f79a0473160fe700440b1ced5204R140) of deployed contracts
after every test, making it practically impossible for Embark to find
matching contracts for any transactions, because contracts aren't necessarily
redeployed per spec, resulting in no additional transaction logs whatsoever.
This commit …
> fix(@embark/test-runner): make `--tx-details` option work again

- packages/embark-ipfs/src/upload.js
This was caused by IPFS returning the total MBs uploaded in the stderr instead of stdout.
So instead of looking at  stderr for errors, look at the code first.
> fix(@embark/ipfs): fix ipfs upload with wrong error message

- dapps/templates/boilerplate/config/contracts.js
- dapps/templates/demo/config/contracts.js
- dapps/templates/simple/contracts.js
- packages/embark-pipeline/src/index.js
- site/source/docs/contracts_configuration.md
Adds `minimalContractSize` option in contract config to reduce the size of the files.
Fixes https://github.com/embark-framework/embark/issues/1712
Name of the option can change
> Add option to contract config to reduce size of contracts

- dapps/tests/app/test/token_spec.js
- packages/embark-test-runner/src/index.js
Discovered while running tests in Teller after updating to the latest 4.1 beta.
The tests would pass as `0 tests passed`. 
This was due to the fact that Teller has `describe` inside `describe`, which is a totally valid thing to do.
The problem is that evaluating those `describe`s is sync, but our code that waits for the `config()` to be finished is async. Even if the `config` already finished, the `setImmediate` makes it so that Mocha thinks there are no more tests because we don't call  `run` in the same loop.
The solution in this PR is not super pretty, but it works. Basically, if we see that `global.embark`(test.js) is ready, we don't wait for `onReady`, because otherwise, Mocha will skip the tests, so we call `global.run()` straightaway.
This leads to the other ugly fix, I need to run …
> fix(@embark/test-runner): fix describe in describe tests

- packages/embark-blockchain-connector/src/provider.js
- packages/embark-blockchain-process/src/proxy.js
~~This is most definitely a WIP.~~
Main points:
`eth_accounts` and `personal_listAccounts` do exactly the same things in geth's source code (see [here](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L193) and [here](https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L222) in the same file; parity should be reviewed too) and therefore `web3.eth.getAccounts()` and `web3.eth.personal.getAccounts()` are the same thing. The web3 docs website is not up-to-date and the published docs are misleading and incorrect. Compare these:
https://web3js.readthedocs.io/en/1.0/web3-eth.html#getaccounts
https://github.com/ethereum/web3.js/pull/2124
So `getAccounts()`, either `eth` or `personal`, simply returns a list of accounts controlled by the node.
What …
> refactor(@embark/blockchain): consistently merge config accounts and node accounts

- packages/embark-pipeline/.babelrc.js
- packages/embark-pipeline/src/webpackProcess.js
When passing the name of a build pipeline that doesn't exist, e.g. `embark run|build --pipeline foo`, `writeStats` would cause an unhandled promise rejection because its `config` argument is falsy. Checking for that and returning early from `writeStats` allows the `"no webpack config has the name 'foo'"` error to be reported correctly.
-------
Also fixed in this PR: the ignore paths for the default webpack config and babel-loader-overrides helper script weren't properly adjusted after the legacy pipeline was split-out into its own package in the monorepo.
> fix(@embark/pipeline): check if config arg of writeStats is falsy

- packages/embark-library-manager/src/index.js
A check is already in place in `package/embark-web3` but `installAll` of the library manager needs the same.
> fix(@embark/library-manager): add a check/warning for `"1.0.0-beta"` web3 version in installAll

- packages/embark/src/lib/utils/template_generator.js
Previously, when using "development embark" (i.e. `embark` command in the monorepo) the template generator would always use `yarn install` to install a template's dependencies. However, if a template relies on `package-lock.json`, as is the case for `embark-create-react-dapp-template`, that behvaior can cause serious problems. So, have the choice of install command depend not only on whether we're using "development embark" but also whether the template has a `package-lock.json` file.
NOTE: this change can probably result in problems given that `yarn install` and `npm install` behave differently re: symlinks in `node_modules`. However, such problems would never show up with production installs of the `embark` packaage. Moreover, after dropping `embarkjs-connector-web3` we don't presently …
> refactor(@embark): template generator should use npm if downloaded template has package-lock.json

- packages/embark-blockchain-listener/src/dev_txs.js
- packages/embark-blockchain-process/src/proxy.js
- packages/embark-core/constants.json
DApps generated with `new --simple` don't have a blockchain config so ensure that the blockchain proxy and listener (dev_txs) use appropriate provider settings when setting up web3.
Without these changes, in a fresh `embark new --simple` project the `embark blockchain` command will encounter unhandled promise rejection with respect to the proxy; `embark run` will encounter the same with respect to dev_txs.
> refactor(@embark/blockchain): support --simple dapps

- packages/embark-contracts-manager/package.json
- packages/embark-contracts-manager/src/contract.ts
- packages/embark-contracts-manager/src/index.js
- packages/embark-deploy-tracker/src/deploymentChecks.js
- packages/embark-deploy-tracker/src/index.js
- packages/embark-deploy-tracker/src/trackingFunctions.js
- packages/embark-deployment/src/contract_deployer.js
- packages/embark-deployment/src/index.js
- packages/embark-typings/index.d.ts
- packages/embark-typings/src/contractsConfig.d.ts
- packages/embark-typings/src/logger.d.ts
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/index.js
Add back contract tracking to the refactored code. Deployment checks are added as plugins to the `embark-deployment` module.
Adds ability to track if a contract has already been deployed, and skips deployment if so.
Updates error handling flow for deployment process.
Adds a contract class to the `embark-contracts-manager`, to add a `log` function for the contract. This `log` function can be called from any module that has the contract instance.
Adds TS interfaces for contracts configuration.
Handles the following cases:
1. Contract already deployed
2. Contract not deployed
3. Contract is configured with `{track: false}` (deploy if not deployed, and don't track)
5. Contract is configured with an `address` in the config
6. `trackContracts` set to `false` from `engine` (always deploy but …
> refactor(@embark/embark-deploy-tracker): Add back contract tracking

- packages/embark/src/cmd/cmd_controller.js
This commit refactors the `build` command to use the newly refactored
event APIs.
> refactor(@embark/cmd): make build command work again

- packages/embark-deploy-tracker/src/index.js
This is another fix for using Ganche with the --fork option.
This time, a user was trying to use ganache with the --fork option with mainnet. Somehow, no block functions work (I tried getBlock and getBlockNumber and they both return`invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type common.Hash`)
This just puts an error, but it continues.
The real fix would be to not start the deploy-tracker in the tests, but since we are already refactoring all of this in v5, I didn't feel like doing it in v4.1 was worth it.
> fix(@embark/deploy-tracker): continue if getting block fails

- packages/embark-contracts-manager/src/contract.ts
- packages/embark-contracts-manager/src/index.js
- packages/embark-deploy-tracker/package.json
- packages/embark-deploy-tracker/src/deploymentChecks.js
- packages/embark-deploy-tracker/src/index.js
- packages/embark-deploy-tracker/src/test/deploymentChecksSpec.js
- packages/embark-deploy-tracker/src/test/trackingFunctionsSpec.js
- packages/embark-deploy-tracker/src/trackingFunctions.js
- packages/embark-deployment/src/contract_deployer.js
- yarn.lock
Add unit tests for the contract tracking `embark-deploy-tracker` package.
`trackingFunctions` was refactored in a way to make it more testable and now performs tracker file IO on demand, as opposed to being executed for each contract deploy. Additionally, removed any synchronous file IO in favour of their asynchronous counterparts.
Added special case for config contract-level tracking:
when `contract.track === false` in contracts config, contracts are deployed, then the config is changed `contract.track` is truthy, a special use case is presented, and the chains.json file is updated accordingly.
NOTE: This branch is based on `refactor_5_0_0`.
> feat(@embark/embark-deploy-tracker): Add unit tests

- packages/embark-transaction-tracker/src/index.js
- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/modules/blockchain/api.ts
- packages/embark/src/lib/modules/blockchain/index.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/api.js
Branched off @emizzle's great API refactor. This adds back the gas oracle API, because otherwise it was impossible to use the contracts pages where there were transactions (`send`s)
Also fixed a small error in the API, see line 18 and others for api.ts.
The plugins were never set so the API never returned.
Just repeating, this merges in @emizzle's branch whch in turn, is based off refactor_5_0_0
> Make gas oracle API work again and fix small API problems

- packages/embark-deployment/src/contract_deployer.js
- packages/embark-specialconfigs/src/index.js
- packages/embark-web3/src/index.js
- packages/embark/src/cmd/dashboard/dashboard.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/index.js
Contract artifacts were not being generated nor run through the VM if the contracts/interfaces were not deployed. These features were executed as actions on the `deployment:contract:deployed` event.
This PR runs executes the same actions for `deployment:contract:undeployed` event as the `deployment:contract:deployed` event, which occurs when a contract is not deployed.
> fix(@embark/embark-deployment): Undeployed contract artifacts

- packages/embark-accounts-manager/src/index.ts
- packages/embark-contracts-manager/src/index.js
- packages/embark-transaction-tracker/src/index.js
- packages/embark-typings/src/embark.d.ts
- packages/embark-ui/src/components/Contracts.js
- packages/embark-ui/src/components/ContractsDeployment.js
- packages/embark-ui/src/components/ContractsList.js
- packages/embark-ui/src/containers/EditorContainer.js
- packages/embark-ui/src/sagas/searchSaga.js
- packages/embark-ui/src/utils/presentation.js
- packages/embark/package.json
- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/modules/blockchain-client/index.js
- packages/embark/src/lib/modules/blockchain/api.ts
- packages/embark/src/lib/modules/blockchain/index.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/api.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/index.js
- yarn.lock
APIs for Cockpit have been re-added.
The bulk of the work is split in to two parts
1. Contracts APIs (in `embark-contracts-manager`) have been refactored a bit to add status codes to most responses (`express` is deprecating responses without status codes)
2. Remainder of the blockchain APIs and commands have been refactored so that they are registered in the blockchain stack component (`lib/modules/blockchain`), which is agnostic to the blockchain-specific implementation. The low-level implementation methods have been abstracted out from web3 by way of this registration. It is the job of the `ethereum-blockchain-client` (plugin) to register the API methods and command functions, which -- being ethereum -- can use `web3` in the methods.
There is an event `blockchain:reset` that was used in …
> refactor(@cockpit): Re-add APIs

- packages/embark-deploy-tracker/src/deploymentChecks.js
- packages/embark-deploy-tracker/src/test/deploymentChecksSpec.js
- packages/embark-solidity/src/index.js
This was caused by two factors:
1. We didn't check the contract's bytecode, so as soon as we had an address, we assumed it was deployed, but it often could be the old address
2. The bytecode didn't change, because the prepare script for contracts modified the `contractFile` object, so the path of the contract files became the `.embark/` one.
- fixed by deep cloning the contrractFiles object.
> fix(@embark/deploy-tracker): fix contract always re-deploying

- packages/embark/src/cmd/cmd_controller.js
I tried using RxJS, but I couldn't find a way to have a timeout like the one we have right now and as before. That timeout is useful to throttle instantaneous file changes, like using an IDE that enables to change and save multiple files at once. Without that throttle, it would start the pipeline for each file modified, but with it, it runs only once for all.
> refactor(@embark/cmd-controller): re add cargo for file watcher

- packages/embark-deploy-tracker/src/index.js
- packages/embark-deploy-tracker/src/test/deploymentChecksSpec.js
- packages/embark-deploy-tracker/src/test/trackingFunctionsSpec.js
- packages/embark-deploy-tracker/src/trackingFunctions.js
There was an error that would display on the second+ run of embark, that was causing by trying to read JSON of an empty file.
The solution was a combination of ensuring the file existed with defaults when enabled, and also ensuring we await the saving of the file.
Included is a bit of a refactor of how the tracking functions handled the “current chain”. Hopefully, this should make things more clear.
Tests have been updated accordingly.
> fix(@embark/embark-deploy-tracker): Fix reading of empty file

- packages/embark-contracts-manager/src/index.js
- packages/embark-deployment/src/index.js
- packages/embark-specialconfigs/src/functionConfigs.js
- packages/embark-specialconfigs/src/index.js
- packages/embark-utils/src/index.js
- packages/embark/src/cmd/cmd_controller.js
- site/source/docs/contracts_configuration.md
This commit introduces a new Smart Contract configuration addressHandler
that lets users define a function to "lazily" compute the address of the
Smart Contract in question.
This is useful when a third-party takes care of deploying a dependency
Smart Contract, but the address of that Smart Contract only being available
at run-time.
Example:
```
deploy: {
fromIndex: 0,
args: [100],
},
OtherContract: {
deps: ['SimpleStorage'],
address: async (deps) => {
// use `deps.contracts.SimpleStorage` to determine address
},
abiDefinition: ABI
},
}
```
In the example above, OtherContract will be deployed after SimpleStorage
because it uses the deps property to define Smart Contracts that it depends
on. All dependencies are exposed on the addressHandler function parameter
similar to …
> feat(@embark/specialconfigs): introduce dynamic addresses

- dapps/templates/demo/test/simple_storage_spec.js
- packages/embark-mocha-tests/package.json
- packages/embark-mocha-tests/src/lib/index.js
- packages/embark-proxy/src/index.ts
- packages/embark-proxy/src/proxy.js
- packages/embark-test-runner/src/index.js
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/lib/core/configDefaults.js
- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/modules/blockchain/index.js
- packages/embark/src/lib/modules/ganache/index.js
- packages/embark/src/lib/modules/geth/index.js
Makes it possible to change the change blockchain node from test to test, but defaults to the Ganache VM.
Based off https://github.com/embark-framework/embark/pull/1846
> Enable changing node from test to test

- packages/embark-proxy/src/index.ts
- packages/embark-proxy/src/proxy.js
- packages/embark-utils/src/index.js
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/modules/blockchain/index.js
- packages/embark/src/lib/modules/geth/blockchain.js
- packages/embark/src/lib/modules/geth/index.js
- packages/embark/src/lib/modules/parity/index.js
Fixes the `embark blockchain` command and also makes it so the running command check if the blockchain is already up before starting a node on itself.
The ping endpoint used there and for the proxy has also been changed to using web3 and checking with a basic rpc call (eth_accounts).
This was changed because our implementation of pingEndpoint was really limited and didn't work correctly for `ws` and especially not `wss`.
> Fix embark blockchain command + fix wss in Embark

- packages/plugins/solidity-tests/src/test/runner_test.js
When an options object is not supplied the tests fail because the constructor expects the options argument to be an object, i.e. referencing `options.plugins` should not cause a TypeError.
> test(@embark/plugins/solidity-tests): supply mock options object to SolidityTestRunner constructor

- packages/embark/src/lib/modules/ethereum-blockchain-client/api.js
- packages/embarkjs/embarkjs-whisper/src/index.js
- yarn.lock
Use our own object instance by giving it the existing provider instead
of fishing out private properties inside the `web3` instance.
> chore: refactor requestManager use

- package.json
- packages/core/typings/src/plugins.d.ts
- packages/stack/compiler/README.md
- packages/stack/compiler/package.json
- packages/stack/compiler/src/index.ts
- yarn.lock
This supports in v5 how `embark-snark` needs to hook into contracts compilation but is implemented in a generic way that can be made use of by any plugin.
To see it in use have a look at https://github.com/embark-framework/embark-snark/pull/2, more specifically:
https://github.com/embark-framework/embark-snark/pull/2/files#diff-1fdf421c05c1140f6d71444ea2b27638R43.
> feat(@embark/compiler): support :before and :after hooks on event compiler:contracts:compile

- packages/plugins/snark/.npmrc
- packages/plugins/snark/README.md
- packages/plugins/snark/babel.config.js
- packages/plugins/snark/package.json
- packages/plugins/snark/src/index.js
- packages/plugins/snark/test/index.js
- yarn.lock
Includes changes to make it compatible with upcoming Embark v5.x. Note that with those changes the plugin is no longer compatible with Embark v4.x.
> refactor(@embark/plugins/snark): add embark-snark package to the monorepo

- packages/core/console/src/test/console.js
- packages/core/inside-monorepo/index.js
- packages/core/inside-monorepo/package.json
- packages/core/utils/index.d.ts
- packages/core/utils/package.json
- packages/core/utils/src/index.js
- packages/core/utils/src/monorepo.js
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/lib/core/services_monitor.js
- packages/embark/src/lib/utils/template_generator.js
- packages/stack/api/src/server.ts
This PR implements `embark-utils` APIs for detecting whether the running embark is inside the monorepo, calculating the monorepo's root path, and locating packages within the monorepo.
It also includes changes to the template generator and the API server that make use of the new `embark-utils` functions.
It also includes, in separate commits, some small fixes/refactors discovered while working on this PR.
There may be be various scripts in our codebase that still implement *ad hoc* monorepo detection and/or related logic with relative paths. I hunted around as best I could, and made adjustments as needed, but more may be needed in the future.
> feat(@embark/utils): "inside monorepo" APIs

- packages/stack/communication/test/communication.spec.js
- packages/utils/testing/src/lib/embark.js
- packages/utils/testing/src/lib/index.js
This also makes `fakeEmbark` configurable
> test(@embark/commmunication): add test for artifact generation

- packages/core/utils/src/logHandler.js
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/lib/modules/blockchain/index.js
- packages/embark/src/lib/modules/geth/blockchain.js
When you didn't have the blockchain client installed or put in a bad path to the bin, it would hang.
Especially in `embark run`, you wouldn't even have the message.
That was because the log handler was looking at `msg.type` instead of `msg.logLevel` to check if it's an error. 
I'm not sure where `type` comes from, but I added a condition so that both `type` and `logLevel` work now.
Now, if the client doesn't exist, it will exit and users will get a message
> Fix process logs not showing on errors and fix hang on wrong client

- dapps/templates/boilerplate/config/contracts.js
- dapps/templates/boilerplate/config/storage.js
- dapps/templates/demo/config/contracts.js
- dapps/templates/demo/config/storage.js
- packages/plugins/web3/src/index.js
Putting `client: vm` didn't work, because the web3 module only listened to `on('blockchain:started')` after an async call.
> Fix VM as a client and cleanup template configs

- packages/embark/src/lib/modules/ethereum-blockchain-client/api.js
- packages/stack/proxy/src/proxy.js
The proxy was outputting logs about an error in request. That's because we were asking for a block with a number smaller than 0.
> fix: fix error logs in the cockpit due from negative blocks numbers

- packages/embark/src/lib/modules/geth/whisperClient.js
- packages/embarkjs/whisper/src/index.js
Fix whisper node start (at least on Windows) by putting `--ipcdisable` because ipc is not needed for whisper and also, it made it so that the Whisper node didn't start correctly.
Also, remove the callback from the `send` function in EmbarkJS for Whisper, as it's not needed and also, we can use the promise instead
> Fix whisper callback and start

- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/lib/core/config.js
- packages/embark/src/lib/modules/embark-embarkjs/embarkjs-artifact.js.ejs
- packages/embark/src/lib/modules/embark-embarkjs/index.js
- packages/stack/proxy/src/index.ts
Move loading of plugins to after core and stack components (in cmd_controller).
We should load custom Embark plugins LAST (ie after all core and stack components, and after all Embark plugins). To do this, we disable automatic loading of plugins in the config, and allow them to be loading explicitly in cmd_controller.
Create a system that allows registration of custom EmbarkJS plugins. Each plugin is generated in EmbarkJS by instantiating the registered class. For example, we can register a Plasma plugin and it will be generated in to EmbarkJS.Plasma with an instantiation of `embarkjs-plasma`. The DApp itself can then do what it wants with `EmbarkJS.Plasma` (ie call `EmbarkJS.Plasma.init()`.
**NOTE:** loading of custom Embark plugins needs to be applied to all other commands in …
> refactor(@embark/embarkjs): Support for custom EmbarkJS plugins

- packages/stack/communication/test/communication.spec.js
In https://github.com/embark-framework/embark/commit/d6bf5c24b92c0d1a8bc7c0a28a0432e033d72e74 we've ensured that certain modules of
embark only executed if their functionality is actually enabled.
This broke one of our tests in the communication module.
This commit fixes the test by explicitly enabling the module's functionality.
> test(@embark/communication): fix failing test

- packages/stack/test-runner/package.json
- packages/stack/test-runner/src/lib/index.js
- packages/stack/test-runner/src/lib/reporter.js
- packages/stack/test-runner/src/test/test_runner_test.js
Introduce some light refactoring related to embark-testing facilities, and also a configurable stdout option so the output of the reporter implemented in this package isn't confusingly mixed into unit test reporting for this package.
> test(@embark/stack/test-runner): enable test-runner's test suite

- packages/embark/src/lib/utils/template_generator.js
If the version in the embark package's own `package.json` has a prerelease identifier then appending `.x` to the major version isn't viable for resolving the latest version of the template package that's in the same prerelease line; a more complex semver range must be used:
```
"${pkg}@^${major}.${minor}.${patch}- <${major}.${minor}.${patch}"
```
> refactor(@embark/template_generator): account for prerelease in embark version

- packages/embark/src/lib/core/engine.js
Running embark's `blockchain` command resulted in a runtime error where the `blockchain`
module couldn't be found. This is a bug introduced in https://github.com/embark-framework/embark/commit/ed0d3afb4ff11520e4a73d1318d1269c2e994c06 where
we forgot to update `blockchainStackComponents` in Embark's engine accordingly.
Fixing this results in `embark blockchain` hanging. This is because there's a similar bug
in `blockchainStackCopmnonents` introduced in https://github.com/embark-framework/embark/commit/3b8f8f9ea74a5c90d3a2c4a635b7b82841ff073f.
This commit fixes both bugs by ensuring `embark-blockchain` and `embark-blockchain-client`
packages are loaded using the correct APIs.
> fix(@embark/core): make blockchain command work again

- packages/plugins/ens/src/index.js
- packages/plugins/geth/src/check.js
- packages/plugins/parity/src/check.js
This error was caused because the test app has `.eth` names in it's onDeploys, but when using an environment different than development, ENS was not registered (no rootDomain, etc), so the resolve threw without a catch.
Now, it checks for the ENS contract before trying to resolve.
Also found a weird problem when the Geth version call didn't return a result, so now it will handle it
> Fix cb already called in test app

- packages/embark/src/cmd/cmd.js
Example: `embark rest && embark run`
The command/s following `&&` shouldn't run after the first one fails and prints an "unknown command" message.
> refactor(@embark/cmd): exit with error when command is unknown

- packages/plugins/transaction-logger/src/index.js
This caused logs like:
```
Blockchain> Resolver.unknown(unknown) | 0xb5b9c95cc268158ec3221265c7a1011f71928c50af07721b0e04beed1e0af782 | gas:46946 | blk:11 | status:0x1 │
│ Blockchain> SimpleStorage.unknown(unknown) | 0x80257c5b6cb5b4f3f1f638e01dd85a8d30e0cc005cb04d075a81c57c7bfe6e72 | gas:26661 | blk:19 | status:0x1 │
```
It happened because the cockpit fetches transaction data, which calls `eth_getTransactionReceipt`, which is a method the transaction-logger reacts to.
The thing is, it should only  react to receipts that are attached to transactions, not receipts that come from normal GETs
> fix(@embark/transaction-logger): don't show logs for stray receipts

- yarn.lock
Embark's `yarn.lock` was pointing to es-abstract@1.14.0 but that's problematic because that version was unpublished (in the allowed time window). Some of the npm/yarn registry servers/mirrors (and cloudflare's cache) do make that version's tarball available for download but not all of them, apparently.
> build(deps): bump yarn.lock to pickup es-abstract@1.16.0

- dapps/tests/app/app/contracts/BFC.sol
- dapps/tests/app/config/contracts.js
- packages/plugins/ethereum-blockchain-client/package.json
- packages/stack/blockchain-client/src/index.js
- packages/stack/proxy/package.json
- packages/stack/proxy/src/proxy.js
This is a patch we had back in the day to fix big payloads when using WS providers.
It's because of a bug in Geth, it would not understand big payloads from web3, because it was split.
Increasing the threshold makes it so that the big payloads are not split
> fix: fix ws providers to have the patch for a bigger threshold

- site/source/docs/using_the_console.md
As discussed in #2008, the `service on/off` command in Embark's interactive console
is non-functioning. As solving the root of the problem requires a bit more effort
than anticipated, we've decided offline to remove this command for the time-being.
The functionality is already gone, this commit removes the corresponding docs.
> docs: remove docs for `service` command

- packages/plugins/ethereum-blockchain-client/src/api.js
We've introduced a regression in https://github.com/embark-framework/embark/commit/f9557d4c9 where invalid data
has been sent to web3's `ecRecover()` method to verify signed messages.
This causes an internal server error and the utility feature inside Cockpit
unsuable.
This commit ensures that the correct data is sent to `ecRecover()` making verifying
messages through Cockpit functional again.
> fix(@embark/cockpit): ensure correct data is send to web3's `ecRecover`

- packages/plugins/geth/src/index.js
- packages/plugins/solidity/src/solcP.js
- packages/plugins/solidity/src/solcW.js
There were 2 issues:
- The IPC was connected, but the compiler was not loaded in the blockchain node, so the calls to the IPC hung
- There was a request with an `await`, so it needed `request2`
> Fix embark test with --node

- packages/core/code-runner/src/index.ts
- packages/core/console/src/lib/index.ts
- packages/embark/src/cmd/dashboard/repl.js
In the embark cli dashboard/console, if you were to type `Foo.` and hit tab for autocomplete then (assuming you hadn't defined `Foo`) there would be unhandled errors and the console could even become unusable.
Refactor `packages/core/console` and related code so that nothing happens when you attempt to autocomplete a bad reference (the same behavior as Node's own REPL).
> refactor(@embark/core/console): silence errors when autocomplete is attempted on bad reference

- dapps/tests/app/test/another_storage_spec.js
- packages/embark/src/lib/core/plugin.js
- packages/embark/src/lib/core/plugins.js
- packages/embark/src/test/plugins.spec.js
- packages/plugins/accounts-manager/src/index.ts
- packages/plugins/web3/src/index.js
- site/source/docs/plugin_reference.md
Those are problems that were found while testing Teller with the new V5 release.
The priority was added because, with the refactor, for the event `deployment:contract:deployed`, multiple actions are fired at the same time in a "random" order that could cause a race condition where the `onDeploy` hooks could fire before the registrations in the VM, making some contracts fail to use their own Contract object.
The fund account issue is because we can't call multiple TXs in parallel on the node, otherwise we have nonce issues. IE all transactions will have the same nonce because they are sent at the same time.
I added tests for the respective fixes and features
> Add priority to registerActionsForEvents and fix funding accounts

- .eslintrc.json
- dapps/templates/boilerplate/embark.json
- dapps/templates/demo/embark.json
- dapps/tests/app/embark.json
- dapps/tests/contracts/embark.json
- package.json
- packages/core/console/suggestions.json
- packages/core/i18n/locales/en.json
- packages/core/i18n/locales/es.json
- packages/core/i18n/locales/fr.json
- packages/core/i18n/locales/pt.json
- packages/core/i18n/locales/sl.json
- packages/embark/src/lib/core/config.js
- packages/embark/src/lib/core/configDefaults.js
- packages/embark/src/test/config.js
- packages/embark/src/test/contracts.js
- packages/stack/library-manager/src/index.js
- site/source/docs/configuration.md
- site/source/docs/storage_configuration.md
BREAKING CHANGE:
Remove support for specifying the versions of `web3` and `ipfs-api` in a project's `embark.json`.
> refactor(@embark/library-manager): restrict versionable packages to only solc

- packages/plugins/geth/src/blockchain.js
The `WhisperGethClient` returns empty strings for its "new account" and "list accounts" commands; if a command is an empty string then `Blockchain` should not execute it.
> refactor(@embark/plugins/geth): don't run empty commands

- packages/plugins/geth/src/gethClient.js
- packages/plugins/geth/src/whisperClient.js
This PR is in a draft state at the moment because I'm not 100% sure how to best scope the commit — feat, perf, build, refactor?
Also, since embark only prints a warning re: geth versions that are older than the minimum supported version, should this be considered a breaking change or not?
> feat(@embark/plugins/geth): bump min supported geth version from 1.8.14 to 1.9.7

- dapps/tests/app/config/contracts.js
- packages/plugins/ens/src/index.js
This commit fixes the issue that it wasn't possible anymore to use named constructor arguments
in Smart Contract configurations.
For example, the following Smart Contract expects two constructor arguments:
```solidity
contract SomeContract {
constructor(address[] _addresses, int initialValue) public {}
}
```
The first being a list of addresses, the second one a number. This can be configured as:
```js
SomeContract: {
args: [
["$MyToken2", "$SimpleStorage"],
123
]
}
```
Notice how the order of arguments matters here. `_addresses` come first in the constructor,
so they have to be defined first in the configuration as well.
Another way to configure this is using named arguments, which is what's broken prior to this commit:
```js
SomeContract: {
args: {
initialValue: 123,
_addresses: …
```
> fix(@embark/ens): don't change shape of Smart Contract args in action hooks

- dapps/tests/app/test/embarkJS_spec.js
- dapps/tests/app/test/namesystem_spec.js
- dapps/tests/app/test/token_spec.js
- dapps/tests/contracts/ens.json
- dapps/tests/contracts/test/another_storage_spec.js
- packages/embark/src/cmd/cmd_controller.js
- packages/plugins/ens/package.json
- packages/plugins/ens/src/index.js
- packages/plugins/mocha-tests/src/lib/index.js
- packages/stack/embarkjs/src/index.js
- packages/stack/namesystem/src/index.js
- packages/stack/test-runner/src/lib/index.js
With this, you can now change, per test, the ENS config. That way, you could have the root domain be `embark.eth` in test A, and in test B, the root domain could be `testb.eth`.
For storage and communication, you can start them too, but only at the start of the tests, using the config file with the `test` environment. I tied enabling the ability to change those per test, but it's way more painful, because there is an actual node that needs to stop
> Enable modules in tests

- packages/core/utils/package.json
- packages/embark/package.json
- yarn.lock
A benefit of this upgrade is that, owing to a bugfix in `ora@3.0.0`, in CI we'll see the output (minus spinner) from library manager when downloading solc for `dapps/tests/app` and `dapps/tests/contracts`.
I made sure to test everything is working fine on both Windows and macOS when using the `--nodashboard` option for `embark run` (i.e. should see the spinner re: basic pipeline) and when doing `embark test` (i.e. should see the spinner re: library manager).
> build(deps): bump ora from 2.1.0 to 4.0.3

- packages/plugins/geth/src/index.js
- packages/plugins/parity/src/index.js
- packages/stack/blockchain/src/index.js
The blockchain module should not contain any ethereum-specific code, and currently it contains a check to see if the blockchain has already been started.
This PR moves this check to blockchain client (ie geth or parity). This check function is registered along with the started callback.
> refactor(@embark/blockchain): Move check for blockchain started

- site/themes/embark/layout/layout.swig
This adds a script for site analytics we added to https://status.im/ recently(https://github.com/status-im/status.im/pull/396).
You can read about it here:
https://our.status.im/implementing-fathom-analytics-on-marketing-websites/
> add Fathom Analytics JS to the site

- packages/cockpit/ui/src/components/Console.css
- packages/cockpit/ui/src/components/Console.js
- packages/core/core/src/engine.ts
- packages/plugins/profiler/package.json
- packages/plugins/profiler/src/gasEstimator.js
- packages/plugins/profiler/src/index.js
Hook `embark-profiler` into the engine's contracts group.
Adjust `request` signatures to match v5 usage.
Ensure gas numbers are formatted consistently in the ascii table.
Display non-json output in cockpit's console as monospace/pre to preserve profiler table formatting.
> refactor(@embark/plugins/profiler): re-enable embark-profiler plugin

- dapps/templates/demo/app/components/storage.js
- dapps/tests/app/app/index.html
- packages/core/code-runner/src/vm.ts
- packages/embark/package.json
- packages/embarkjs/ipfs/package.json
- packages/embarkjs/ipfs/src/index.js
- packages/plugins/ipfs/package.json
- packages/plugins/ipfs/src/index.js
- yarn.lock
BREAKING CHANGE:
Related to #1985. Prior to Embark's minimum supported version of Node.js being bumped to 10.17.0, Embark was incompatible with any relatively recent release of the `ipfs-http-client` package.
While *internal* changes are needed re: ipfs's `Buffer` export for e.g. `embark_demo` to function correctly *(and this PR makes those changes)*, Embark otherwise runs/tests okay.
Keep in mind #2033.
However, if a dApp author were to explicitly `require('ifps-api')` in the front-end that wouldn't work as before; and swapping `"ipfs-http-client"` for `"ipfs-api"` might also not be enough — there are API changes that dApp authors would need to consider, regardless of Embark presently supplying the dependency and EmbarkJS wrapping around it.
> build(deps): bump deprecated ipfs-api@17.2.4 to ipfs-http-client@39.0.2

- packages/cockpit/ui/package.json
- packages/cockpit/ui/src/components/Console.js
- packages/cockpit/ui/src/services/api.js
- packages/stack/library-manager/package.json
- packages/stack/library-manager/src/index.js
The problem was that the Whisper component checks if the Web3 version is high enough (supported), but when we removed the support for changing the web3 version in `versions`, it no longer was there for Cockpit to see.
> Fix whisper component in the cockpit

- dapps/tests/app/app/contracts/expiration.sol
- dapps/tests/app/test/expiration_spec.js
- packages/stack/test-runner/src/lib/index.js
Improve the reliability of the expiration unit test in the test dapp by explicitly setting the `block.timestamp` and comparing an expiration value against that.
This improves on the current implementation that relies on time passed which varies depending on the speed of unit tests run (CPU speed, logs shown, etc).
> fix(@embark/tests): Improve expiration unit test

- packages/plugins/geth/src/blockchain.js
- packages/plugins/geth/src/blockchainProcessLauncher.js
When whisper was being started in a new process, the message displayed in the console was “Starting Blockchain node in another process”. This is misleading as it is the same message that geth/parity use to start up their processes.
Update whisper initialisation process messaging so it states “Starting Whisper node in another process”.
> chore(@embark/whisper): improve whisper startup logging

- packages/embark/src/cmd/simulator.js
When using websockets, the simulator was starting on port `8545` instead of `8546`, so the blockchain check was failing.
Update the simulator port to be websockets port from the config when using websockets.
> fix(@embark/simulator): fix port used in simulator

- packages/plugins/rpc-manager/src/lib/eth_signData.ts
- packages/plugins/rpc-manager/src/lib/index.ts
This is actually not a WIP but a `fix`.
Let's wait for #2050 to land first. This one then needs rebase.
Thanks @michaelsbradleyjr for helping implementing this!
> fix(@embark/rpc-manager): implement missing RPC modifier for eth_sign

- packages/embarkjs/ipfs/package.json
- packages/embarkjs/ipfs/src/index.js
- packages/plugins/ipfs/package.json
- packages/plugins/ipfs/src/index.js
- yarn.lock
Refactor constructor call in light of breaking change in the release notes:
https://github.com/ipfs/js-ipfs-http-client/releases/tag/v40.0.0
> Multi parameter constructor options are no longer supported
> build(deps): bump ipfs-http-client from 39.0.2 to 40.0.0

- packages/plugins/whisper-geth/src/blockchain.js
- packages/plugins/whisper-geth/src/blockchainProcessLauncher.js
- packages/plugins/whisper-geth/src/whisperGethClient.js
Fix issue where Whisper logs were printed twice because it had the same name as the blockchain, so the event to listen to process logs was registered twice. Just needed to change the name.
Fix Windows issue where the Whisper Geth node was conflicting with the main blockchain node over the IPC. Reason is that on Windows, the IPC link is made through a pipe file on disk. Changing that would mean to only change it on Windows, so it would be a pain. Instead, just putting `ipcdisable` in the Whisper node fixes it, and IPC is not really needed for Whisper anyway.
> Fix to Whisper Geth node issues

- dapps/templates/boilerplate/config/communication.js
- dapps/templates/demo/config/communication.js
- packages/core/core/src/config.ts
Client traffic with the communication provider node, e.g. a whisper node, is not proxied so make the default port 8547 instead of 8557. It's not a technical problem for it to be 8557, but our convention to present has been for 855* ports to be proxied while the upstream is an 854* port.
Update the boilerplate and demo templates to match.
> refactor(@embark/core): make 8547 the default port of communication provider node

- packages/core/core/src/engine.ts
- packages/embark/src/cmd/cmd_controller.js
`Engine.startEngine(cb)` potentially exits the current process if
any registered plugins emits an error in the bootstrap phase.
This limits consumers of this API to react accordingly. Embark's APIs
should be considered library APIs that propagate errors, but let callers
decide what to do with them.
This commit ensures we keep propagating the error of `startEngine()` without
exiting the current process.
> fix(@embark/core): don't exit in Engine consumer API

- packages/core/core/package.json
- packages/embark/package.json
It is unnecessary and not a good idea for `packages/embark` to provide dependencies to other monorepo packages via any kind of transitive dependency relationship. In this case, `embark` depended on `embark-core` and `embark-core` needs `embark-whisper-*` packages but it's `embark` that supplies those packages indirectly. It works out in the monorepo, *probably* in production too, but we need to move away from that pattern completely.
> refactor(@embark/core): spec embark-whisper-* as deps of embark-core instead of embark

- dapps/templates/boilerplate/config/pipeline.js
- dapps/templates/demo/config/pipeline.js
- packages/embark/src/cmd/cmd.js
- site/source/_posts/2019-03-18-upgrading-to-embark-4.md
- site/source/docs/create_project.md
- site/source/docs/embark_commands.md
- site/source/templates/index.md
- site/themes/embark/layout/templates.swig
Add `--template` deprecation notices to the site and documentation.
More deprecation notices in other repos:
1. https://github.com/embark-framework/embark-vyper-template/pull/2
2. https://github.com/embark-framework/embark-typescript-template/pull/8
3. https://github.com/embark-framework/embark-vue-template/pull/5
4. https://github.com/embark-framework/embark-angular-template/pull/4
5. https://github.com/horyus/ethvtx_embark/pull/1
6. https://github.com/embark-framework/embark-bamboo-template/pull/2
7. https://github.com/embark-framework/sggc/pull/2
> chore(@embark/site): Add `—template` deprecation notice.

- packages/core/core/src/engine.ts
- packages/core/utils/src/network.ts
- packages/plugins/solidity/src/solcW.js
- packages/plugins/whisper-geth/src/blockchain.js
- packages/plugins/whisper-geth/src/blockchainProcessLauncher.js
- packages/plugins/whisper-geth/src/whisperGethClient.js
- packages/stack/blockchain/src/index.js
- packages/stack/proxy/src/index.ts
- packages/stack/test-runner/src/lib/index.js
Fix conflict in ports when Embark is already running
Fix using --node for the tests. Makes it work and also uses the Embark compiler correctly over IPC
> Fix test running with another Embark instance running

- dapps/templates/demo/app/dapp.js
- packages/embarkjs/embarkjs/src/lib/blockchain.js
- packages/embarkjs/embarkjs/src/lib/index.js
- packages/plugins/ens/src/index.js
- packages/plugins/web3/src/index.js
- packages/stack/blockchain/src/index.js
- packages/stack/deployment/src/index.js
- packages/stack/embarkjs/src/index.js
- packages/stack/pipeline/src/index.js
Users can turn of blockchain support if they want to using the `blockchain.js`
configuration. In practice however, this has never properly worked as several
places in Embark's codebase weren't actually honoring that configuration value.
This commit introduces the necessary changes so that disabling blockchain support will:
- No longer generate blockchain related EmbarkJS artifacts
- No longer try to deploy Smart Contracts but still compile them
> fix(@embark/blockchain): make disabling blockchain feature work

- packages/embark/src/cmd/cmd_controller.js
DApp plugins were already been setup to load last for run and test. This PR sets updates `console`, `build`, `graph`, and `upload` to do the same.
> chore(@embark/core): Set DApp plugins to load last

- packages/plugins/geth/package.json
- packages/plugins/geth/src/devtxs.ts
- packages/plugins/geth/src/index.js
- packages/plugins/geth/tsconfig.json
- packages/plugins/geth/tslint.json
Add back DevTxs.
DevTxs sends a zero-value tx to push through any pending txs that may get stuck with geth while in `—dev` mode.
Converted the legacy code in to typescript.
> chore(@embark/geth): Add back DevTxs

- packages/plugins/ens/package.json
- packages/plugins/ens/test/index.js
As part of https://github.com/embark-framework/embark/pull/2110/commits/8ed5376533b5a165e478f5f12ca74230c33beb7a we made `ENS.getEnsConfig()`
asynchronous, hence it needs a callback. This change was not done in one of the
ENS tests, resulting in the test to fail. The test mocked that particular API,
turning it into noop, which is why the test kept timing out.
This commit fixes the test by not mocking the API and adding the needed configuration
to the environment.
> fix(@embark/ens): fix broken test due to async API

- packages/plugins/coverage/package.json
- packages/plugins/ens/package.json
- packages/plugins/ens/test/index.js
- packages/plugins/mocha-tests/package.json
- packages/plugins/solidity-tests/package.json
- packages/stack/communication/package.json
- packages/stack/deployment/package.json
- packages/stack/deployment/test/deployment.spec.js
- packages/utils/testing/package.json
It's a relevant `package.json` if the package has a test suite. If `test` isn't specified then the tests won't run in CI (they have't been running).
Include a fix for one failing test in `packages/plugins/ens` and two failing test in `packages/stack/deployment`. In all three cases, the mock embark object's config needed a `blockchainConfig` section with `{ enabled: true }`.
> build: specify missing test action in relevant package.json "qa" scripts

- packages/embarkjs/embarkjs/src/lib/blockchain.js
- packages/embarkjs/embarkjs/src/test/blockchain.js
- packages/embarkjs/embarkjs/src/test/helpers/blockchain.js
Changes the connection check to `getNetworkId` because using `getAccounts` was not a good idea because of EIP1102.
Basically, in Status, if the user didn't give access to his wallet, `getAccounts` returns an error, which EmbarkJS interprets as a faulty connection.
When using `dappAutoEnable: false`, this triggered the error straight away
NB: this merges in https://github.com/embark-framework/embark/pull/2133
> fix(@embark/embarkjs): use getNetworkId to test connection

- packages/core/core/src/config.ts
- packages/embarkjs/embarkjs/src/lib/blockchain.js
- packages/embarkjs/embarkjs/src/test/blockchain.js
- packages/embarkjs/embarkjs/src/test/helpers/blockchain.js
- packages/plugins/geth/src/check.js
- packages/plugins/geth/src/index.js
- packages/plugins/parity/src/check.js
- packages/plugins/parity/src/index.js
- packages/plugins/rpc-manager/src/lib/eth_accounts.ts
- packages/plugins/rpc-manager/src/lib/rpcModifier.ts
- packages/plugins/whisper-geth/src/check.js
- packages/plugins/whisper-geth/src/index.js
- packages/stack/proxy/src/index.ts
Long story short, we did not support connecting to HTTPS and WSS urls at all for the nodes. Also, just anything not localhost was not very supported
As you'll see, I had to duplicate the fix 3 times for Geth, Parity and Whisper... Maybe we could reopen the conversation about abstracting some of that.
> Fix connecting to an external node

- packages/core/engine/src/index.ts
Since https://github.com/embark-framework/embark/commit/ee56f3771389a00e019eadce595dcf30468f0afe, any deployment hook that
was using simple `console.log()` statements to output information, would result in
unexpected `[[object object], [object object]]`.
Unfortunately, the reason for that was that we switched from non-arrow functions to
arrow functions [here](https://github.com/embark-framework/embark/commit/ee56f3771389a00e019eadce595dcf30468f0afe#diff-a7c4cef8bfebeb39fcd092aca5570fecL324-L340). Usually switching from non-arrow functions to arrow functions solves
a lot of lexical scope issues where the current reference of `this` isn't pointing at the
right thing.
We're tempering with the global `console.log` inside Embark, which then, combined with
**proper** lexical scope, causes the …
> fix(@embark/engine): ensure deployment hook logs don't produce unexpected output

- packages/embark/src/cmd/dashboard/dashboard.js
- packages/stack/contracts-manager/src/index.js
This fixes a bug that redeployment of contracts has not been properly
reflected in the cockpit contract list.
The reason for that was that it's listening for a websocket API that
only updates when the `contractsState` event has been emitted.
The commit ensures `contractsState` is emitted during dedicated deployment
events.
> fix(@cockpit/contracts): ensure contract state is emitted in realtime

- dapps/tests/contracts/contracts.json
- packages/embarkjs/ens/src/index.js
During `embark test`, the contracts dapp was throwing an error:
```
connection not open on send()
Error: Invalid JSON RPC response: ""
at Object.InvalidResponse (/Users/michael/repos/embark/node_modules/web3-core-helpers/src/errors.js:42:16)
at XMLHttpRequest.request.onreadystatechange (/Users/michael/repos/embark/node_modules/web3-providers-http/src/index.js:92:32)
at XMLHttpRequestEventTarget.dispatchEvent (/Users/michael/repos/embark/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
at XMLHttpRequest._setReadyState (/Users/michael/repos/embark/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
at XMLHttpRequest._onHttpRequestError (/Users/michael/repos/embark/node_modules/xhr2-cookies/xml-http-request.ts:379:8)
at ClientRequest.<anonymous> …
```
> fix(@embark/dapps): Contracts app test failure

- packages/plugins/mocha-tests/src/lib/index.js
- packages/plugins/rpc-manager/src/lib/eth_signData.ts
- Fix account management in tests so that contracts have the right `from` address and have a basic `gas` value (that value is relatively arbitrary, I'm not sure what we used to have, but I had to add this value for tests to work)
- Fix the sign data rpc call so that it compares addresses correctly, other wise, it didn't detect that accounts were part of the Node
> Fixes so that the tests in Teller work

- packages/core/utils/src/accountParser.js
- packages/plugins/rpc-manager/src/lib/eth_accounts.ts
- packages/plugins/rpc-manager/src/lib/index.ts
Was caused by the fact that each rpc-modifier got its own node
accounts, but once the eth_accounts modifier is enabled, the
"node" accounts are always going to contain the custom accounts too
Now, the node accounts are set once eth_accounts is initiated, so
that every modifier is on the same page
Also implement a second layer of protection to make sure that if a
duplication happens, it is gotten rid of
> fix(@embark/rpc-manager): fix duplicated accounts in rpc manager

- CHANGELOG.md
The release of v4.2.0 was done from the `4.2.x` branch, so it's necessary to add it manually.
---
**QUESTIONS**
In the [comparison view](https://github.com/embark-framework/embark/compare/v4.1.1...v4.2.0) of v4.1.1 with v4.2.0 there were 46 `CHANGELOG.md` files updated.
So in this kind of situation, where a release was done from a branch other than `master`, do we think it's important to manually add all the changelog entries to their respective changelog files in `master` (if the package exists in `master`), or is it satisfactory to add only the root changelog entry?
Also, is it better to put the entry for 4.2.0 at the top or should it be situated between the entries for 4.1.1 and 5.0.0-alpha.0? There's a date included in the first line of each changelog entry, so I'm guessing it's …
> docs: add CHANGELOG.md entry for v4.2.0 into master

- packages/embark/src/cmd/cmd_controller.js
- packages/plugins/transaction-logger/src/index.js
The transaction-logger was slowing down tests because each Tx, it
would read a file and write to it, but that's slow and even got
slower as the file grew bigger
To fix, I removed the Tx-logger from text, along with the profiler
as they are useless for tests
> fix(@embark/tests): fix slow embark test because of the tx-logger

- packages/stack/embarkjs/src/index.js
Fix misspelling in event name. This event is new to v5, so there is no deprecation or major version bump needed.
> fix(@embark/embarkjs): Fix event name misspelling

- packages/embark/package.json
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/tsconfig.json
- packages/plugins/scaffolding/src/framework/reactBuilder/index.ts
- packages/plugins/scaffolding/src/framework/reactBuilder/templates/dapp.js.hbs
- packages/plugins/scaffolding/src/framework/reactBuilder/templates/index.html.hbs
- packages/plugins/scaffolding/src/index.ts
This is a best effort WIP PR to get `embark-scaffolding` operational for embark v5, prior to holidays.
With these changes in place, `embark scaffold ...` does work, but there are some limitations and things to be aware of, so that's why the PR is in draft status.
**NOTES**
`embark-scaffolding` is removed from `packages/embark/package.json` since it's actually loaded by `packages/core/engine` and therefore is a dependency of the latter. There are a few more `embark-[*]` dependencies in `packages/embark/package.json` that can likewise be moved to engine, but that can be handled in a future PR.
I aimed for the bare minimum `engine.registerModuleGroup()` calls needed to make scaffold work, and I think I succeeded. It would be nice if the following logger output could be suppressed as it's not …
> WIP: refactor so that embark-scaffolding can be used in embark v5

- packages/plugins/snark/package.json
- packages/stack/compiler/src/index.ts
- yarn.lock
If using `embark-snark` in the dapp's plugin, and the dapp doesn’t have any contracts, the `embark-snark` plugin would not simply exit early and essentially do nothing.
Fix `embark-snark` plugin so that it will run its routine regardless of whether or not the dapp has contracts or not.
Bump `circom` and `snarkjs` to their latest patch version.
> fix(@embark/snark): Allow dapp to have no contracts

- packages/plugins/transaction-logger/src/index.js
Transaction logs for contracts that were unknown to Embark (ie not in the dapp) would often log super large unformatted objects (filling the terminal), making the information logged hard to read without actually being that useful. In addition, occasionally the object logged would throw the error `TypeError: Converting circular structure to JSON`.
Set the log level for transaction logs that are not from a known contract to `debug`, so that they do not flood the terminal with often unused information.
Use `util.inspect` to print the transaction log instead of `JSON.stringify` to prevent circular structure errors.
> fix(@embark/transaction-logger): Circular JSON log and unknown contract log level

- packages/plugins/debugger/src/index.ts
Null check to prevent an error during automated debugging for failed transactions.
> fix(@embark/debugger): Prevent error if contract not tracked by Embark

- dapps/tests/app/test/expiration_spec.js
- packages/plugins/mocha-tests/src/lib/index.js
- packages/stack/test-runner/src/lib/index.js
This commit introduces a new `global.evmClientVersion` that can be used to
conditionally run tests, such as when tests rely on RPC APIs that are only
available in specific evm nodes.
> feat(@embark/test-runner): expose evmClientVersion for conditional tests

- dapps/tests/app/test/simple_storage_spec.js
When using `embark test —node=embark` with the test app, the test that listens for contract events would always fail after timing out. Funnily enough, after the timeout, the subsequent test would run, executing a method that would ulimately fire the event listened for in the previous test, causing the second test to fail as well.
Update the contract events listener test in the test app to execute the `set2` method twice, successfully working around the issue.
1. The cause of the issue is unknown and how workaround solves the problem is also unknown.
2. This change works with both `embark test` and `embark test —node=embark`.
3. There are two other tests that fail when using `--node=embark` that will be fixed in https://github.com/embark-framework/embark/pull/2169.
> fix(@embark/tests): Fix failing test with `—node=embark`

- site/source/docs/migrating_from_3.x.md
New guide for breaking changes in v5. I might have forgotten stuff, please let me know.
We'll also later need an article for the release, because this guide is more about the breaking changes and doesn't cover all new features
> docs(@embark/site): add migration guide to Embark v5

- packages/core/utils/package.json
- packages/core/utils/src/accountParser.js
- packages/embark/package.json
- yarn.lock
See: https://github.com/embark-framework/ethereumjs-wallet/releases/tag/v0.6.4
See also: https://www.npmjs.com/package/@embarklabs/ethereumjs-wallet?activeTab=versions
The primary difference is that `ethereumjs-wallet@0.6.3` is depdendent on a version of `scrypt.js` that has the [older `scrypt`][old-scrypt] package as an optional depdendency; whereas `@embarklabs/ethereumjs-wallet` depends on [`@web3-js/scrypt-shim`][web3-scrypt] (authored by @michaelsbradleyjr), which checks for the availability of [Node's built-in scrypt KDF][builtin-kdf] (Node.js `>= 10.5.0`) and uses that, or else falls back to a pure JS implementation provided by the `scryptsy` package.
[old-scrypt]: https://github.com/barrysteyn/node-scrypt
[web3-scrypt]: https://github.com/web3-js/scrypt-shim
[builtin-kdf]: …
> build(deps): replace ethereumjs-wallet@0.6.3 with @embarklabs/ethereumjs-wallet@0.6.4

- packages/core/core/src/config.ts
- packages/core/core/src/plugin.ts
- packages/core/engine/src/index.ts
- packages/core/utils/src/check.js
- packages/core/utils/src/index.ts
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/test/config.js
- packages/plugins/ethereum-blockchain-client/src/index.js
- packages/plugins/geth/src/blockchain.js
- packages/plugins/geth/src/index.js
- packages/plugins/nethermind/.npmrc
- packages/plugins/nethermind/README.md
- packages/plugins/nethermind/package.json
- packages/plugins/nethermind/src/blockchain.js
- packages/plugins/nethermind/src/blockchainProcess.js
- packages/plugins/nethermind/src/blockchainProcessLauncher.js
- packages/plugins/nethermind/src/index.js
- packages/plugins/nethermind/src/nethermindClient.js
- packages/plugins/nethermind/tsconfig.json
- packages/plugins/whisper-geth/src/blockchain.js
- tsconfig.json
Add Nethermind client plugin to enable using Nethermind instead of Geth.
Works completely with dev mode. Did quick tests for testnet and mainnet just to see if it starts, but didn't wait until full sync.
Works in standalone and in-process.
There is still some stuff that can be improved on it, but it can be done during the later refactor of blockchain plugins.
To create this plugin, I copied the Parity one and saw that a lot of stuff is either useless or not done correctly (same applies for Geth).
I had to fix some modules like deployer and the plugin class, because Nethermind has some small issues, but it shouldn't regress any other plugin.
> Nethermind plugin

- packages/embark/package.json
- packages/plugins/transaction-logger/src/index.js
- yarn.lock
Doing read, then write each a trasaction or call exectues could get
heavy, especially with regular txs on
This was especially true in the tests, which led to deactivate the
tx logger in the tests
Instead of reading the whole file, adding the JSON line a writing,
we instead just append some pseudo JSON to it that later gets read
and parsed correctly back to JSON
> refactor(transaction-logger): replace log file write by append

- dapps/tests/app/test/token_spec.js
- packages/embarkjs/ens/src/ENSFunctions.js
- packages/embarkjs/ens/src/index.js
- packages/plugins/ens/src/index.js
- packages/stack/embarkjs/src/index.js
Fixes the use of Infura to connect to the ENS contracts. When
connecting directly to Infura, it would throw with `rejected due to
project ID settings`, because it doesn't accept the VM as the domain
Instead, when passing from the proxy, it works. So I changed the
default when no dappConnection to ['$EMBARK']. I also added a
message when the error happens to help users fix it themselves
When in the testnet, we don,t register because we already have the
addresses, which is fine, but we also didn't populate the ensConfig
object which contains the important information about the addresses
and ABI.
There was a lot of lint problems in a couple of files so I cleaned
that up
> fix(@embark/ens): fix Infura connection and testnet use of ENS

- packages/embarkjs/embarkjs/src/lib/blockchain.js
- packages/embarkjs/embarkjs/src/lib/messages.js
- packages/embarkjs/embarkjs/src/lib/names.js
- packages/embarkjs/embarkjs/src/lib/storage.js
- packages/stack/embarkjs/src/embarkjs-artifact.js.ejs
The goal of this pr is to:
* support not specifying an embarkjs plugin if it's not being used
* warn users when attempting to do use a plugin and it's missing
> fix(@embark/embarkjs): support not needing embarkjs plugins defined

- .github/workflows/nightlies.yml
That is, the file `${HOME}/.npmrc` will be deleted by the "Remove NPM credentials" step even if a previous step failed.
---
I noticed that step didn't run when *Nightlies/release* recently failed, but it's a good idea for it to always run.
> ci: adjust Nightlies/release job so NPM credentials are always removed

- packages/embarkjs/embarkjs/src/lib/blockchain.js
- packages/embarkjs/ens/src/index.js
- packages/plugins/ens/src/index.js
- packages/plugins/ens/test/index.js
When we introduced dappConnection to ENS, we didn't add the concept
of auto connection, like we do in the "normal" connection. This
means that when using $WEB3, the contracts connection waited for
the user to click on a button, but the ENS part called `ethereum.enable`
directly, which is confusing for the dev, because we specified to
NOT automatically connect to ethreum.
This fixes it by checking the dappAutoEnable property in contracts
config and adds it to the namesystemConfig artifact
> fix(@embark/ens): connect to web3 only with dappAutoEnable is true

- dapps/tests/contracts/test/simple_storage_spec.js
- packages/embark/package.json
- packages/plugins/ganache/package.json
- yarn.lock
Bumped `ganache-cli` from version `6.7.0` to `6.8.2`.
Also, in `dapps/tests/contracts` move the `this.timeout(0);` inside the `it(...)` for the expensive gas esimation (involving `SimpleStorage.methods.set`) because it otherwise doesn't seem to have an effect on the default 15 second timeout.
@richard-ramos this one's for you!
---
Before committing, I checked the test dapps work and that `embark run` works in a fresh `embark_demo` with `embark simulator` running in another terminal.
> build(deps): bump ganache-cli from 6.7.0 to 6.8.2

- packages/stack/proxy/src/index.ts
i recently updated to embark 5.0 im having issues connecting to a local node each time i connect to it i get the following output from the embark console
```
Error during proxy setup: Port should be >= 0 and < 65536. Received 754510.. Use '--loglevel debug' for more detailed information.
```
This is what i have under the blockchain.js  file
```
localDev: {
endpoint: "http://127.0.0.1:7545",
accounts: [{
nodeAccounts: true,
}]
}
```
The port to start the proxy on is incremented by a constant value (using the `+` operator), however the port comes from the config and in the case where it is a string, the `+` operator acts as a string concatentation.
Ensure the port from the config is always parsed to a number before attempting to add the constant proxy port offset.
> fix(@embark/proxy): Parse `rpcPort` from config as integer

- packages/cockpit/ui/src/actions/index.js
- packages/plugins/transaction-logger/src/index.js
Changes the way the logs are stored to straight up be logged as an array and then reads it as such
It also removes the reverse from the read and puts it in the UI instead since it's the UI that needs it reversed.
Once merged, this needs the old log file to be deleted from `.embark`, since the structure is different. (`embark reset` does the job)
🚀
> refactor(@embark/transaction-logger): change log storage and read

- packages/embarkjs/embarkjs/src/lib/blockchain.js
Some ethereum providers (e.g. Opera implementation) do not return the accounts array in the `enable` call.
Fixed initialization errors on Ethereum-enabled DOM environments that do not return an array of accounts in the `enable` method.
Modified `Blockchain.enableEthereum` to get the accounts explicitly after a successful `ethereum.enable` call, keeping the promises chain.
> fix(@embark/embarkjs): change enableEthereum to not rely on returned accounts array

- packages/plugins/ethereum-blockchain-client/src/index.js
- packages/plugins/ganache/src/index.js
- packages/plugins/mocha-tests/src/lib/index.js
Teller tests used to fail because of "Out of gas exception". 
I put the default gas limit to `8000000` in the provider and in the contracts, so they match the Ganache server default. This way, all tests pass, including the test app (nothing changed)
We should really implement a way to change that gas limit either per test or for all tests. Should it be the gas limit config in contracts config? Will do it in another PR once we take a decision.
> fix(@embark/test): fix Teller tests by introducing bigger gas limit

- site/themes/embark/layout/partial/footer.swig
- Add Teller, Assemble and Nimbus
- Remove Embark which is a duplicate of the current website (It is the same as other the Status Network websites, e.g., https://dev.status.im/)
The order of the Status Network projects is
Products
Dev Tools
Infra
(Suggested by Jonny)
> update the footer

- dapps/templates/boilerplate/embark.json
- dapps/templates/demo/contracts/simple_storage.sol
- dapps/templates/demo/embark.json
- dapps/templates/simple/embark.json
- packages/core/core/src/configDefaults.ts
- packages/embark/package.json
- packages/embark/src/test/config.js
- packages/embark/src/test/contracts.js
- packages/embark/src/test/modules/compiler/compiler.js
- packages/embark/src/test/modules/solidity/contracts/simple_storage.sol
- packages/embark/src/test/modules/solidity/contracts/token.sol
- packages/embark/src/test/modules/solidity/solidity.js
- packages/embark/src/test/vm_fs.js
- packages/plugins/scaffolding/src/contractLanguage/solidityBuilder/templates/contract.sol.hbs
- packages/plugins/solidity/package.json
- packages/plugins/solidity/src/solcP.js
- packages/plugins/solidity/src/solcW.js
- yarn.lock
Bumped the bundled [solc](https://www.npmjs.com/package/solc) to version `0.6.1`. This PR builds on the dependabot commit in #2189 (which has been closed; this one replaces it).
Make various related changes to templates, tests, etc. The methodology for finding files that needed changes was to search through the whole monorepo for the strings "solc" and "solidity" and then inspect the hits to see whether changes were needed/appropriate.
Remove `solc` as a dependency in `packages/embark/package.json` so that it's only a proper dependency in `packages/plugins/solidity/package.json`. Adjust how the "bundled" `solc` package's version is determined, i.e. inspect the `package.json` of `embark-solidity` instead of `embark`.
When `solc`'s version is `>=0.6.0` use the [new callback API][api]. …
> build(deps): bump solc from 0.5.0 to 0.6.1

- package.json
This results in faster completions on Azure Pipelines. For an individual build (OS/Node.js combination) it shaves off ~10 or more minutes, depending on the OS.
Once the `lint` and `test` steps have collective implementations we should be able to shave another couple of minutes off of the completion times.
The steps that take the longest are `yarn install` (~4 minutes), collective `typecheck` (~4 minutes), and `ci:dapps` (~3 minutes).
> ci: revise "ci:full" script to run some steps collectively

- packages/core/console/package.json
current issue with latest nightly `embark-console not found`, is due to the wrong directory being specified in package.json
> bugfix(@embark/console): fix included package files

- packages/plugins/ens/src/index.js
- packages/stack/contracts-manager/src/index.js
This was caused by the fact that we add the ENS contract to the
manager when before they deploy, but the dependency resolution was
done while building the contracts, so even before.
So the solution was to add a "before build" action so that the ENS
module could add its contracts to the manager if needed.
> fix(@embark/contracts): fix ENS contracts not being resolved as deps

- dapps/tests/app/test/embarkJS_spec.js
- packages/embarkjs/ens/src/index.js
registerSubDomain  didn't work in tests because it used the old way
of checking the env, which is checking the `this.env` string, but in
tests, we use the `test` env. So instead, we now check if it is a
known network using the network ID (like we do for other place)
> fix(@embark/ens): fix registerSubDomain in tests and add test

- dapps/templates/demo/app/components/blockchain.js
TLDR: Only affected Demo. We added `enableEthereum` randomly which wasn't needed
This only affected the demo. We somehow put the `enableEthereum()`
call right before the Demo `set` function, so since we now throw
when it's not available, it stopped the `set`. But it was never
needed because demo has `autoEnadble` on, meaning that `enable` is
called at the start.
> fix(@embark/demo): fix ethereum not available in browser in the demo

- packages/embarkjs/ens/src/index.js
- packages/plugins/ens/src/ensContractAddresses.js
Change address to the updated one because of a flaw found in the old
> chore(@embarkens): update ENS Registry mainnet address

- package.json
The `"qa:full"` script comes into play in the contexts of `scripts/release.js` (`npm run release`) and `scripts/stable-release.js` (`npm run release:stable`).
> build: update "qa:full" script in same manner as revised "ci:full"

- packages/embark/src/cmd/dashboard/monitor.js
`packages/embark/src/cmd/dashboard/dashboard.js` overwrites the logger instance's `logFunction` method with a method named `logEntry` defined on the class exported from `packages/embark/src/cmd/dashboard/monitor.js`. Update `logEntry` in the same way as `logFunction` was revised in #2184.
> fix(@embark/dashboard): update dashboard's `logEntry` to match core/logger's `logFunction`

- packages/core/core/src/config.ts
- packages/plugins/geth/src/index.js
Before, we checked if the network was a testnet or mainnet and
warned if there were no account sconfigured to sync. However, that
didn't take into account that we could connect to an external node,
hence not starting Geth at all.
So to fix that, I moved the condition and message to the Geth module
and only log when we start the node and the condition is met.
> fix: only show account warning when Geth will actually start

- dapps/.gitignore
- dapps/tests/contracts/contracts.js
- dapps/tests/contracts/embark.json
- packages/embark/src/cmd/cmd_controller.js
Before, `embark build` would wait at the end if there was an
afterDeploy, because there was no way with the old string and array
syntax to know when the commands were done.
Now, with the function syntax, we can wait for the end.
This way, we can exit the build at the end if it is a function
afterDeploy.
Otherwise, we show a message saying that they should update
> fix@embark/cmd-controller): exit build if afterDeploy is not array

- packages/core/engine/src/index.ts
- packages/embark/src/cmd/cmd_controller.js
`Engine`s internal `coreComponents()` API sets up a bunch of things like
a `ProcessManager` and the `ServiceMonitor`. The `ServiceMonitor` activates
itself on `embark:engine:started` and practically monitors registered services
until the process has been explicitly stopped.
There are some commands that don't actually need service monitoring like `build` and
a future `exec` command that's in the making. For those cases it's useful to have them
disable the service monitor when `coreComponents()` is used.
This commit introduces configuration options to `coreComponents()` with currently one
supported option: `disabledServiceMonitor` which defaults to `false`.
Usage:
```
engine.registerModuleGroup('coreComponents', {
disableServiceMonitor: true
});
```
<!-- Star Trek/Wars, n/BSG, Voltron, …
> feat(core/engine): allow for disabling serviceMonitor activation

- site/source/docs/contracts_configuration.md
updated hook examples from
```
deployIf: (dependencies) => {
```
to
```
deployIf: async ({contracts, web3, logger}) => {
```
magic
> chore: update hooks examples to destructure dependencies object

- dapps/tests/app/test/namesystem_spec.js
- packages/plugins/ens/src/index.js
- site/source/docs/naming_configuration.md
Enable putting `$accounts[i]` in subdomain registrations, where `i`
is the index of the `getAccounts` array.
This is the same behaviour we have for contract deployement
> feat(@mbark/ens): enable the use of $accounts in registrations

- packages/core/utils/src/index.ts
- packages/core/utils/src/serialize.ts
- packages/stack/contracts-manager/src/contract.ts
- tsconfig.base.json
For all instances where a `Contract` instance is serialized using `JSON.stringify`, the `logger` property was being stringified and written to logs and contract artifact files.
Add Serializer class that allows ignoring of class properties during serialization when using `JSON.stringify`.
Created a static decorator class `Serializer` that can be used to decorate classes and class properties (and extended to methods, accessors, etc), which determine if a class property should be ignored when the class instance is serialized using `JSON.stringify`.
NOTE: The `Serializer` relies on TypeScript’s decorators which are still listed as experimental (requiring the necessary compiler flag) despite being around for several years. Decorators are a stage 2 proposal for JavaScript.
> fix(@embark/contracts-manager): Remove `logger` from serialized contract

- packages/plugins/ens/src/index.js
Was caused by the contract being added in case another contract uses
it as a dependency, but it automatically tried to deploy with it, so
instead, set it as `deploy: false` until we see if we need to
register it
> fix(@embark/ens): fix tests erroring on FIFS contract deploy

- packages/stack/test-runner/src/lib/reporter.js
Before, we added the gas for all receipts that came in because they
had a `gasUsed`, instead of adding the gas for receipts that came
with a transaction
> fix(@embark/test-runner): fix reporter to only catch gas for txs

- packages/stack/contracts-manager/src/index.js
This was an issue experienced with ENS contracts not being deployed
because the configs used `strategy: explicit` and ENS configs are
not in configs.
This fixes Teller with Embark.
To fix, I changed the way we check for deploy. If `deploy` is set as
`true` it should always deploy even if not in configs. It just means
they were added from a plugin (like ENS)
Also, I needed to set to `false` the `deploy` property of contracts
compiled that were not in config, because otherwise, they tried to
deploy, which goes against the strategy. This is because those
contracts get initiated as `deploy: true`.
> fix(@embark/contracts-manager): always deploy contracts with deploy: true

- dapps/templates/demo/contracts/simple_storage.sol
- packages/cockpit/ui/src/actions/index.js
- packages/core/utils/src/file.ts
- packages/core/utils/src/index.ts
- packages/plugins/ethereum-blockchain-client/src/api.js
- packages/plugins/ethereum-blockchain-client/src/index.js
- packages/plugins/transaction-logger/src/index.js
- packages/stack/blockchain/src/api.ts
Adds back the watch on contract events and writes them to a file
with the same method as contract logs from transaction-logger, so
I extracted those methods to utils/file so that both could use the
same functions.
Seems like a lot of other functions `ethereum-blockchain-client/src/api.js` are not used, so there might be other cases like `getEvents` where the getter function "works", but it's always returning nothing because the setter function is never called.
Example: `subscribeToPendingTransactions` is never called. Is it no longer needed because we do that logic somewhere else? Or do we have an API that relies on those transactions that's now never returning anything? it,s hard to tell, because those functions come from before the refactor.
> fix(@embark/blockchain-api): add back contract event listen and log

- dapps/tests/app/test/simple_storage_deploy_spec.js
- packages/embarkjs/embarkjs/src/lib/blockchain.js
- packages/embarkjs/embarkjs/src/lib/utils.js
- packages/embarkjs/web3/src/index.js
- packages/plugins/mocha-tests/src/lib/index.js
Set these up so we can call `deploy`, `at`, and `new` on contract
classes.
This PR cherry-picks https://github.com/embarklabs/embark/pull/1670/commits/3f6442f3043d52cd3cecea6311f55aa7037939cb and https://github.com/embarklabs/embark/pull/1670/commits/fec1babc9fc19e8d706455ca447f8173f8698149 as they didn't make it into `master` back then, right before the v4 release.
> fix: set helper methods on contracts

- dapps/templates/boilerplate/test/contract_spec.js
- dapps/templates/demo/test/simple_storage_spec.js
- dapps/templates/simple/test/contract_spec.js
- dapps/tests/app/test/another_storage_spec.js
- dapps/tests/app/test/array_references_spec.js
- dapps/tests/app/test/embarkJS_spec.js
- dapps/tests/app/test/expiration_spec.js
- dapps/tests/app/test/interface_spec.js
- dapps/tests/app/test/lib_test_spec.js
- dapps/tests/app/test/namesystem_spec.js
- dapps/tests/app/test/plugin_storage_spec.js
- dapps/tests/app/test/simple_storage_deploy_spec.js
- dapps/tests/app/test/simple_storage_spec.js
- dapps/tests/app/test/token_spec.js
- dapps/tests/contracts/test/another_storage_spec.js
- dapps/tests/contracts/test/array_references_spec.js
- dapps/tests/contracts/test/lib_test_spec.js
- dapps/tests/contracts/test/simple_storage_spec.js
- dapps/tests/contracts/test/token_spec.js
- packages/plugins/mocha-tests/package.json
- packages/plugins/mocha-tests/src/lib/index.js
This commit adds a convenience API `artifacts.require(name)` that aims to make
requiring artifacts a little bit more straight forward.
Usage:
```
const SimpleStorage = artifacts.require('SimpleStorage');
const EmbarkJS = artifacts.require('EmbarkJS');
```
> feat(@embark/test-runner): introduce artifacts.require API

- packages/core/logger/src/index.js
During the latest round of Logger updates, the `writeToFile` function was changed to an `async.cargo` queue and all `writeToFile` references should have been updated to push a a task to the queue.
The main issue was that the `dir` function was not upgraded to push a task to the `writeToFile` queue.
Upgrade the `dir` function to push a task to the `writeToFile` queue to be in line with all other logger functions.
> fix(@embark/logger): Make `dir` the same as all other logger functions

- packages/stack/contracts-manager/src/index.js
Turns out that https://github.com/embarklabs/embark/commit/17cec1b78701c37bc8c43dccee6093cbe28ff70b has never worked as intended.
Custom provided `abiDefinition` values have been simply ignored. Embark always used the
`abiDefnition` that resulted from the Smart Contract compilation.
> fix(stack/contracts-manager): ensure custom `abiDefinition` is set properly if provided

- packages/plugins/ethereum-blockchain-client/src/index.js
This is caused by web3 using the method name to show which method
doesn't have the right number of arguments, but the constructor does
not have a name
Before:
```
[SimpleStorage]: Invalid number of parameters for "undefined". Got 0 expected 1!
```
After:
```
[SimpleStorage]: Invalid number of parameters for "constructor". Got 0 expected 1!
```
> fix(@embark/deployment): fix undefined in web3 error message about number of arguments

- packages/stack/pipeline/package.json
- packages/stack/pipeline/src/api.js
- packages/stack/pipeline/src/index.js
- packages/stack/pipeline/test/api.spec.js
- packages/stack/pipeline/test/pipeline.spec.js
- packages/stack/pipeline/tsconfig.json
- packages/utils/testing/src/lib/embark.js
- packages/utils/testing/src/lib/plugin.js
Update `embark-pipeline` dependencies.
Add unit tests for `embark-pipeline`.
Update Embark testing framework to include assertion testing for API calls and event actions.
[API documentation](https://github.com/embarklabs/embark/wiki/API-Documentation) has also been updated.
Unit tests using jest and sinon. Embark testing framework updates using sinon.
> chore(@embark/pipeline): Update pipeline dependencies and add tests

- packages/stack/contracts-manager/src/index.js
- site/source/docs/contracts_configuration.md
Adds proxyFor to contracts that merges the ABI of the parent
contract to the child (proxy)  contract so that the proxy can use
the methods of the parent but is deployed as itself
> feat(@embark/contracts): add proxyFor property for contracts

- packages/core/engine/src/index.ts
- packages/plugins/ganache/package.json
- packages/plugins/ganache/src/index.js
- packages/plugins/ganache/tsconfig.json
- packages/stack/blockchain/src/index.js
- packages/stack/proxy/src/proxy.js
I started working on fixing the warning about Event emitter that appearred in the tests, and found a bug about the `-node` option and the Ganache client.
The problem was that the Ganache plugin never actually checked, like other clients, if a node was already started, so it always used the VM.
However, if you used `--node=ws://loc...`, you want Embark to connect to that URL. So, now, Ganache will check if the endpoint is already running, if it is, it will connect to it using a normal web3 provider, otherwise, it will use the VM provider.
So, after fixing that, I could confirm that the Event Emitter problem happens both with the VM provider and without it, meaning that it was not related to Ganche at all.
I finally found that the problem was in the proxy, where we have 2 sources of events …
> Fix Ganache node connection and Event emitter warning

- packages/stack/proxy/src/proxy.js
Only the  Ganache provider has the setMaxListener
> fix(@embark/proxy): only up event listeners on available providers

- packages/plugins/ganache/src/index.js
We registered the status check for Ganache even when Ganache was not
the client
> fix(@embark/ganache): fix status when ganache is not the client

- dapps/tests/app/test/simple_storage_deploy_spec.js
- packages/embarkjs/embarkjs/src/lib/blockchain.js
`.deploy()` is an alias to `.new()` and in other tools also no longer used
as API to deploy instances. In addition, we don't want it to shadow the
original web3 `deploy()` API which actually caused a breeaking change.
> fix: revert custom `deploy()` API for `EmbarkJS.Contract`

- dapps/tests/app/config/contracts.js
- packages/core/utils/src/index.ts
- packages/plugins/ens/src/index.js
- packages/plugins/specialconfigs/src/functionConfigs.js
- packages/plugins/specialconfigs/src/index.js
- packages/plugins/specialconfigs/src/listConfigs.js
- packages/stack/deployment/src/contract_deployer.js
- site/source/docs/contracts_configuration.md
This commit introduces a new feature that enables users to calculate Smart Contract
constructor arguments lazily using an (async) function. Similar to normal Smart Contract
configurations, the return or resolved value from that function has to be either a list
of arguments in the order as they are needed for the constructor, or as an object with
named members that match the arguments individually.
```
...
development: {
deploy: {
args: async ({ contracts, web3, logger}) => {
// do something with `contracts` and `web3` to determine
// arguments
let someValue = await ...;
return [someValue];
// or
return {
initialValue: someValue
};
}
}
}
}
...
```
Closes #2270
> feat(plugins/specialconfigs): adds support for Smart Contract args as functions

- dapps/tests/app/test/another_storage_spec.js
- dapps/tests/app/test/array_references_spec.js
- packages/core/core/src/index.ts
- packages/core/core/src/processes/processLauncher.js
- packages/core/utils/src/accountParser.js
- packages/core/utils/src/env.js
- packages/core/utils/src/index.ts
- packages/embark/src/cmd/cmd.js
- packages/plugins/geth/src/devtxs.ts
- packages/plugins/rpc-manager/src/lib/eth_accounts.ts
- packages/plugins/rpc-manager/src/lib/eth_sendTransaction.ts
- packages/plugins/rpc-manager/src/lib/eth_signData.ts
- packages/plugins/rpc-manager/src/lib/eth_signTypedData.ts
- packages/plugins/rpc-manager/src/lib/eth_subscribe.ts
- packages/plugins/rpc-manager/src/lib/eth_unsubscribe.ts
- packages/plugins/rpc-manager/src/lib/index.ts
- packages/plugins/rpc-manager/src/lib/personal_newAccount.ts
- packages/plugins/rpc-manager/src/lib/rpcModifier.ts
- packages/plugins/rpc-manager/src/lib/utils/signUtils.ts
- packages/stack/blockchain/src/index.js
- packages/stack/proxy/src/proxy.js
- packages/stack/test-runner/src/lib/index.js
- site/source/docs/contracts_testing.md
Managing account details inside of the RPC Manager became a bit convulted and difficult to follow due to any web3 requests inside of an `RpcModifier` communicating over the proxy and therefore to other `RpcModifier`’s or itself. It also created cases where node accounts were duplicated by way of running the `eth_accounts` modifier multiple times (the first time getting accounts from the node and subsequent times getting accounts from the modified `eth_accounts` response.
This has been simplified by having the entry point of the `rpc-manager` (`index.js`) talk directly to the node via `web3`. This allowed account/nodeAccount management to also be handled by the entry point, removing the need for each individual `RpcModifier` from having to handle these account details. The result is a much …
> refactor(@embark/rpc-manager): Simplify RPC modifications

- packages/embark/src/cmd/cmd_controller.js
The blockhain for the demo and basic templates didn't work anymore, because they use ganache for the dev env.
Added back the registers for embark-ganache. They had been removed by removing the geth and parity registers
> fix(@embark/cmd-controller): add back embark-ganache registrations

- packages/core/console/src/index.ts
- packages/core/engine/src/index.ts
- packages/core/utils/src/index.ts
- packages/embark/src/bin/embark.js
- packages/plugins/basic-pipeline/src/index.js
- packages/plugins/basic-pipeline/src/webpack.config.js
- packages/plugins/basic-pipeline/src/webpackProcess.js
- packages/plugins/graph/src/index.js
- packages/stack/blockchain/src/index.js
- packages/stack/communication/src/index.js
- packages/stack/storage/src/index.js
- site/source/docs/configuration.md
- site/source/docs/structure.md
See #2277. This PR is derived from that one, the main difference being the approach taken in `packages/embark/src/bin/embark.js`. It also fixes a bug arising from #2260 that results in `EMBARK_NO_SHIM` scenarios failing because no argument is passed to `EmbarkBin.prototype.exec`.
---
This commit introduces support for using `embark.config.js` to calculate the embark configuration object that is otherwise provided via `embark.json`.
If an `embark.config.js` file is present, it will be used over the `embark.json` file.  The `embark.config.js` module needs to export either an object or a function that can be asynchronous and has to return or resolve with an embark configuration object:
```js
// embark.config.js
module.exports = async function () {
let config = ...; // do lazy calculation of …
```
> feat: add support for `embark.config.js`

- packages/plugins/ganache/src/index.js
- packages/stack/blockchain/src/index.js
- packages/stack/proxy/src/index.ts
Since we changed the Ganache plugin to work exactly like a real Node plugin, it also meant that when doing `embark blockchain`, it acted as if a node was started and ready to be used, when in fact, it was just creating a useless process, since the provider is not shared between the Embark instances.
Instead, I return `true` on the `start` action, so that the blockchain command sees that as if the Node was already started. If we ever have other VM clients, we just have to do the same,
> fix(@embark/ganache): make embark blockchain exit when using Ganache

- site/_config.yml
This caused a problem for links that were not from the subdomain,
but still part of embarklabs.io, because it opened a new tab
> fix: don't open external links to another tab by default

- package.json
- scripts/fix-versions.js
Range specifiers for intra-monorepo dependencies can, because of nightly or stable releases, get out of sync between PR branches and `master`. In many cases, what then happens is that yarn can't satisfy the dep range with the version in the monorepo, so it installs from the registry and updates `yarn.lock` accordingly. We have a `check-yarn-lock.js` script (`yarn cylock`) that detects the situation and prevents CI from passing. However, to date the problem has to be fixed manually.
Implement a script that fixes the problem by scanning all the `package.json` files and updating mismatched ranges.
It's best to run the script *after* rebasing against `master`.
> build: implement a script to fix intra-monorepo dep range specifiers in rebased branches

- scripts/check-yarn-lock.js
Refactor `scripts/check-yarn-lock.js` to use a dynamically calculated blacklist (`npx lerna ls --all --json`) instead of a hard-coded whitelist to improve accuracy and reduce future maintenance.
---
I got the idea when working on #2351.
> refactor: modify check-yarn-lock.js to use a blacklist instead of a whitelist

- packages/core/core/src/config.ts
When taking a bare-minimum truffle project, created from the [`metacoin` truffle box](https://github.com/truffle-box/metacoin-box), there were only two steps that needed to happen as a prerequisite:
1. First, run `embark init`, creating a default `embark.json`
2. Second, run `npm init`, creating a default `package.json`.
Trying to run `embark run` before those prequisites would error with appropriate directions in the console, guiding the user to run those steps explicitly.
After running these two steps, Embark would hang waiting for the namesystem plugin to come up.
Changing the default namesystem config to disabled allows Embark to start up successfully without hanging.
The rationale behind this decision is that if `embark.json` doesn’t exist, then we cannot expect that the namesystem …
> feat(@embark/core): Support minimum truffle projects

- packages/embark/src/cmd/cmd.js
- packages/embark/src/cmd/cmd_controller.js
- packages/plugins/basic-pipeline/src/index.js
- site/source/docs/embark_commands.md
- site/source/docs/pipeline_and_webpack.md
- site/source/docs/running_apps.md
When making `basic-pipeline` in https://github.com/embarklabs/embark/commit/948956ab1f7fde154e4a4a36c58cfa677ecff9c6 we've introduced a regression
and with this fix, a behaviour change as well::
1. The `webpackConfigName` passed to `Engine` is completely ignored, caused it to be
`undefined` down the line when the plugin tries to do its work (we essentially broke bundling)
2. With that configuration being ignored, we need a new way to make this configurable.
Since `basic-pipeline` is now a true plugin, it makes sense for itself to have configuration
options for that, while still providing decent defaults.
3. The trickly thing is that `webpackConfigName` used to have different values per command.
For example `build` used to use `production` while `run` used `development` as config.
4. This …
> fix(plugins/basic-pipeline): ensure correct webpack config is loaded

- packages/plugins/ganache/src/index.js
- packages/plugins/geth/src/blockchain.js
- packages/plugins/parity/src/blockchain.js
We updated async's version and there was a change in async's `whilst` where the condition needs to be a callback and not just a return.
Edit: also added a commit that fixes a Ganache bug where the node accounts changed in between runs when using custom accounts
> fix(@embark/blockchain): fix blockchain plugins' use of async whilst

- packages/plugins/solc/src/lib/Compiler.js
- packages/utils/testing/src/embark.js
In https://github.com/embarklabs/embark/pull/2330#discussion_r389906144 we've changed the `solc` plugin to read its
`pluginConfig` from `embark.config`. This was done under the assumption that
the `embark.config` is always properly populated with a dedicated `pluginConfig`.
In our testing environment we pass `Embark` objects to plugins, while in reality, we pass `Plugin` instances.
These two are different in nature, so relying on `embark.config` inside the plugin seemed the
most pragmatic way forward without introducing a bigger refactoring in the testing APIs.
Unfortunately it turned out that `embark.config` isn't populated with a `pluginConfig`
which essentially caused it to break apps.
This commit reverts that change done in the mentioned PR and patches the Embark testing
API to behave …
> fix(plugins/solc): don't read pluginConfig from plugin.config

- packages/cockpit/ui/src/components/Console.js
- packages/cockpit/ui/src/containers/HomeContainer.js
Prior to this commit, `Console` would only be rendered when Embark's API returns
at least one registered process from `/embark-api/processes`.
`Console` itself would then add another processes "embark" resulting in two tabs
with console output. This used to work fine because Embark always registered
at least a blockchain process.
In https://github.com/embarklabs/embark/commit/cd934f815799e376799b0c14cfeafe8b1bf3f3e8 however, this has changed.
With Ganache being the default blockchain, there's no longer a processes registered for this
service, resulting in an empty list for `processes` inside Cockpit, causing `Console` not to render
at all. Which also means the `embark` process logs aren't rendered either.
This commit removes the requirement of `processes` being non-empty so that embark …
> fix(cockpit/console): ensure console for processes is rendered

- packages/plugins/mocha-tests/src/lib/index.js
Caused issues because we kept in memory the old contracts, including
the onDeploys.
> fix(@embark/mocha): reset contracts before each test file

- packages/embark/src/cmd/cmd_controller.js
Even when the storage config sets storage to disabled, upload should still be allowed, as uploaded dapps should have the ability to NOT use storage once uploaded.
> fix(@embark/storage): Allow upload when storage is disabled

- packages/cockpit/ui/package.json
- packages/cockpit/ui/src/containers/HomeContainer.js
- packages/embarkjs/snark/package.json
- packages/plugins/quorum/package.json
- yarn.lock
Also fix some peer dependency related warnings seen during `yarn install`.
> style(@cockpit): remove unused var causing a linter failure in a CI environment or production build

- package.json
- packages/plugins/basic-pipeline/package.json
- yarn.lock
Node v13.13.0 introduced a change that is incompatible with `@babel/preset-env` versions `< 7.9.0`.
See:
* https://github.com/nodejs/node/pull/32351
* https://github.com/nodejs/node/issues/32852
* https://github.com/babel/babel/pull/11283
Bump our direct dependencies to `7.9.5` and manually cause additional bumps in `yarn.lock` that result in all versions of `@babel/preset-env` installed in the monorepo's `node_modules` trees being `>= 7.9.0`.
> build(deps): bump @babel/preset-env to >= 7.9.0

- packages/plugins/geth/src/gethClient.js
Since geth 1.9, --unlock also requires a "I know that this is unsafe" flag. 
Fixes #2404
Added --allow-insecure-unlock to the flags of geth. 
Right after the flag --unlock, it add the new flag.
No.
> fix(@embark/geth): add --allow-insecure-unlock flag to geth
