embarklabs/embark

- boilerplate/config/blockchain.yml
- tasks/deploy.coffee
Big contracts require higher gasLimit. Let's make it configurable.
> configurable gas limit

- js/mine.js
`embark blockchain` was getting into strange loop of starting and stopping mining every second. This pr fixes this issue.
> fixed mining condition

- js/mine.js
- lib/blockchain.js
See also https://github.com/iurimatias/embark-framework/issues/15
> Increase minimalAmount, fix pendingTransactions, maxpeers to zero

- README.md
it took me several minutes to figure out how it's working, so it might be worth adding to readme ;)
> readme update - debugging embark

- lib/deploy.js
This made embark-framework work for me. (More often than not.)
> Keep looping if address is null

- lib/compiler.js
solc 0.1.2 changed parameter names
> Support for solc 0.1.2

- lib/blockchain.js
use account if explicitly set in config
> Accountfix

- boilerplate/config/blockchain.yml
- lib/blockchain.js
- lib/compiler.js
- lib/config/blockchain.js
This was done on a whim and I'm not sure it would fit within the confines of the embark testing suite. Let me know if any changes need to be made and I will get right on them. Thanks again.
> Create multiple accounts all run by the same password for testing purposes (NEEDS TESTING!)

- README.md
Didn't see a Contribute, apologies if you hate these. 
I just spun up the demo, very nice, but ran into dependency error when trying `embark simulator`
> Include EtherSim in Readme

- bin/embark
- js/mine.js
- lib/contracts.js
- lib/deploy.js
Started to go over your code as I want to add some functionality and noticed you have quite a few JS lint errors.
This PR fixes most of them. It was mostly just missing semicolons and duplicit `var` declarations.
JS has function-wide variable scope, not block-wide.
> fix lint errors

- lib/index.js
Refers to https://github.com/iurimatias/embark-framework/issues/201
> Add missing argument

- lib/core/services.js
- lib/dashboard/console.js
> Minor typos and better naming

- lib/cmd.js
- test/cmd.js
> changes undefined process.exit(code) to process.exit(9)

- .gitignore
Minor annoyance, but I use WebStorm and really would hate to commit those .idea files accidentally.
> ignore jetbrains folders

- lib/core/services.js
If there's another service in the computer running on IPFS default port 5001 it could cause an exception.
> Fixed issue with logic to detect if IPFS node is online

- CONTRIBUTING.md
Input required since trello card doesn't offer much on opinions here. Seems like an easy start to one though.
> a good start on a contrib.md

- README.md
- docs/embarkjs.rst
Correct the directory jump link
update dapp structure in readme
update usage of deployment in reademe and docs
> update readme and docs

- demo/app/js/index.js
- docs/embarkjs-storage.rst
- js/build/embark.bundle.js
- js/embark.js
- Fixes on some logic related to IPFS Storage in EmbarkJS
- Added some error handling on demo related to IPFS
- Updated docs to show how to handle error related to Storage
> Fixes to EmbarkJS and updating demo app 

- lib/core/test.js
- lib/index.js
- test/cmd.js
- test_app/package.json
- test_app/test/another_storage_spec.js
- test_app/test/simple_storage_spec.js
- test_app/test/token_spec.js
This refactor moves the test class outside of Embark for a more pure testing experience. It also speeds up loading of the test object by only requiring dependencies when the functions that need them are called.
> Speedup test class

- lib/cmds/template_generator.js
- test/cmd.js
> this fixes problems where concatenating the path string would fail

- lib/cmd.js
- lib/cmds/blockchain/blockchain.js
- lib/cmds/blockchain/geth_commands.js
- lib/core/plugins.js
- lib/index.js
- test/blockchain.js
Getting some issues in the Geth commander though. Please review before merging.
> integration testing fixes

- docs/embarkjs.rst
I know this is a small change. I just experienced this error in going through the demo and wanted to try my first Github pull request.
> Fixed parenthases error in docs

- README.md
Add more example options for better documentation of contracts.json
> Improve documentation of contracts.json

- docs/plugins.rst
- lib/contracts/deploy.js
- lib/contracts/deploy_manager.js
- lib/core/plugin.js
[+] Added beforeDeploy plugin feature.
> Fixing #325: beforeDeploy plugins feature

- lib/cmds/blockchain/blockchain.js
- lib/cmds/blockchain/geth_commands.js
Add missing values from config/blockchain.json.
Related to issue #331.
> Pull request for issue #331

- docs/tests.rst
- docs/using-contracts.rst
Updated the documentation for the smart contract usage and test based on the experience of using embark during the creation of tests. Content added is:
1. How to run individual tests
2. How to access accounts
3. How to deploy contracts using web3.eth.Contract
4. How to run actions after deployment
> Updating documentation related to smart contracts and tests

- lib/modules/ipfs/upload.js
- lib/modules/swarm/upload.js
Use `shelljs.which` instead of `shelljs.exec('which')` because the the which command doesn't exist on Windows.
> Fix upload on Windows

- lib/index.js
Messaging order was changed to use events instead of on completion of async commands.
> Moved console "ready" message to write after outputDone event is emitted

- lib/modules/vyper/index.js
Removed the useless waterfall and moved the compile code to a standalone static function
> Refactor Vyper compiler

- lib/core/engine.js
fixes issue with using console logs in the console itself
> intercept logs in the app itself - stopgap fix

- lib/constants.json
- lib/contracts/contracts.js
- lib/core/config.js
- lib/core/engine.js
- package-lock.json
- package.json
- test/contracts.js
Like the title said. Before adding a contract would not get caught. Now it does.
> Fix adding a contract

- lib/constants.json
- lib/contracts/contracts.js
- lib/core/config.js
- lib/core/engine.js
- lib/pipeline/watch.js
- package-lock.json
- package.json
- test/config.js
Not what I was supposed to fix, but at leat this makes sure that when we change contracts.json, the deploy takes the changes arguments.
> Redeploy with right config on config change

- lib/contracts/deploy.js
- lib/core/engine.js
- lib/modules/profiler/index.js
- package-lock.json
- package.json
Profiler for smart contracts implemented. Needs to add gas costs in another PR.
> Profile me officer

- lib/cmds/blockchain/blockchain.js
- lib/cmds/blockchain/geth_commands.js
- templates/boilerplate/config/blockchain.json
- templates/demo/config/blockchain.json
- test/config.js
- test/test1/config/blockchain.json
- test_apps/contracts_app/blockchain.json
- test_apps/test_app/config/blockchain.json
Fixes the problem where the private blockchain would get corrupted by an ungraceful exit.
To use --dev, I found that you don't need to init with a genesis.json nor create an account. In fact, it didn't actually work when I did.
Please test yourself before merging. For me, it worked, but I want to be sure I didn't screw someone up.
> Use --dev when in development

- lib/pipeline/webpackProcess.js
- package-lock.json
- package.json
For the demo app, goes from 12 seconds to 2 seconds! ✈️
> Add a plugin that caches to increase file processing speed

- js/embark.js
- templates/demo/app/dapp.js
https://www.pivotaltracker.com/n/projects/2133693
> execOnReady -> OnReady

- lib/constants.json
- lib/core/processWrapper.js
- lib/i18n/locales/en.json
- lib/pipeline/pipeline.js
- lib/pipeline/webpackProcess.js
- lib/process/eventsWrapper.js
- lib/process/processLauncher.js
- lib/process/processWrapper.js
- package-lock.json
- package.json
- test/processLauncher.js
Adds the Process wrapper used to extend processes
- handles log
- adds Events instance that sends back events to the parent process
Also adds Process Launcher to launch an a new process by forking it and:
- handles events from the child
- handles logs from the child
- permits the module that launched the process to subscribe to messages from the child
> Add Process Wrapper and Launcher

- lib/contracts/code_generator.js
- lib/contracts/contracts.js
- lib/core/events.js
- lib/pipeline/pipeline.js
moves code generation from the pipeline to code generator
> Refactor pipeline

- lib/cmd.js
- lib/index.js
> add command for only compiling contracts in build command

- lib/dashboard/monitor.js
> should add scroller to available services

- lib/dashboard/console.js
- lib/dashboard/monitor.js
- lib/modules/profiler/index.js
> Fixed Returns From Plugin Modules

- lib/i18n/locales/en.json
- lib/modules/solidity/solcP.js
- lib/modules/solidity/solcW.js
- test/contracts.js
_________________________________________________________________
/    _____________________________________________________________    \
|   |                                                             |   |
|   |  >_                             .                           |   |
|   |                                . *                          |   |
|   |                                "  ..                        |   |
|   |                          .=*&æ..="""*.                      |   |
|   |                        .     ""        *                    |   |
|   |                       &               *                     |   |
|   |                       &c               .                    |   |
|   |                       *e                *                   |   |
|   | …
> update solc wrapper

- lib/pipeline/watch.js
fixes segfault issue seen sometimes
> only close watcher when it's actually ready

- lib/tests/test.js
Maybe could even be like Test.prototype.getAccounts = web3.eth.getAccounts; ?
> make getAccounts a simple web3..eth.getAccounts wrapper.

- lib/i18n/locales/en.json
- lib/modules/vyper/index.js
> add a warning for vyper installation

- js/embark.js
- lib/core/config.js
- lib/core/engine.js
- lib/index.js
- lib/modules/ens/embarkjs.js
- lib/modules/ens/index.js
- package-lock.json
- package.json
- templates/boilerplate/config/namesystem.json
- templates/demo/config/namesystem.json
The beginnings of the ```Names``` module and the initial resolution services provided via ENS. Needs some help in terms of wiring the thing into the main embark module.
> ENS Domain name resolution initial integration

- lib/cmds/simulator.js
> fix simulator preferential treatment

- js/embark.js
- lib/contracts/code_templates/vanilla-contract.js.ejs
> alias to the abi property in an object

- lib/contracts/contracts.js
- lib/tests/test.js
- package-lock.json
- test_apps/test_app/package-lock.json
Even more speed
Stats: https://docs.google.com/spreadsheets/d/1lZfoLrIlT4ihy56PmPFhDvg6QT1ZhxPVq0CmESSLSJU/edit?usp=sharing
> compile tests only once

- lib/modules/ipfs/index.js
- lib/modules/swarm/index.js
- lib/processes/storageProcesses/ipfs.js
Includes IPFS command run 
Includes response from IPFS/Swarm service checks
Includes url being checked during IPFS/Swarm service checks.
> Improve storage logging (during --loglevel trace)

- lib/process/processWrapper.js
- lib/processes/blockchainProcessLauncher.js
- package-lock.json
> Kill all the zombies!

- lib/tests/test.js
- test_apps/test_app/test/simple_storage_spec.js
config() now calls back correctly with the accounts
> fix calling back with accounts

- lib/tests/run_tests.js
- package-lock.json
- test_apps/contracts_app/test/another_storage_spec.js
- test_apps/contracts_app/test/array_references_spec.js
- test_apps/contracts_app/test/lib_test_spec.js
- test_apps/contracts_app/test/simple_storage_spec.js
- test_apps/contracts_app/test/token_spec.js
- test_apps/test_app/test/another_storage_spec.js
- test_apps/test_app/test/array_references_spec.js
- test_apps/test_app/test/lib_test_spec.js
- test_apps/test_app/test/plugin_storage_spec.js
- test_apps/test_app/test/simple_storage_spec.js
- test_apps/test_app/test/token_spec.js
Fixed version of https://github.com/embark-framework/embark/pull/487
> Override require to replace embark.require by only require

- lib/contracts/blockchain.js
- lib/tests/test.js
Enables setting the deployment host and port to connect to for the tests just like in contracts.json. Enables the wallet feature too.
> Connect to a node in tests

- lib/modules/storage/index.js
- lib/pipeline/pipeline.js
- lib/processes/storageProcesses/ipfs.js
- lib/processes/storageProcesses/storageProcessesLauncher.js
- lib/processes/storageProcesses/storageUtils.js
- lib/processes/storageProcesses/swarm.js
- package-lock.json
Stops getting the weird `'[IPFS error: ,Error: spawn ipfs ENOENT] undefined'`
Instead, puts a message saying it is not installed and where to find information.
> Put message if swarm or ipfs is not installed

- lib/modules/fuzzer/index.js
- lib/modules/gasEstimator/index.js
- lib/modules/profiler/index.js
- package-lock.json
There's a couple of buggy contracts in here but am not sure how exactly to fix them. Would like some advice here and to see if the bugs might just be on my end.
> Gastimation

- lib/contracts/contracts.js
- test_apps/test_app/test/another_storage_spec.js
- test_apps/test_app/test/interface_spec.js
- test_apps/test_app/test/simple_storage_deploy_spec.js
So when you rely on a contract and there is an error in it that makes it not deploy (like being an interface), it show a warning
> show warning if dependency is not deploying

- lib/cmds/blockchain/geth_commands.js
- test_apps/test_app/config/blockchain.json
> fix test app config and swap olympic for rinkeby as testnet option

- lib/cmds/blockchain/blockchain.js
- lib/cmds/blockchain/geth_commands.js
- test/blockchain.js
- test_apps/contracts_app/blockchain.json
- test_apps/test_app/config/blockchain.json
Having them caused an error and Geth crashed
> remove deprecated geth params

- lib/contracts/contracts.js
- package-lock.json
- package.json
Needed to reset the `compileError` flag once compilation succeeded.
> Fix for starting embark with a contract that has an error, then fixing, seems to still break the pipeline

- lib/processes/storageProcesses/ipfs.js
- package-lock.json
Runs `ipfs daemon` first, reads stdout for message regarding ipfs not initialised, then runs `ipfs init`, then re-runs `ipfs daemon`.
> Run `ipfs init` for the case when user has installed ipfs, but not initialised it.

- templates/boilerplate/config/blockchain.js
- templates/boilerplate/config/communication.js
- templates/boilerplate/config/contracts.js
- templates/boilerplate/config/namesystem.js
- templates/boilerplate/config/storage.js
- templates/boilerplate/config/webserver.js
- templates/boilerplate/test/contract_spec.js
- templates/demo/config/blockchain.js
- templates/demo/config/communication.js
- templates/demo/config/contracts.js
- templates/demo/config/namesystem.js
- templates/demo/config/storage.js
- templates/demo/config/webserver.js
- templates/demo/test/simple_storage_spec.js
- templates/simple/contracts.js
- templates/simple/test/contract_spec.js
Adds new tests and comments explaining the different options.
Not sure how storage works entirely, so maybe @emizzle you could do it for me please? 😃
> Update templates with tests and comments

- lib/core/config.js
- lib/modules/whisper/index.js
Changed Whisper origin header to "embark" and added "embark" to geth CORS.
How can we test this?
> Added cors for whisper

- lib/modules/gasEstimator/index.js
> convert to average

- lib/cmds/simulator.js
ganache crashes inexplicably if this option is used
> don't use -h option in simulator

- lib/modules/ens/embarkjs.js
Catches the ABI errors and puts out something more pleasant.
> Gracefully error ens

- lib/modules/ens/embarkjs.js
> small correction

- lib/core/config.js
- lib/modules/ipfs/index.js
- lib/modules/storage/embarkjs.js
- lib/modules/swarm/index.js
- lib/versions/library_manager.js
- package-lock.json
- package.json
- templates/boilerplate/embark.json
- templates/demo/embark.json
- test_apps/test_app/embark.json
Replaced usage in storage module (on dapp side) with async.js `detectSeries`
> Removed p-iteration from embark altogether

- templates/boilerplate/config/blockchain.js
- templates/demo/config/blockchain.js
In issue #541 sync mode config setting was updated from "light:true" to "syncMode:light", but demo still has old values.
> Update sync mode config values in demo config #601

- lib/cmd.js
- lib/contracts/contract_deployer.js
- lib/core/events.js
- lib/tests/reporter.js
- lib/tests/run_tests.js
- lib/tests/test.js
See https://github.com/embark-framework/embark/pull/593 for screen captures
Now works with a custom node
> Display gas cost in tests

- lib/cmd.js
- lib/cmds/blockchain/blockchain.js
- lib/cmds/blockchain/blockchainProcess.js
- lib/core/config.js
- lib/core/engine.js
- lib/index.js
Also initConfig for build, upload and graph so that isDev is correctly set
> set isDev as default if there is no blockchain file

- js/embark.js
- lib/cmds/blockchain/geth_commands.js
- lib/modules/ens/embarkjs.js
- templates/demo/app/components/ens.js
- templates/demo/app/dapp.css
- templates/demo/app/dapp.js
Adds an ENS section to the Demo template enabling to lookup and resolve.
Needed to fix a bag where the getId for the current chain was no longer there so we didn't use the right address. Also, I changed promises to callbacks because I don't like promises 🤷‍♂️ 
Here is what it looks like:
> Add ENS to Demo app and also add small fix

- package.json
Repository url and homepage seems to be old url.
> Update package.json url

- lib/contracts/contract_deployer.js
> Display info about gas when deploying contract

- README.md
Deprecated message: ethereumjs-testrpc has been renamed to ganache-cli, please use this package from now on
> Update readme with new package

- lib/pipeline/webpackProcess.js
- package.json
- test_apps/test_app/package.json
Reverts embark-framework/embark#656
> wRevert ".embark/versions modules"

- lib/tests/run_tests.js
- lib/tests/test.js
- test_apps/test_app/test/another_storage_spec.js
While running test, if there is one node running
then we try to connect to it first then we start
a new one with ganache-cli
There is multiple run into this function:
- at bootstrap
- when the test call the config
> In test, try to connect to node first

- lib/constants.json
- lib/core/processes/processManager.js
- lib/modules/blockchain_connector/index.js
- lib/modules/blockchain_process/blockchain.js
- lib/modules/blockchain_process/index.js
If the user started a blockchain on testnet and then embark run on develop, it will warn him that there is a mismatch.
> Warn if there is a mismatch in network ids

- lib/modules/ens/index.js
Disabling ENS in config completely stops ens stuff
> disable ens if it is not enabled

- lib/constants.json
- lib/core/config.js
- lib/tests/test.js
Caused the ENS files to disappear during compilation
> fix reload file removing plugins

- .npmignore
Same as #694 but for `3_1_0` branch.
> don't ignore templates' .gitignore files

- lib/modules/blockchain_process/proxy.js
**TL;DR**
Not all transaction were logged
This is because the global variable were not clean as they should be
mix between `commList` and `receipts`
Also, indentation has been fixed
> Fix transaction logger

- cmd/dashboard/console.js
- cmd/dashboard/monitor.js
- lib/core/ipc.js
- lib/core/modules/coderunner/runCode.js
**TL;DR**
Print error in console (same behaviour as normal node REPL)
See screenshot for the 3 modes:
- embark run
- embark console
- embark console with IPC
> IPC works with errors, console print errors

- cmd/dashboard/console.js
- lib/core/modules/coderunner/codeRunner.js
- lib/modules/deployment/contract_deployer.js
**TL;DR**
Limit the number of command we pass to the console
> Console via IPC do not run on deploy

- templates/demo/app/components/blockchain.js
- templates/demo/app/components/ens.js
- templates/demo/app/components/storage.js
- templates/demo/app/components/whisper.js
Might be better to review with whitespace hidden, because blockchain component used 4 spaces.
> Pressing enter in a form now submits it instead of reloading in demo

- lib/modules/blockchain_process/simulator.js
Applying networkId from blockchain.json for simulator.
> Setting up network id for simulator from blockchainConfig

- templates/demo/config/namesystem.js
**TL;DR**
Move register config to development
> [CHORES] Move name config to development

- lib/modules/ens/contracts/ENS.sol
- lib/modules/ens/contracts/ENSRegistry.sol
- lib/modules/ens/contracts/FIFSRegistrar.sol
- test_apps/test_app/app/contracts/ENS.sol
- test_apps/test_app/app/contracts/ENSRegistry.sol
- test_apps/test_app/app/contracts/FIFSRegistrar.sol
Remove warning for ENS contracts
> Remove ENS warning

- templates/boilerplate/config/blockchain.js
- templates/boilerplate/config/communication.js
- templates/boilerplate/config/contracts.js
- templates/boilerplate/config/namesystem.js
- templates/boilerplate/config/storage.js
- templates/demo/config/blockchain.js
- templates/demo/config/communication.js
- templates/demo/config/contracts.js
- templates/demo/config/namesystem.js
- templates/demo/config/storage.js
- templates/simple/contracts.js
same as https://github.com/embark-framework/embark/pull/727 but rebased/cherry-picked
> add comments to configs

- lib/core/engine.js
> remove double registerModule

- lib/core/modules/coderunner/codeRunner.js
enables doing `await web3.eth.getAccounts()` in the console
> simple implementation of await in the console

- lib/modules/console_listener/index.js
- lib/modules/ens/index.js
**TL;DR**
Hide ENS *initial* transaction log:
```
pid 14977 listening on /home/anthony/code/embark-framework/embark/templates/demo/.embark/embark.ipc
========================
Welcome to Embark 3.2.0-develop
========================
webserver available at http://localhost:8000
ready to watch file changes
Blockchain node is ready
Ethereum node detected..
loading solc compiler..
compiling solidity contracts...
deploying contracts
deploying SimpleStorage with 134157 gas at the price of null Wei, estimated cost: 0 Wei
SimpleStorage deployed at 0x5F7D9A81A40d03F1c2b0b4CD22fDCfCDfEC5707d using 134157 gas
finished deploying contracts
writing file dist/index.html
Deployment Done
writing file dist/js/dapp.js
Looking for documentation? You can find it at …
```
> Hide ENS Transaction log

- lib/core/i18n/i18n.js
Embark's locale detection was broken with respect to environment variables. This PR fixes it.
> fix locale detection

- lib/utils/template_generator.js
Template download / generate should not proceed if the destination path already exists.
> don't continue with template install if destination path exists

- lib/modules/webserver/index.js
- lib/modules/webserver/server.js
**TL;DR**
If the web server port is already in use, will increment it.
Tries to infinity and beyond, but leaves a message in case, to not infinity loop without the user knowing
Made it work with 3 simultaneous Embarks.
> Enable multiple Embark runs at the same time

- templates/demo/app/components/ens.js
- templates/demo/config/namesystem.js
**TL;DR**
Change ENS root to `eth` in demo
> Change ENS root to eth in demo

- templates/demo/app/components/storage.js
- templates/demo/config/communication.js
- templates/demo/config/namesystem.js
**TL;DR**
Display alert only when not IPFS on demo
> Display alert only when not ipfs

- lib/modules/blockchain_connector/provider.js
- lib/modules/blockchain_process/proxy.js
- lib/tests/test.js
- test_apps/test_app/app/contracts/simple_storage.sol
- test_apps/test_app/test/simple_storage_deploy_spec.js
- test_apps/test_app/test/simple_storage_spec.js
**TL;DR**
Using `embark test --node "ws node..."` in the test_app (and some normal tests too) causes errors, socket disconnections and hangs (yes, ALL those)
Requires https://github.com/embark-framework/EmbarkJS/pull/15
> Fix test_app with a WS node

- lib/utils/accountParser.js
- templates/boilerplate/config/contracts.js
- templates/demo/config/contracts.js
- templates/simple/contracts.js
**TL;DR**
If there is a password field in privateKeyFile object, it will try to decode the keystore.
Works for V1 and V3 keystores (eg: from MyCrypto)
> Unlock account using keystore file with password

- lib/core/config.js
- lib/core/processes/processLauncher.js
- lib/modules/blockchain_connector/index.js
- lib/modules/blockchain_process/blockchain.js
- lib/modules/ens/index.js
**TL;DR**
Allow zero config in blockchain
- Do not break in case of networkId is not set
- Allow to debug child process
Command: ```../../bin/embark run foo --nodashboard```
BEFORE
```demo git:(develop) ../../bin/embark run foo --nodashboard 
pid 6518 listening on /home/anthony/code/embark-framework/embark/templates/demo/.embark/embark.ipc
========================
Welcome to Embark 3.2.0-develop
========================
webserver available at http://localhost:8000
ready to watch file changes
IPFS node not found, attempting to start own node
Starting ipfs process
ipfs process started
Blockchain node is ready
Geth error: Unlocking account 95cd9d4af4d472712241cd19b7459c0253a0ad12 | Attempt 1/3
!! Unsupported terminal, password will be echoed. …
```
> Allow zero config in blockchain

- lib/modules/deployment/contract_deployer.js
**TL;DR**
Silent Already deployed for ENS contracts
> Silent already deployed

- lib/core/engine.js
- lib/modules/compiler/index.js
This PR fixes passing compiler options down to the compiler.
> Fix passing compiler options

- .eslintrc.json
- lib/core/config.js
- lib/core/plugin.js
- lib/modules/blockchain_process/blockchain.js
- lib/modules/code_generator/index.js
- lib/modules/deployment/contract_deployer.js
- lib/modules/whisper/index.js
- lib/utils/utils.js
**TL;DR**
Enable es-lint no-else-return:
https://eslint.org/docs/rules/no-else-return
> Enable no-else-return

- cmd/cmd_controller.js
- lib/core/engine.js
**TL;DR**
If the console is run on his own, then it is a server otherwise a client
> Console can be a client or server ipc

- lib/modules/ens/index.js
> Don't crash if ENS contracts don't deploy

- lib/modules/console/index.js
- test/console.js
**TL;DR**
Only setup embarkjs once
> Fix message events already declared

- lib/modules/deployment/contract_deployer.js
**TL;DR**
Fix for gas Price when deploying contract:
```
deploying SimpleStorage with 134157 gas at the price of 1 Wei, estimated cost: 134157 Wei
SimpleStorage deployed at 0xC1118FBff59c51da500F7851e22D90AD921D576d using 134157 gas
```
> Fix Gas Price

- cmd/cmd_controller.js
- lib/core/engine.js
- lib/core/ipc.js
- lib/tests/test.js
**TL;DR**
IPC detection is fully dynamic on all command
=> IPC needs to be fully setup before initialisation of modules
```
pid 5089 listening on /home/anthony/code/embark-framework/embark/templates/demo/.embark/embark.ipc
IPFS node not found, attempting to start own node
Starting ipfs process
ipfs process started
Blockchain node is ready
Ethereum node detected..
loading solc compiler..
IPFS node detected..
compiling solidity contracts...
deploying contracts
deploying SimpleStorage with 134157 gas at the price of 1 Wei, estimated cost: 134157 Wei
SimpleStorage deployed at 0x72aE945De40C3a9a357Efd1930081B2473aA25E3 using 134157 gas
finished deploying contracts
Deployment Done
running webpack with 'production' config...
writing file …
```
> Fix dynamic IPC

- lib/modules/ens/index.js
**TL;DR**
Do not trigger embark config on secondary deploy (contract never change)
Before:
```
Ready
change: contracts/simple_storage.sol
compiling solidity contracts...
deploying contracts
SimpleStorage already deployed at 0xFA96b1FcfCB1BEe0244E164cCC1051cf86aC34a1
finished deploying contracts
running webpack with 'development' config...
writing file dist/js/dapp.js
Blockchain> ENSRegistry.setSubnodeOwner("0x93cdeb708b7545dc668eb9280176169d1c33cfd8ed6f04690a0bcc88a93fc4ae", "0xa51c98855bc4307cb9f527e1c99ad1bc38fa5ac69f02488fcdccb45eaaa6fcaf", "0x7B84ef33447d401B07620B502cD978a63feCB1ab") | 0xfca564cc719545d542865fad6061690046db02631999472b1848a87099e875f4 | gas:35901 | blk:78 | status:0x1
Blockchain> ENSRegistry.setResolver("0x287f04779ab2b50666684f4538e8b6d560f254d291f0e53801570727aa3063 …
```
> Ens config is run only once

- bin/embark
- cmd/cmd.js
- package-lock.json
- package.json
Makes sure to be in a Dapp and then checks the package json to make sure everything is installed.
Also, a bit of linting.
> Check node modules before running

- templates/demo/app/dapp.js
**TL;DR**
Adding blockchain indicator
> Adding blockchain indicator

- lib/modules/console/index.js
- lib/modules/swarm/embarkjs.js
- lib/modules/swarm/index.js
- lib/modules/swarm/upload.js
- package-lock.json
- package.json
**TL;DR**
SwarmAPI is our own library that we created to support the latest breaking uri schema changes for Swarm. These changes utilise the new library inside of Embark.
Depends on https://github.com/embark-framework/swarmjs/pull/2 being merged (now merged).
The SwarmAPI library is now published (https://github.com/embark-framework/swarm-api) and this branch now points to the published package.
> Switch to SwarmJS which supports latest version of Swarm

- lib/core/config.js
- lib/modules/ens/index.js
- templates/boilerplate/config/namesystem.js
- templates/demo/config/namesystem.js
**TL;DR**
Prevent embark to crash if there is no config file for ens
> Prevent embark to crash when there is no config for ens

- lib/core/modules/coderunner/runCode.js
**TL;DR**
Adding process and interval function
> Adding new repl options

- cmd/cmd_controller.js
- lib/core/engine.js
- lib/modules/plugin_cmd/index.js
- lib/utils/utils.js
Adds new command 'plugin'. closes #767 
<use @mentions for quick questions, specific feedback, and progress updates.>
> Plugin cmd

- lib/modules/contracts_manager/index.js
We were using the wrong realRuntimeBytecode
> fix redeploy of contracts on spaces

- bin/embark
- cmd/cmd.js
Do not check dependencies for reset, version, help, etc.
> Only check dependencies on Dapp commands

- lib/core/file.js
- test_apps/test_app/app/contracts/SimpleStorageWithHttpImport.sol
Was caused by the content we run the regex on getting modified.
> Fix double http import

- cmd/cmd_controller.js
- lib/core/engine.js
**TL;DR**
- IPC server is only for `embark run`
- Avoid double call to connect in console
- Remove web server from console command
> No webserver and no ipc server on console

- cmd/cmd.js
- lib/core/fs.js
- lib/tests/run_tests.js
- package-lock.json
- package.json
When --coverage option is there, it will generate the report and open the browser
> Add --coverage option to tests

- lib/pipeline/pipeline.js
**TL;DR**
Before any pipeline process, clean the build dir
> Clean build dir before starting

- lib/modules/blockchain_process/blockchain.js
- lib/modules/storage/storageProcessesLauncher.js
- lib/modules/swarm/process.js
**TL;DR**
Swarm use the same datadir as the blockchain
> Swarm use local data dir

- cmd/cmd_controller.js
- lib/core/ipc.js
- lib/core/modules/coderunner/runCode.js
- lib/modules/swarm/embarkjs.js
- package-lock.json
- package.json
**TL;DR**
Circular error in json
Web3 connection via IPC (not the most elegant part but don't want to refactor before release)
EmbarkJS in console via require not import (@jrainville this is the error when starting test app)
> Fix circular JSON and swarm api require

- lib/modules/coverage/index.js
- lib/tests/run_tests.js
**TL;DR**
This changes the behaviour from writing on exit to writing after each trace event.
https://static1.srcdn.com/wordpress/wp-content/uploads/2018/06/Firefly-Serenity-Ship.jpg?q=50&fit=crop&w=798&h=407)
> Update coverage report after suite

- templates/demo/app/components/blockchain.js
- templates/demo/app/dapp.js
> simplify embark_demo, use web3.js 1.0 only

- lib/core/modules/coderunner/codeRunner.js
- test_apps/test_app/config/contracts.js
- test_apps/test_app/test/token_spec.js
**TL;DR**
Better support for await:
- Only resolve if the await keyboard is specified to avoid unexexpected behaviour
- Support for multi instructions using `;` keywork
Do you see any other case?
> Better support for await

- lib/modules/blockchain_process/blockchain.js
This may have been removed in the rebase, adding it back in.
**TL;DR**
This may have been removed in the rebase, adding it back in.
> Adding back calling code block for dev_funds

- lib/tests/reporter.js
- lib/tests/run_tests.js
- lib/tests/test.js
**TL;DR**
- Use override of send only when coverage
- Do not *2 gas price
See develop vs the branch:
> Gas Price not modified by coverage

- package-lock.json
- package.json
> update to embarkjs 0.4.2

- lib/tests/run_tests.js
**TL;DR**
Improve coverage UX by eliminating 1 step to view coverage reports.
> Improve coverage UX

- lib/modules/ens/index.js
Was causing issues in some cases
> take into account when event does not trigger a callback

- lib/tests/run_tests.js
**TL;DR**
Match the path we output to the path we open on the browser for coverage.
> Match coverage path

- lib/modules/blockchain_process/geth_commands.js
same as #858 but to the right branch
> Geth creates new account - add password warning

- lib/modules/code_generator/code/reload-on-change.js
- lib/modules/code_generator/index.js
- lib/modules/webserver/server.js
- lib/modules/webserver/templates/embark-building-placeholder.html.ejs
- package-lock.json
- package.json
Add browser reload on file change/rebuild
Fixes #832
> Add browser reload on file change/rebuild

- lib/modules/webserver/server.js
- package-lock.json
- package.json
> update ws package (security issue)

- cmd/cmd_controller.js
> `embark reset` should remove a dapp's coverage subdir

- lib/modules/deployment/contract_deployer.js
- package-lock.json
- package.json
**TL;DR**
Update web.js dependency to version 1.0.0-beta.36
> Update web.js to 1.0.0-beta.36

- .eslintrc.json
Revise eslint config to allow `!!` expressions.
> allow coercion w/ `!!`

- cmd/cmd_controller.js
- lib/modules/console/index.js
**TL;DR**
EmbarkJS needs to be done in console.
This is I think due to recent changes on EmbarkJS, it used to be in the file we run code on but has been separated
> EmbarkJS blockchain must be done

- cmd/cmd.js
- lib/modules/blockchain_connector/index.js
- lib/modules/deployment/contract_deployer.js
- lib/modules/ens/index.js
> Misc fixes

- lib/modules/coverage/contract_source.js
**TL;DR**
Fixes contract matching in situations where a contract file could hold multiple contract classes.
http://cdn-static.denofgeek.com/sites/denofgeek/files/styles/insert_main_wide_image/public/4/07//spaceballs.png?itok=tNEKvq9F)
> Fix contract matching

- lib/modules/coverage/contract_source.js
**TL;DR**
This removes logging for solidity nodes we don't know how to handle yet.
> Don't log that we don't know how to handle node

- lib/modules/blockchain_process/blockchain.js
master had a `!!` (allowed by changes in lint config on master) but develop replaced it with a `Boolean(...)`. This PR changes it back to `!!`.
> Boolean() -> !!

- lib/utils/template_generator.js
The *"Next steps"* message displayed by `embark demo` shouldn't be displayed until after `npm install` has finished installing the demo's dependencies.
> display "Next steps" after npm install has finished

- README.md
> Add more activity badges to readme

- lib/pipeline/pipeline.js
> output contracts json even if the pipeline is empty

- lib/modules/coverage/contract_source.js
**TL;DR**
This PR adds an edge case to a situation where a for loop wouldn't have an initialization statement and so it would crash coverage.
cc. @richard-ramos
> Account for empty initialization in loops

- lib/modules/webserver/server.js
**TL;DR**
The way WS works has changed and the merge didn't catch that
> Fix git merging badly

- lib/modules/ens/index.js
Add ENS console commands and rewrite resolve + lookup functions in EmbarkJS. The existing implementation of these functions was poorly written with several bugs. (return namehash rather than normalized name, returned resolved promise in some error cases, didn't return promise at all in others)
Fixes #834
> add ENS console commands

- lib/core/modules/coderunner/codeRunner.js
Error message is not clear enough when node connection is lost. Fixes #945.
> improved error message when there is issue communicating with node

- cmd/cmd.js
- lib/tests/run_tests.js
- lib/tests/solc_test.js
- lib/tests/test.js
- npm-shrinkwrap.json
- package.json
- test_apps/contracts_app/contracts/simple_storage.sol
- test_apps/contracts_app/test/ownable_test.sol
closes #817 
This PR is ready for review @iurimatias
> Integrate remix tests

- lib/core/config.js
- lib/core/file.js
- test/config.js
Add remapping when parse file to support embark-solc
Ref: https://github.com/embark-framework/embark-solc/issues/3
> Add remapping when parse file to support embark-solc

- lib/tests/run_tests.js
- lib/tests/test.js
**TL;DR**
This means that any test runs without coverage will run optimized Solidity code instead.
Fixes #987.
```
The Omega Class Destroyer
(Like the Agamemnon, Capt. Sheridan's Ship)
|~~~~~~~~~~~|                                                  
|-----------|
i               |===========|                       
|               |,---------.|                      __--~\__--.
#---,'""""`-_   `n     |`---------'|    `n    `n     ,--~~  __-/~~--'_____.
|~~~~~~~~~|---~---/=|___________|=\---~-----~-----| .--~~  |  .__|     |
-[|.--_. ===|#####|-| |@@@@|+-+@@@| |]=###|/-++++-[| ||||___+_.  | `===='-.
-[|'==~'    |#####|-| |@@@@|+-+@@@| |]=###|\-++++-[| ||||~~~+~'  | ,====.-'
|_________|---u---\=|~~~~~~~~~~~|=/---u-----u-----| '--__  |  '~~|     |
\       /=-   `    |,---------.|      `     ` …
```
> Only disable optimizations with coverage.

- lib/modules/blockchain_connector/index.js
- lib/modules/blockchain_connector/provider.js
**TL;DR**
Instead of relying on non reliable source, directly
check the ws status
> In case of ws, use the connected attribute

- cmd/cmd_controller.js
- lib/core/engine.js
- lib/modules/deployment/contract_deployer.js
- lib/modules/ens/index.js
- lib/modules/specialconfigs/index.js
- test_apps/contracts_app/contracts/another_storage.sol
- test_apps/contracts_app/contracts/test.sol
- test_apps/contracts_app/embark.json
- test_apps/contracts_app/ens.json
- test_apps/contracts_app/test/another_storage_spec.js
- test_apps/contracts_app/test/token_spec.js
- test_apps/test_app/app/contracts/test.sol
- test_apps/test_app/config/contracts.js
- test_apps/test_app/test/token_spec.js
> ens resolve

- cmd/cmd_controller.js
- lib/core/events.js
Fix for #971, added .once() into Events.
@alaibe 
spaceship.jpg
> Fix for #971 - "Fatal error when Ethereum node going offline"

- lib/modules/deployment/contract_deployer.js
Fix for #965 - "Console doesnt have contract objects for contracts with pre-defined addresses configured".
Fix for sometimes incorrect empty code detection in contract_deployer.js ("0x" vs "0x0").
@iurimatias 
Space_X_Big_Fffalcon_Rocket.jpg
> Fix for #965 - "Console doesnt have contract objects for contracts with pre-defined addresses configured"

- lib/core/config.js
- lib/core/plugin.js
- lib/modules/ipfs/index.js
- lib/modules/storage/storageProcessesLauncher.js
- lib/modules/swarm/index.js
**TL;DR**
Adds support for the `embark-status` plugin.
1. Allows CORS to be added as an event request.
2. Allows ES6 plugins.
3. Adds event emission for config hydration for blockchain, contracts, and webserver.
> Support for `embark-status` plugin

- embark-ui/src/components/Layout.css
- embark-ui/src/components/Layout.js
> Highlight header tab

- embark-ui/src/components/ContractsDeployment.js
- embark-ui/src/components/Description.js
- embark-ui/src/components/SignAndVerify.js
- embark-ui/src/components/TransactionDecoder.js
- embark-ui/src/components/Widget02.js
- embark-ui/src/containers/AppContainer.js
- embark-ui/src/containers/DeploymentContainer.js
- embark-ui/src/containers/SignAndVerifyContainer.js
- embark-ui/src/containers/TransactionDecoderContainer.js
**TL;DR**
Add prototypes to our react components
> Make linter happy 2019

- embark-ui/src/components/ContractLayout.js
- embark-ui/src/components/TextEditorToolbar.js
- embark-ui/src/containers/TextEditorAsideContainer.js
> Add icons for the contract page

- embark-ui/src/containers/CommunicationContainer.js
h/t to @alaibe for helping me understand the redux relationships.
> fix whisper in embark-ui

- embark-ui/src/components/ContractsDeployment.js
- embark-ui/src/containers/TextEditorAsideContainer.js
> Do no show interface on injected web3

- embark-ui/src/components/Description.js
- embark-ui/src/containers/AppContainer.js
- embark-ui/src/containers/CommunicationContainer.js
**TL;DR**
Fixes for console errors
> Fix console errors/warnings

- lib/modules/console/index.js
- lib/utils/utils.js
> Stringiy function for command console

- embark-ui/src/components/DataWrapper.js
- embark-ui/src/containers/GasStationContainer.js
> Add a warning when there is no blocks for the estimator

- lib/modules/webserver/server.js
> Add back output done

- embark-ui/src/actions/index.js
- embark-ui/src/sagas/index.js
- embark-ui/src/services/storage.js
**TL;DR**
Add back event on file save sucess
> Add back event on file save sucess

- npm-shrinkwrap.json
- package.json
> chore: update embarkJS to 0.4.5

- embark-ui/src/components/Login.js
That was quite annoying. No one needs autocomplete for the token
> Disable autocomplete in Login component and fix indentation

- embark-ui/src/reducers/selectors.js
- embark-ui/src/sagas/searchSaga.js
**TL;DR**
Resolves the name, then searches in for what it represents. Otherwise, only outputs the address and puts a message.
> Add searching ENS names in cockpit search bar

- embark-ui/src/components/ContractDebugger.js
- embark-ui/src/components/ContractLayout.js
- embark-ui/src/components/ContractTransactions.js
- embark-ui/src/components/DebugButton.js
- embark-ui/src/components/TextEditor.js
- embark-ui/src/components/TextEditorToolbar.js
- embark-ui/src/components/Transaction.js
- embark-ui/src/components/Transactions.js
- embark-ui/src/containers/ContractDebuggerContainer.js
- embark-ui/src/containers/EditorContainer.js
- embark-ui/src/containers/TextEditorAsideContainer.js
- embark-ui/src/containers/TransactionContainer.js
- embark-ui/src/containers/TransactionsContainer.js
- embark-ui/src/reducers/selectors.js
- embark-ui/src/utils/utils.js
- lib/modules/blockchain_connector/index.js
**TL;DR**
Add debug button (comes
from area-51)
> feat: add debug button to transaction and contract log

- README.md
> update badges to use master instead of develop

- src/lib/modules/authenticator/index.js
> fix: do not display log if no webserver

- embark-ui/src/actions/index.js
- embark-ui/src/components/AddFileModal.js
- embark-ui/src/components/AddFolderModal.js
- embark-ui/src/components/FileExplorer.js
- embark-ui/src/components/TextEditorToolbar.js
- embark-ui/src/containers/FileExplorerContainer.js
- embark-ui/src/containers/FileExplorerRowContainer.js
- embark-ui/src/containers/TextEditorToolbarContainer.js
- embark-ui/src/index.css
- embark-ui/src/reducers/selectors.js
- embark-ui/src/sagas/index.js
- embark-ui/src/services/api.js
- embark-ui/src/utils/utils.js
- src/lib/modules/pipeline/index.js
---
name: ⚙ Add crud to explorer
---
Allow to add file, remove file, add folder, remove folder to the code editor
> Add Crud to explorer

- embark-ui/src/containers/EditorContainer.js
- embark-ui/src/containers/FileExplorerRowContainer.js
> fix(ui): white screen on text editor

- src/lib/modules/coverage/contractSource.js
Instead of full match, start to count as soon
as there is 1 match
@andremedeiros pls give feedback
> fix: coverage count

- src/lib/modules/coverage/contractSource.js
WhileStatement
UsingForDirective
EnumDefinition
> feat: handle missing directive

- lib/modules/solidity/solcP.js
- test/contracts/contract_with_http_import.sol
- test/file.js
- test_apps/test_app/app/contracts/SimpleStorageWithHttpImport.sol
- test_apps/test_app/package-lock.json
- test_apps/test_app/test/http_contract_test.js
> add solc 0.5.0 support to 3.2.x

- embark-ui/src/sagas/searchSaga.js
- src/lib/constants.json
- src/lib/modules/blockchain_connector/index.js
- src/lib/modules/deployment/contract_deployer.js
- src/lib/modules/ens/ENSFunctions.js
- src/lib/modules/ens/index.js
- src/lib/modules/transactionTracker/index.js
- src/lib/utils/utils.js
- test_apps/contracts_app/contracts/another_storage.sol
- test_apps/contracts_app/test/another_storage_spec.js
Enables only the use of domains in that white list
Also, fixes a bug that make the deployment hang. I'd need people to test it though, as it's super unpredictable.
> Add whitelist for ENS

- src/lib/modules/ens/index.js
The bug seems to be in web3 but we fix it
by avoiding extra tx
> fix: deploy hangs

- embark-ui/src/components/ContractDebugger.js
- embark-ui/src/components/DebugButton.js
- embark-ui/src/components/TextEditor.js
- embark-ui/src/containers/EditorContainer.js
- embark-ui/src/reducers/selectors.js
> fix(ui): click on debug button start the debugger

- lib/tests/test.js
- lib/utils/accountParser.js
> Fix test with node in config

- src/lib/modules/tests/test.js
- src/lib/utils/accountParser.js
Also fix the warning for ganache configs for accounts.
> Fix using a node configuration in tests

- package.json
- src/cmd/dashboard/dashboard.js
- src/cmd/dashboard/monitor.js
- src/cmd/dashboard/repl.js
- yarn.lock
This is a rebased version of @lastmjs 's effort in #804 
@lastmjs FYI: unfortunately the only way to update your PR was to create a new one as we don't have write access to your fork.
@andremedeiros @iurimatias can we put together a list of outstanding things in this effort? Is this here still up to date? https://github.com/embark-framework/embark/pull/804#issuecomment-420424512
Closes #768
> feat(@embark/cli): repl support inside dashboard

- src/lib/modules/blockchain_connector/index.js
- src/lib/modules/deployment/contract_deployer.js
**ONLY MERGE ONCE https://github.com/embark-framework/EmbarkJS/pull/28 HAS BEEN RELEASED**
> feat(@embark/deployment): output transaction hash of contract deployment

- src/lib/modules/console/suggestions.ts
> bugfix(@embark/console): don't crash due to suggestions containg a `(` at the end

- embark-ui/src/components/ContractDebugger.js
- src/lib/modules/debugger/index.ts
> feature(@embark/debugger): enable/disable debugger prev/next buttons

- embark-ui/src/actions/index.js
- embark-ui/src/containers/AppContainer.js
- embark-ui/src/sagas/index.js
- embark-ui/src/services/api.js
- src/lib/modules/contracts_manager/index.js
When contracts are redeployed, send them to the UI so it gets automatically updated
> feat(ui): auto updates contracts in cockpit

- src/lib/modules/deployment/index.js
Otherwise there was a long period of time without any input on what's going on especially with a "real"
> Add logs to tell about pre-deploy

- src/lib/core/config.js
- src/lib/modules/authenticator/index.js
- src/lib/modules/blockchain_process/blockchain.js
- src/lib/modules/blockchain_process/blockchainProcess.js
- src/lib/modules/blockchain_process/blockchainProcessLauncher.js
- src/lib/modules/blockchain_process/proxy.js
- src/lib/modules/blockchain_process/simulator.js
- src/lib/modules/code_generator/code/reload-on-change.js
- src/lib/modules/webserver/index.js
- src/lib/modules/webserver/server.js
- src/lib/modules/webserver/templates/embark-building-placeholder.html.ejs
- src/lib/utils/utils.js
Resolves #940
- Adds https webserver
- Reverse proxy to talk to geth (HTTPS -> HTTP)
> Adds support for https dev webserver

- package.json
- src/lib/modules/compiler/README.md
- src/test/modules/compiler/compiler.js
- src/test/modules/solidity/contracts/erc20.vy
- src/test/modules/solidity/contracts/simple_storage.sol
- src/test/modules/solidity/contracts/token.sol
- src/test/modules/solidity/solidity.js
> Document compiler module & add test

- embark-ui/src/services/api.js
This is dues to those 2 endpoints being added
as the same time of the new technique
> fix: all ws endpoint use new technique

- src/lib/core/config.js
- src/lib/modules/tests/test.js
- src/lib/utils/contractsConfig.ts
- src/lib/utils/regexConstants.ts
Give the same ability to config function on test
than when running with embark run
> feat: apply contract change to test

- src/lib/modules/blockchain_process/gethClient.js
- src/lib/modules/tests/test.js
Basically, Geth is stupid, the only way to create the dev account is by running the Geth command using `--dev` but `new account` doesn't work.
also a small test fix
> Fix Geth running with multiple node accounts

- src/lib/modules/profiler/gasEstimator.js
Caused the Teller functions to just not have any estimate
> fix(profiler): do not exit on error but print it

- src/lib/modules/debugger/index.ts
Improve the debugger displays. Not sure if this fixes the original error, but I think the local variable might be broken in the remix package. (ticket: https://www.pivotaltracker.com/story/show/162737585)
> Fix debugger commands displays

- src/lib/modules/blockchain_connector/provider.js
- src/lib/modules/blockchain_process/gethClient.js
First thing in the Provider is to fix big contract deployments that's caused with Geth and WS.
Other thing is a fix to a bug I introduced to the geth client.
> Fix WS Geth issue and clear setTimeout

- src/lib/modules/coverage/contractEnhanced.ts
- src/lib/modules/coverage/index.ts
- src/lib/modules/coverage/injector.ts
- src/typings/embark.d.ts
For solc version below 0.4.21
fixes #1230
> feat: coverage without emit

- src/lib/modules/api/index.ts
- src/lib/modules/api/server.ts
Dynamic host in case of docker
> feat: allow cockpit with docker

- src/lib/modules/contracts_manager/index.js
- src/lib/modules/debugger/index.ts
* Allow to stop debugger
* Rename options (I got confused for almost 1 hour)
* Fix finding transaction
> feat: allow to stop debugger

- embark-ui/.storybook/addons.js
- embark-ui/.storybook/config.js
- embark-ui/package.json
- embark-ui/src/stories/account.stories.jsx
- embark-ui/yarn.lock
> feat(embark-ui): add storybook

- embark-ui/src/components/TransactionDecoder.js
- embark-ui/src/containers/TransactionDecoderContainer.js
- src/lib/modules/blockchain_connector/index.js
This is a WIP PR to get early feedback on transaction decoding based on raw transaction hashes
> feat(@cockpit/transaction-decoder): allow for decoding raw tx hashes

- src/lib/modules/blockchain_connector/provider.js
> fix: first parallel deploy

- packages/embark/src/test/config.js
- packages/embark/src/test/contracts/contract_with_http_import.sol
- packages/embark/src/test/utils.js
- test_dapps/packages/test_app/app/contracts/SimpleStorageWithHttpImport.sol
- test_dapps/packages/test_app/test/http_contract_test.js
The latest lerna changes have changed the HTTP paths of some test files used in the repo. This PR updates the paths to their new location.
> fix(@embark/test_app): Fix tests as paths have chagned

- README.md
- packages/embark/package.json
- yarn.lock
see https://coveralls.io/builds/21428554
> feature: add coveralls integration

- packages/embark-ui/src/actions/index.js
- packages/embark-ui/src/components/Preview.js
- packages/embark-ui/src/containers/EditorContainer.js
- packages/embark-ui/src/containers/TextEditorAsideContainer.js
- packages/embark-ui/src/reducers/index.js
- packages/embark-ui/src/reducers/selectors.js
* Save preview url in redux state
* Use css to show/hide the preview url in order to prevent the iframe to reload
> feat(ui): keep state in frame

- packages/embark/src/test/config.js
- packages/embark/src/test/contracts/contract_with_http_import.sol
- packages/embark/src/test/utils.js
- test_dapps/test_app/app/contracts/SimpleStorageWithHttpImport.sol
- test_dapps/test_app/test/http_contract_test.js
URLs for test_app files have changed on the remote again, this PR updates the tests to reflect that change.
> fix(@embark/core): fix tests as paths have changed again

- packages/embark-ui/src/components/Console.js
> feat(ui): color console item info as success

- packages/embark/src/lib/modules/code_generator/index.js
- packages/embark/src/lib/modules/pipeline/index.js
- packages/embark/templates/boilerplate/embark.json
- packages/embark/templates/boilerplate/package.json
- packages/embark/templates/demo/embark.json
- packages/embark/templates/simple/embark.json
- packages/embark/templates/simple/package.json
- test_dapps/test_app/app/js/app.js
- test_dapps/test_app/app/js/index.js
- test_dapps/test_app/app/js/test.js
Adds the web3 connector to templates and adds Blockchain.connect to the test_app to make it work
> Add web3connector to templates and make test_app work

- packages/embark/src/lib/modules/ipfs/index.js
- packages/embarkjs/src/storage.js
In addition to `EmbarkJS.Storage` not being available in the console (ie `await EmbarkJS.Storage.isAvailable()` always returned false), the error `Could not connect to a storage provider using any of the dappConnections in the storage config` would always appear in the console. The storage operations in the dapps were working OK.
The fix to this was three-fold:
1) Wait for the ipfs process to be started before attempting to run the `EmbarkJS.Storage.registerProvider/setProvider` in the console.
2) Wait for `EmbarkJS.Storage.registerProvider` to be called before `EmbarkJS.Storage.setProvider`. This was actually handled in #1349.
3) Remove any async operations from the `setProviders` method in the storage module. This was causing `callback is not defined` errors which were being swallowed …
> fix(@embark/storage): Fix storage not connecting error

- packages/embark/src/lib/modules/blockchain_connector/index.js
- packages/embark/src/lib/modules/blockchain_process/index.js
Fixes the huge crash we had when you put a bad port
> fix(blockchain-process): display error message when bad port

- packages/embark/src/lib/modules/coverage/contractEnhanced.ts
- packages/embark/src/lib/modules/coverage/index.ts
- packages/embark/src/lib/modules/tests/test.js
Use the contracts file instead of the configuration because contracts can be loaded dynamically via plugin
> feat(coverage): load contracts from plugin

- packages/embark-ui/src/actions/index.js
- packages/embark-ui/src/components/Console.js
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/cmd/dashboard/dashboard.js
- packages/embark/src/cmd/dashboard/monitor.js
- packages/embark/src/cmd/dashboard/repl.js
- packages/embark/src/lib/modules/console/index.ts
With this, doing a command in the cockpit or embark prints the result in both embark and the cockpit.
Only "issue" is that we don't have the actual command, especially in the dashboard, but @andremedeiros is working on that
> Make cockpit console synced with Embark's console (for commands)

- packages/embark-ui/src/components/ContractOverview.js
- packages/embark-ui/src/components/Contracts.js
- packages/embark-ui/src/components/GasStation.js
- packages/embark-ui/src/containers/GasStationContainer.js
Make messages given by the estimator clearer.
> fix(cockpit/estimator): make estimator clearer

- packages/embark/src/lib/modules/contracts_manager/index.js
Add contract state changes to the cockpit by sending contract state updates via the websocket.
> feature(@embark/cockpit): Add contract state changes to cockpit

- packages/embark/src/lib/modules/blockchain_connector/index.js
- packages/embark/src/lib/modules/deployment/contract_deployer.js
This fixes the case Barry had where it hung while synching, though, right now, it just crashed. 
With this, it will display a message and end the process
> Check if node is synchronized after connection

- packages/embark/src/lib/modules/console/suggestions.json
- packages/embark/src/lib/modules/console/suggestions.ts
**Cache suggestions**
Suggestions are cached for better performance on each request. When contracts are deployed, the suggestion cache is cleared, allowing for updated contract methods to be built in to the suggestions.
**Handle edge cases**
Handle cases when console command is parsed as an empty string, or possibly returns an empty object, which would cause `Object.getOwnPropertyNames` to throw an error (that is ultimately swallowed).
> feature(@embark/console): Suggestions improvements

- packages/embark-ui/src/components/AddFileModal.js
- packages/embark-ui/src/components/AddFolderModal.js
- packages/embark-ui/src/components/ContractsList.js
- packages/embark-ui/src/components/DeleteModal.js
- packages/embark-ui/src/containers/FileExplorerRowContainer.js
Also fix cases where modals closed for no reason
> fix(cockpit/editor): add delete modal to confirm deletion

- packages/embark-ui/src/components/ContractsList.js
- packages/embark-ui/src/components/TextEditorToolbar.js
- packages/embark-ui/src/containers/TextEditorToolbarContainer.js
- packages/embark-ui/src/reducers/index.js
- packages/embark-ui/src/reducers/selectors.js
Adds messages for loading, success and error
The messages are pretty generic right now, but we can easily add conditions in the reducer to have a specific message for save for example.
> feat(cockpit/editor): add status messages for file operations

- packages/embark-ui/src/containers/FileExplorerRowContainer.js
This caused issues when moving from one tooltip to the other
> fix(cockpit/editor): remove delay on tooltips

- packages/embark/src/cmd/dashboard/monitor.js
they were displaying the color as text instead of as a color
> fix(embark/logger): fix logs in the dashboard

- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/modules/console/index.ts
show `console > command` in the dashboard
> fix(embark/dashboard): show command in the dashboard

- packages/embark/src/lib/modules/deployment/contract_deployer.js
Needed the contracts to be evaled and registered as variables.
I tested and it works well for `Simp` which autocompletes to `SimpleStorage`, but then I can't autocomplete from `SimpleStorage.opt` to `SimpleStorage.options`. Not sure if it ever did, but it's still better than before.
Maybe @emizzle would know more?
> fix(embark/contracts): add the contracts back to the autocomplete

- packages/embark-ui/src/components/Communication.js
Handle enter pressed when listening to channels and sending messages.
> fix(@embark/cockpit): Utils/Communications handle enter

- packages/embark-ui/src/components/ContractOverview.js
When a fallback function is encountered give its signature as `function()`, disable row expansion, and omit the interaction form. Also label with a `fallback` badge.
> fix(embark-ui): detect fallback functions in the contracts explorer

- packages/embark/src/lib/modules/ipfs/process.js
As well as the IPFS API CORS, update the IPFS gateway CORS to successfully run the `embark-status` plugin.
> fix(@embark/ipfs): Fix IPFS gateway CORS for embark-status plugin

- packages/embark/package.json
- yarn.lock
> chore(@embark/embark): update handlebars dependency

- packages/embark-specialconfigs/src/index.js
This will change any output generated using `console.log` within deployment hooks to
```
ContractName > deploymentHook > Output
```
and
```
afterDeploy > Output
```
respectively.
E.g. an `onDeploy` hook config like this:
```
contracts: {
fromIndex: 0,
args: [100],
onDeploy: () => {
console.log('Hello from on deploy');
}
}
}
```
Will output:
```
SimpleStorage > onDeploy > Hello from on deploy
```
**Notice that this commit does not honour Embark's [deprecated string syntax](https://embark.status.im/docs/contracts_configuration.html#Error-Handling) for deployment hooks.**
> uiux: improve logging of deployment hooks by applying a context prefix

- packages/embark-specialconfigs/src/index.js
**Corresponding documentation PR (needs release with this feature release): https://github.com/embark-framework/embark-site/pull/167**
This commit enables new `beforeDeploy` deployment hooks. With this change
it's possible to add `beforeDeploy` to either `contracts: {}` within the contracts
configuration, or an individual contract.
For example:
```
contracts: {
beforeDeploy: async (context) => {
}
}
}
```
Runs the hook before `SimpleStorage` will be deployed. Whereas
```
contracts: {
...
beforeDeploy: async (context) => {
}
}
```
will be executed before *all* Smart Contracts will be deployed.
> feat(@embark/embark-specialconfigs): introduce new beforeDeploy hooks

- packages/embark/src/lib/constants.json
- packages/embark/src/lib/modules/code_generator/code/reload-on-change.js
- packages/embark/src/lib/modules/code_generator/index.js
- packages/embarkjs/src/blockchain.js
This transpiles the generated `embarkjs.js` file in `embarkArtifacts` so that it can be usable by Node applications like so: `const EmbarkJS = require('./embarkArtifacts/embarkjs.node').default;`
> feat(@embark/generator): transpile embarkjs.js to be used by node

- packages/embark/src/cmd/cmd_controller.js
Was missing the necessary services
> fix(@embark/console): fix cockpit console if using console command

- packages/embark-contracts-manager/.npmrc
- packages/embark-contracts-manager/README.md
- packages/embark-contracts-manager/package.json
- packages/embark-contracts-manager/src/index.js
- packages/embark-contracts-manager/tsconfig.json
- packages/embark-contracts-manager/tslint.json
- packages/embark/package.json
- packages/embark/src/lib/core/engine.js
- packages/embark/src/test/contracts.js
~Depends on #1552 and #1553, will be rebased against `master` if/when those PRs are merged.~
~The particular commit to review is 1e5f4263e052cf805ac28f5ccf18076bba8ba1f3.~
> refactor(@embark/contracts-manager): move contracts_manager into embark-contracts-manager package

- packages/embark-api-client/package.json
- packages/embark-api/package.json
- packages/embark-async-wrapper/package.json
- packages/embark-authenticator/package.json
- packages/embark-compiler/package.json
- packages/embark-contracts-manager/package.json
- packages/embark-core/package.json
- packages/embark-ens/package.json
- packages/embark-graph/package.json
- packages/embark-library-manager/package.json
- packages/embark-logger/package.json
- packages/embark-process-logs-api/package.json
- packages/embark-profiler/package.json
- packages/embark-scaffolding/package.json
- packages/embark-specialconfigs/package.json
- packages/embark-test-runner/package.json
- packages/embark-transaction-tracker/package.json
- packages/embark-typings/package.json
- packages/embark-utils/package.json
- packages/embark-vyper/package.json
- packages/embark-watcher/package.json
- packages/embark-webserver/package.json
- packages/embark-whisper/package.json
- packages/embark/package.json
- yarn.lock
Related to bumping the typescript package to its latest version
> build: bump tslint in all relevant pkgs from v5.11.0 to v5.16.0

- packages/embark-plugin-cmd/package.json
See: #1573, #1574, #1575, #1576.
> fix(@embark/plugin-cmd): revise package.json in light of #1573, #1574, #1575, #1576

- packages/embark-ui/src/containers/BlocksContainer.js
> refactor(@cockpit/explorer): revise blocks explorer per techniques of PRs #1492, #1494

- dapps/templates/demo/app/index.html
- dapps/templates/demo/embark.json
- dapps/templates/demo/package.json
> fix(@embark/demo): link css from dependency

- packages/embark-blockchain-connector/package.json
- packages/embark/package.json
- yarn.lock
> refactor: bump ganache-cli to latest stable version for compat with newer solc

- packages/embark-ens/README.md
- packages/embark-ens/src/ENSFunctions.js
- packages/embark-ens/src/embarkjs.js
- packages/embark-ens/src/index.js
> fix(@embark/ens): fix hashing of node in lookup

- site/source/_data/plugins.yml
- site/source/community/index.md
- site/source/docs/index.md
- site/source/index.md
- site/source/news/index.md
- site/source/plugins/index.md
- site/themes/embark/languages/en.yml
- site/themes/embark/layout/archive.swig
- site/themes/embark/layout/blog.swig
- site/themes/embark/layout/community.swig
- site/themes/embark/layout/docs-landing.swig
- site/themes/embark/layout/index.swig
- site/themes/embark/layout/page.swig
- site/themes/embark/layout/partial/footer.swig
- site/themes/embark/layout/partial/head.swig
- site/themes/embark/layout/partial/header-blog.swig
- site/themes/embark/layout/partial/header.swig
- site/themes/embark/layout/partial/paginator.swig
- site/themes/embark/layout/plugins.swig
This commit localizes messages of the mostly static sites of embark's
website. This is needed to have them internationalized into different
languages.
> chore: localize static sites

- packages/embark-deploy-tracker/src/index.js
Reported by a user who was using Ganache-cli using the --fork option. Somehow the block 0 is not accessible that way, so in the deploy tracker, I make it so we retry with block 1 instead when it fails with 0. If it fails with block 1, it does throw the error as usual.
> Fix tests hanging with ganche-cli using --fork

- packages/embark-ui/src/components/ContractOverview.js
- packages/embark-ui/src/containers/ContractsContainer.js
In cockpit, now contracts are gonna be ordered alphabetically, same thing for their functions in the explorer
> feat(@embark/ui): sort contracts and functions alphabetically

- packages/embark-storage/src/storageProcessesLauncher.js
Wrap `require.resolve` in try/catch instead of testing the path with `embark.fs.access`.
> refactor(@embark/storage): wrap require.resolve in try/catch

- packages/embark-ui/src/containers/EditorContainer.js
Guard against redux-saga fetching races in `componentDidUpdate`.
> fix(@cockpit/debugger): check if `debuggingContract` is undefined

- site/source/docs/structure.md
Originally discovered by christine-ho-dev
> fix(@embark/site): fix configuring contract link in structure.md

- packages/embark-pipeline/src/index.js
Kindof fixes https://github.com/embark-framework/embark/issues/1718
> fix(@embark/pipeline): streamline contract index file creation

- packages/embark-ui/src/actions/index.js
- packages/embark-ui/src/reducers/index.js
This was originally intended as a fix for the ENS bug in Cockpit where errors didn't show, but I found that actually ALL error entities didn't work, so this fixes it.
This PR then replaces https://github.com/embark-framework/embark/pull/1727
> fix(@embark/ui): fix errorEntities not working at all

- packages/embark/src/cmd/cmd.js
- packages/embark/src/cmd/cmd_controller.js
To help people who don't know too well how envs work, because uploading and building in the dev env is rarely the wanted behaviour.
> feat(@embark/cmd): add a warning on build and upload if development

- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/lib/core/engine.js
Most of the components don't work, but it starts
> fix(@embark/cockpit): make cockpit start again

- packages/embark-deployment/src/contract_deployer.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/checkContractSize.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/index.js
Adds back in checking of the contract size check before deployment by registering actions for event `deployment:contract:beforeDeploy`
> refactor(@embark/contracts): Add contract check size back in

- dapps/tests/app/app/contracts/simple_storage_test.sol
- dapps/tests/app/config/contracts.js
- packages/embark-contracts-manager/src/index.js
- packages/embark-ens/src/index.js
- packages/embark-specialconfigs/src/functionConfigs.js
- packages/embark-specialconfigs/src/index.js
- packages/embark-web3/src/index.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/index.js
This merges in the refactor/ENS branch.
> Re-add using ens names as arguments and onDeploy options

- dapps/tests/app/app/contracts/simple_storage_test.sol
- dapps/tests/app/config/contracts.js
- packages/embark-contracts-manager/src/contract.ts
- packages/embark-contracts-manager/src/index.js
- packages/embark-ens/src/index.js
- packages/embark-namesystem/.npmrc
- packages/embark-namesystem/README.md
- packages/embark-namesystem/package.json
- packages/embark-namesystem/src/index.js
- packages/embark-namesystem/tsconfig.json
- packages/embark-namesystem/tslint.json
- packages/embark-specialconfigs/src/functionConfigs.js
- packages/embark-specialconfigs/src/index.js
- packages/embark-storage/src/index.js
- packages/embark-web3/src/index.js
- packages/embark-whisper/src/index.js
- packages/embark/package.json
- packages/embark/src/cmd/cmd_controller.js
- packages/embark/src/lib/core/engine.js
- packages/embark/src/lib/modules/communication/index.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/index.js
Creates a new stack-component for embark-namesystem. It doesn't contain much, but makes sure to register nodes for namesystem, in this case ENS.
Refactors the embark-ens module to use the new events and polishes it a bit.
Rewired it too for the EmbarkJS part, but wasn't able to test it as the dashboard seems to be broken. I will do an additionnal PR once I have access to the dashboard or the console and I see that the EmbarkJS ENS functions don't work.
> Refactor ENS

- dapps/templates/demo/app/components/blockchain.js
- dapps/templates/demo/app/components/ens.js
- dapps/templates/demo/app/components/storage.js
- dapps/templates/demo/app/components/whisper.js
- dapps/templates/demo/app/dapp.css
- dapps/templates/demo/app/dapp.js
- dapps/templates/demo/app/index.html
- dapps/templates/demo/package.json
- packages/embarkjs/src/blockchain.js
- yarn.lock
The problem was that updating bootstrap broke react-bootstrap, so I changed to reactstrap because it's better and what we use in the cockpit too.
I also improve the style a tiny bit:
> Fix demo style and improve 

- packages/embark-contracts-manager/package.json
- packages/embark-contracts-manager/src/index.js
Makes the contract list work as well as contract functions.
The events (contract events for the logger) do not work yet, they require more changes
> Fix cockpit contract list and contract functions

- dapps/templates/demo/config/contracts.js
- packages/embark/src/lib/modules/blockchain/index.js
- packages/embark/src/lib/modules/ethereum-blockchain-client/index.js
- packages/embark/src/lib/modules/geth/blockchain.js
- packages/embark/src/lib/modules/geth/gethClient.js
- packages/embark/src/lib/modules/parity/blockchain.js
- packages/embark/src/lib/modules/parity/parityClient.js
- packages/plugins/web3/src/index.js
- packages/stack/communication/src/index.js
- packages/stack/namesystem/src/index.js
- packages/stack/proxy/src/proxy.js
- packages/stack/storage/src/index.js
This adds an action that is called before the blockchain starts so that a plugin can modify the blockchain configs.
Also, a couple of small fixes for bugs I discovered while coding the nim plugin
> Improvements and fixes for the nim compiler plugin

- packages/embark/src/lib/utils/template_generator.js
- packages/stack/communication/src/index.js
- packages/stack/namesystem/src/index.js
- packages/stack/storage/src/index.js
The template generator was broken on Windows
Also, the modules were trying to get started even if put as disabled
> Fix generating templates and fix the simple template run

- packages/plugins/ens/package.json
- packages/plugins/ens/test/index.js
Adds tests to the ENS module to chekc for the artifact and to check that we only register a subdomain when needed.
A lot more tests could be added, but a lot would have to be mocked, so I'm not sure what is needed/wanted.
> Add tests for ENS

- packages/cockpit/ui/src/components/ContractLog.js
- packages/plugins/transaction-logger/package.json
- packages/plugins/transaction-logger/src/index.js
> Show TX reason when there is a failure

- dapps/tests/app/app/contracts/expiration.sol
- dapps/tests/app/app/contracts/simple_storage.sol
- dapps/tests/app/test/another_storage_spec.js
- dapps/tests/app/test/expiration_spec.js
- dapps/tests/app/test/interface_spec.js
- dapps/tests/app/test/simple_storage_deploy_spec.js
- dapps/tests/app/test/simple_storage_spec.js
- packages/plugins/ethereum-blockchain-client/src/index.js
- packages/plugins/mocha-tests/src/lib/index.js
- packages/plugins/specialconfigs/src/functionConfigs.js
- packages/plugins/specialconfigs/src/listConfigs.js
- packages/plugins/web3/src/index.js
- packages/stack/proxy/src/proxy.js
- packages/stack/test-runner/package.json
- packages/stack/test-runner/src/lib/index.js
- site/package.json
- site/source/docs/contracts_testing.md
Fixes the test app to at least run. Before, it just hung.
Adds new testing features:
- `assert.reverts` to assert if a transaction reverts
- `assert.eventEmitted` to assert if  an event emitted
- `increaseTime` to increase the time of the EVM
Also adds the docs and tests for those
> Fix part of the test app and add new test util functions

- packages/stack/proxy/src/proxy.js
Add error handling to the proxy so that websocket frames are not sent on a socket that is not open.
> fix(@embark/proxy): Check if WebSocket open before sending

- packages/stack/compiler/package.json
- packages/stack/compiler/test/compiler.spec.js
- packages/utils/testing/src/lib/plugin.js
Details are attached to the individual commits.
> Add compiler module tests

- packages/core/console/src/lib/suggestions.ts
Update event name `"deploy:contract:deployed"` to `"deployment:contract:deployed"`.
Also, listen one time for `"deployment:deployContracts:afterAll"` and then request the full contracts list so as to pickup contract names that were already deployed. This is necessary for subsequent `embark run` (without reset), otherwise the suggestions list will be missing contracts.
---
Instead of listening one time for `"deployment:deployContracts:afterAll"`, maybe it would be enough to listen for `"deployment:contract:undeployed"`, thoughts?
> fix(@cockpit/console): show contract names in the suggestions list

- site/themes/embark/layout/partial/footer.swig
- site/themes/embark/source/css/04-objects/_objects.footer.scss
> chore(@embark-site): add all links to status network projects

- azure-pipelines.yml
See: https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#nodejsyarn
> ci: activate caching of yarn packages in azure pipelines

- packages/embark/src/cmd/cmd_controller.js
- packages/plugins/debugger/src/index.ts
- packages/plugins/ethereum-blockchain-client/src/api.js
- packages/stack/blockchain/src/api.ts
Re-enable debugger for cockpit and console.
Add missing request `blockchain:getTransaction` required to start a debugging session.
Fix error in console when stopping a debug session.
> fix(@embark/debugger): Re-enable debugger

- packages/plugins/geth/src/devtxs.ts
- packages/plugins/geth/src/index.js
Fix issue in which the dapp has a custom account defined the regular txs would not work since the dev account is not part of the list
> Dev txs fix

- packages/plugins/transaction-logger/src/index.js
The transaction logger takes care of intercepting any responses coming from the
blockchain proxy, determines what response it's dealing with and then extracts
information from the response to output useful log information to the user, such as
when a contract methods has been called etc.
It turned out that it didn't properly handle cases where value transactions
from account to account (such as done here in [Status Teller](https://github.com/status-im/status-teller-network/blob/a5ab4d4b26afccf15ac7472a18728385dd8b2461/embarkConfig/data.js#L100-L110)) have been made.
Since Embark couldn't map any of those accounts to actual contracts, while
still having stored corresponding transactions, it logged them as transactions
from "Unknown Smart Contracts".
This commit ensures via heuristics that, …
> fix(@embark/transaction-logger): handle non-contract transactions

- dapps/tests/app/app/index.html
- dapps/tests/app/app/js/index.js
- packages/cockpit/ui/src/containers/EnsContainer.js
- packages/cockpit/ui/src/reducers/selectors.js
For the test DApp, when ENS is enabled, ENS controls were not showing in Cockpit (under Utils), nor were they available to test in the DApp interface as they did not exist.
Fix ENS controls not showing in Cockpit when enabled.
Add ENS tab to Test DApp for ENS UI.
> fix(@embark/ens): Show ENS controls for Test DApp

- packages/core/engine/src/index.ts
As discussed in https://github.com/embark-framework/embark/pull/2143#issuecomment-566671315
> refactor(@embark/engine): move back to arrow functions and ...args

- site/README.md
updated the readme of the site changed the repo link and the change directory path
> docs: update site readme to the current repo

- packages/cockpit/ui/src/containers/EnsContainer.js
Removed loading component from rendering as it was causing the ENS components to unmount and ultimately not show ENS results.
> fix(@embark/cockpit): Remove loading from ENS util

- packages/plugins/ens/src/index.js
When the “register” section of `namesystem.json` was missing, ENS would not deploy the ENS contracts nor create the contracts’ artifacts.
Fix ENS deployment routine to always deploy the ENS contracts, regardless of whether or not the "register" config section exists. In the case of testnet/mainnet, the contracts’ addresses will be known and therefore will be understood as “already deployed” by the contract deployer.
If a root domain was specified in the “register” section of the config and the DApp connected to an external node where we do not own the ENS contracts (ie testnet), attempting to register a root domain would not be possible as we do not own the ENS contracts.
Fix ENS deployment routine to check if we are on a network in which we own the ENS contracts. If we are not, and we …
> fix(@embark/ens): Handle cases when no “register” in config

- packages/stack/watcher/src/index.js
The problem: "Our pipeline/watcher is a little dumb. If the artifacts are generated in src/, the watcher watched those files and when Embark creates the artifacts, it triggers a build, which triggers the artifacts, which.. well, you see the problem"
> fix(@embark/watcher): endless loop when artifacts are put in src

- packages/embark/src/cmd/cmd_controller.js
This fixes an issue on Discover (dap.ps). The build script didn't escape at the end because the event called too fast
> fix(@embark/cmd_controller): fix build command to escape on finish

- packages/core/console/package.json
- packages/plugins/suggestions/package.json
And remove `suggestions.json` in the `"files"` list of `packages/core/console/package.json` since it was moved to `packages/plugins/suggestions/suggestions.json`.
> chore(@embark/suggestions): include suggestions.json in the files to be packed by npm

- packages/stack/pipeline/src/index.js
generateAll was async, but it called the write functions with a sync
loop, so at the end of the function, the files were not written yet.
This is a problem in `embark build` because the process ends after
genrateAll is done, so no artifacts were written
> fix(@embark/pipeline): make generateAll async so it completes tasks

- packages/stack/communication/package.json
- packages/stack/communication/tsconfig.json
- yarn.lock
Went through the module dependencies and updated their versions or removed them when unused
> chore(stack/communication): update module dependencies

- site/source/docs/contracts_testing.md
Add docs for mineAtTimestamp and getEvmVersion and improve the
other ones a bit (typos, format, etc)
> docs(@embark/site): improve documentation on global test function

- packages/stack/deployment/package.json
- packages/stack/deployment/tsconfig.json
> chore(stack/deployment): update dependencies

- site/themes/embark/layout/docs.swig
- site/themes/embark/source/js/index.js
> chore: remove version switcher from docs layout

- site/source/docs/contracts_configuration.md
Change to smart contract and fix forProxy -> proxyFor
> fix(@embar/site): fix proxyFor docs

- packages/embark/src/cmd/cmd_controller.js
Only start a blockchain node when there is no --contracts flag and
start only needed modules for compilation
> fix(@embark/cmd-controller): fix build --contracts command starting comm node

- packages/core/console/src/index.ts
- packages/plugins/profiler/src/gasEstimator.js
- packages/plugins/profiler/src/index.js
The profiler was not formatted correctly in the console as `util.inspect` was being applied to the ASCII table before being output to the console REPL.
In addition, functions containing solidity assertions (require, revert, assert) that cause the function to fail when estimating gas would print an error to embark’s console log, and would show nothing as their gas estimate in the table.
Do not `util.inspect` command output if the result is a string. For API commands being run, allow the command to specify whether or not the output of the command should be HTML escaped. This could pose security risks!
For functions that have errors during gas estimation, add a message in the embark console explaining that the error may be due to solidity assertions in the function that prevent the gas from …
> fix(@embark/profiler): Fix profile output and update messaging

- packages/plugins/ethereum-blockchain-client/src/api.js
- packages/stack/blockchain/src/api.ts
- packages/stack/blockchain/src/index.js
> feat(stack/blockchain): expose networkId in generated artifact

- packages/plugins/vyper/README.md
See the associated PR https://github.com/embarklabs/blog/pull/18.
> chore(@embark/vyper): Update README for Vyper plugin

- packages/plugins/ethereum-blockchain-client/src/index.js
> chore(dashboard): change currency unit to Gwei and Ether in deployment output

- dapps/templates/boilerplate/app/index.html
- dapps/templates/demo/app/index.html
- dapps/tests/app/app/index.html
- dapps/tests/app/app/test.html
- dapps/tests/app/app/test2.html
> fix(@embark/dapps): use utf-8 in html script tag
